### ISSUE TITLE
Prevent writing b2 file information to stdout when using download-file

### ISSUE THREAD

**Issue by jpsalm** [Backblaze/B2_Command_Line_Tool#1031]
I want to be able to download a file using the b2 and send it straight for processing without having to write it to disk first.

e.g. `b2 download-file b2://my-bucket/my-file --no-progress - | process-file`

Currently, the metadata printed to stdout by b2 is interfering with that:

```
File name:         
File id:             
Output file path:  
File size:       
Content type:
...
```

Please either give us an option to suppress this, or suppress it for me when using stdout as the output file.

**Comment by ppolewicz** [comment]
Try `b2 cat`

**Comment by jpsalm** [comment]
Awesome, thanks, you can close this :)
