### ISSUE TITLE
[Question or Feature Request]

### ISSUE THREAD

**Issue by UgurKap** [Backblaze/B2_Command_Line_Tool#1033]
Hello, when you sync a directory with b2, it seems to be just uploading the original files if you have a symbolic link. I am not aware if there is a way to exclude symbolic links from uploading. If there is, it would be pretty neat.

**Comment by mjurbanski-reef** [comment]
`b2 sync --help` provides a description of all available options, including `--exclude-all-symlinks` which seems to be what you are searching for

**Comment by UgurKap** [comment]
Ah, okay. My bad, thanks for the great tool and very fast support :)
