### ISSUE TITLE
Delete a list of files

### ISSUE THREAD

**Issue by pedz** [Backblaze/B2_Command_Line_Tool#1043]
I have 25TB in b2 storage and many files are duplicates of other files.  I have gone through a long process to find these duplicates and now I have a long list (roughly 17,000,000) of files I want to duplicate.  The process of `b2 rm B2_URI` will take roughly a year at the current rate.  I tried `b2 rm B2_URI B2_URI` but it didn't like it.

Is there an existing way to speed this up.  If not, is there an interest in adding it?

**Comment by ppolewicz** [comment]
How are you running `b2 rm B2_URI`, synchronously?

It kind of feels like `xargs` and a server which won't fall from all the load might be the solution to the problem, but maybe I'm misunderstanding something?

**Comment by pedz** [comment]
Yes.  Something like: `cat list.txt | while read f ; do b2 rm $f ; done`

Its been going for a day and I've done 150,000.  So, roughly 113 days.  I can do that.  Its simple.  But I thought I would ask.

**Comment by ppolewicz** [comment]
I think you can do it 10-20 times faster if you use `xargs`. Also, please always quote strings in bash, so `"$f"` rather than `$f` (google `bumblebee bug github` to find out why - one time someone didn't quite and now it's a meme)

**Comment by pedz** [comment]
I use zsh.  I'm on a Mac.  With xargs, I can't put multiple B2_URL on the same command -- right?  I tried it and it complained.

**Comment by pedz** [comment]
Thank you.  I didn't have the --delimiter option so I used `tr '\n' '\0'` and then used the `-0` option.  I could remove about 1000 files per minute.

Plus, I sorted the files largest to smallest and after 450000 files, the rest of the files would add up to about 500G which doesn't seem worth the bother.
