### ISSUE TITLE
sync: ERROR: unknown error: 400 bad_request large files not available yet

### ISSUE THREAD

**Issue by alanfranz** [Backblaze/B2_Command_Line_Tool#111]
Hello,
I'm using b2 0.5.0 on python 2.7, Ubuntu 14.04 64 bit.

I wanted to sync again after I had already sync with a previous version of b2 (0.4.10 afaik), and I get this error:

```ERROR: unknown error: 400 bad_request large files not available yet```

the largest file in the source directory is 427M, while the file it's trying to upload is about 201M.

```
root@amaranta:/other/localbackup# /root/tools/backblaze/bin/b2 version
b2 command line tool, version 0.5.0
root@amaranta:/other/localbackup# ls -lh -S | head
total 152G
-rw------- 1 root root 427M Jun  4  2015 duplicity-full-signatures.20150604T075332Z.sigtar.gpg
-rw------- 1 root root 201M Sep  3  2015 duplicity-inc.20150902T014501Z.to.20150903T014502Z.vol2.difftar.gpg
-rw------- 1 root root 201M Nov 15 03:47 duplicity-inc.20151114T024507Z.to.20151115T024505Z.vol7.difftar.gpg
-rw------- 1 root root 201M Jun 26  2015 duplicity-inc.20150625T014502Z.to.20150626T014502Z.vol3.difftar.gpg
-rw------- 1 root root 201M Nov 18 03:46 duplicity-inc.20151117T024502Z.to.20151118T024503Z.vol1.difftar.gpgERROR: unknown error: 400 bad_request large files not available yet
-rw------- 1 root root 201M Sep 25  2015 duplicity-inc.20150924T014501Z.to.20150925T014503Z.vol6.difftar.gpg
-rw------- 1 root root 201M Jan 12 03:51 duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol4.difftar.gpg
-rw------- 1 root root 201M Nov 14 03:46 duplicity-inc.20151113T024503Z.to.20151114T024507Z.vol2.difftar.gpg
-rw------- 1 root root 201M Aug  5  2015 duplicity-inc.20150804T014501Z.to.20150805T014501Z.vol1.difftar.gpg
root@amaranta:/other/localbackup# /root/tools/backblaze/bin/b2 sync ./ b2:amarantabackup
+ duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol6.difftar.gpg
ERROR: unknown error: 400 bad_request large files not available yet
root@amaranta:/other/localbackup# ls -l duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol6.difftar.gpg
-rw------- 1 root root 209718570 Jan 12 03:52 duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol6.difftar.gpg
root@amaranta:/other/localbackup# ls -lh duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol6.difftar.gpg
-rw------- 1 root root 201M Jan 12 03:52 duplicity-inc.20160111T024504Z.to.20160112T024503Z.vol6.difftar.gpg
root@amaranta:/other/localbackup# 
```

pip freeze output in b2 virtualenv:

```
b2==0.5.0
cffi==1.5.2
cryptography==1.3.1
enum34==1.1.2
idna==2.1
ipaddress==1.0.16
ndg-httpsclient==0.4.0
portalocker==0.5.7
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==16.0.0
requests==2.9.1
six==1.10.0
```

**Comment by alanfranz** [comment]
I've just tried downgrading to 0.4.10 and now it's working, so I guess the issue was introduced in 0.5.0.

**Comment by ppolewicz** [comment]
Large files were enabled in 75b611055b35f4138eaa55ac02dcec1ea31f97c6. I don't know why API returns such error now - I suspect B2 had to reverse enabling large files due to some server-side issue tonight. Please use 0.4.10 for a few hours while it is investigated.

**Comment by alanfranz** [comment]
OK.

One small thought: I've took a look at the bucket.py code. It seems that the large file API is employed whenever it can be employed, that is whenever the file is > minimum supported large file size. Such file size is calculated as minimum part size (dynamically fetched from account info) * 2.

My 2c:
1) I don't really understand such calculations; b2 page says that both the minimum part size and the minimum large file size is 100MB https://www.backblaze.com/b2/docs/large_files.html
2) Is there a point in using large file as much as possible? It's easier for resuming interrupted uploades? Otherwise I'd think about reversing the logic, and using the large file function only when the source files exceed the standard file limit (5GB AFAIK).

**Comment by ppolewicz** [comment]
Parallel upload is usually faster. Also if a failure happens, you can resume a failed part, so the smaller part there is, the smaller amount of data needs to be uploaded again.

**Comment by bwbeach** [comment]
My apologies for your trouble.  It looks like the B2 server updates that were supposed to happen yesterday afternoon, before the release of version 0.5.0, did not happen until this morning.  I just tested a large file upload myself, and found that it worked.

For now, there is no advantage to using the large file API and uploading a file in parts.  For the future, @ppolewicz is right that parallel uploads will improve performance.  We are in the process of implementing parallel uploads for large files.

**Comment by ppolewicz** [comment]
Can we close this now?

**Comment by alanfranz** [comment]
I hadn't got the chance to test this again. It works properly with backblaze servers now, I tested 0.5.2.
