### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' 

### ISSUE THREAD

**Issue by jcalonso** [Backblaze/B2_Command_Line_Tool#115]
I'm having the the following error, on the latest version of the cli tool (0.5.2)

```
jcalonso@my-server:/media/data# b2 sync myData b2:myBucket/myData
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.5.2', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 782, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 258, in run_command
    return self.sync(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 736, in sync
    self._print("+ %s" % filename)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 292, in _print
    print(*args, file=self.stdout)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 44: ordinal not in range(128)

```

**Comment by bwbeach** [comment]
Thanks for the bug report.  I'll be working on sync this week, and will get this fixed.

**Comment by bwbeach** [comment]
Python uses sys.stdout.encoding to decide how to translate unicode to bytes when printing to stdout.  My guess is that your encoding is set to 'ascii', which means that it won't be able to print unicode.  

My environment has 'utf-8' as the default encoding for sys.stdout, and it works for me.

I'm not sure what the right thing to do is.   When the encoding is unicode-capable, things should work.  When it's not, what should the code do?

**Comment by bwbeach** [comment]
@jcalonso - I think that you could get around this by setting LANG to use an encoding that can print the characters in your file names.   Here's a quick experiment I ran:

    $ echo $LANG
    en_US.UTF-8
    $ python
    Python 2.7.11 (default, Mar  7 2016, 13:29:38) 
    >>> import sys ; sys.stdout.encoding
    'UTF-8'
    >>> print u'\u81ea'
    自
    >>> 
    $ export LANG=en_US.ASCII
    $ python
    Python 2.7.11 (default, Mar  7 2016, 13:29:38) 
    >>> import sys ; sys.stdout.encoding
    'US-ASCII'
    >>> print u'\u81ea'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u81ea' in position 0: ordinal not in range(128)

Any suggestions for what the b2 command should do when it can't print the file names?

**Comment by ppolewicz** [comment]
We should catch this and return an appropriate error message, like "your terminal cannot output Unicode in its current configuration. You can fix it by..."

**Comment by jcalonso** [comment]
Just to complement the information, my terminal LANG is set to `en_GB.UTF-8`

**Comment by bwbeach** [comment]
That's interesting.  I wonder what your sys.stdin.encoding is.

**Comment by ppolewicz** [comment]
@jcalonso please tell us what happens when you start `python` and type this in:
```python
import sys
print sys.stdin.encoding
```

**Comment by jcalonso** [comment]
```
$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.stdin.encoding
UTF-8
>>>
```

**Comment by bwbeach** [comment]
When I test on Windows, I get this:

    >>> import sys
    >>> sys.stdout.encoding
    'cp437'

Apparently this is [normal on Windows](https://wiki.python.org/moin/PrintFails#Windows).

**Comment by bwbeach** [comment]
This test case exhibits the problem on Mac:

    PYTHONIOENCODING=ascii python -m b2 ls <bucketName>

**Comment by seb2411** [comment]
I have the same problem it seem with the version 0.5.6.

```
b2 sync /backup b2://mybucket/path
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.5.6', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 873, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 806, in run_command
    self._print_stderr('ERROR: %s' % (str(e),))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2011' in position 25: ordinal not in range(128)
```

**Comment by abeusher** [comment]
I experienced this and solved the problem by removing dashes/hyphens from my bucket names.  Try doing this with a bucket name that is 100% alpha numeric.

**Comment by RX14** [comment]
I'm on backblaze-b2 version `0.6.2`.

```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE=en_GB.UTF-8
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES=en_GB.UTF-8
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
$ backblaze-b2 sync --delete --replaceNewer /foo b2://bucket-with-dashes/
Traceback (most recent call last):
  File "/usr/bin/backblaze-b2", line 11, in <module>
    load_entry_point('b2==0.6.2', 'console_scripts', 'b2')()
  File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 879, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 811, in run_command
    self._print_stderr('ERROR: %s' % (str(e),))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2011' in position 23: ordinal not in range(128)
```

Removing the hyphens fixes the error, but this isn't an acceptable issue, please reopen.

**Comment by ppolewicz** [comment]
Ok this is actually #266: user copied the bucket name from web interface, where it was displayed in a malformed manner. No actual hypens were used - instead `\u2011` (NON-BREAKING HYPHEN) was passed to the CLI. We've fixed the exceptions and we requested the cloud team to stop using NON-BREAKING HYPHEN in their UI.
