### ISSUE TITLE
download_file_by_name and download_file_by_id spool file in RAM

### ISSUE THREAD

**Issue by nilayp** [Backblaze/B2_Command_Line_Tool#116]
I and others have observed that when using download_file_by_name or download_file_by_id, the file you are downloading spools into RAM and only getting written to disk when it's fully downloaded. 

Therefore, a file larger than the amount of RAM in your system will crash. Is there a way to periodically flush the downloading file to disk?

**Comment by bwbeach** [comment]
I believe this was fixed in the latest release, 0.5.2.

**Comment by nilayp** [comment]
Excellent. I confirmed that it's working properly with 0.5.2.

It would be great if we can somehow notify the user when they are using an outdated CLI. 90% of CLI support tickets are solved with `pip install b2 --upgrade`. :)
