### ISSUE TITLE
No such bucket: <bucket id>

### ISSUE THREAD

**Issue by frdmn** [Backblaze/B2_Command_Line_Tool#12]
I just created a new bucket using the CLI:

```shell
$ b2 create_bucket public01 allPublic
af37c3b95c4aa1fd5fXXXX
```

When I list all available buckets, I can also see that backblaze created it succesfully:

```shell
$ b2 list_buckets
af37c3b95c4aa1fd5fXXXX  allPublic   public01
```

But as soon as I try to upload a file or list existing files, It throws the `No such bucket: af37c3b95c4aa1fd5fXXXX` error message:

```shell
$ b2 upload_file af37c3b95c4aa1fd5fXXXX D7V_7370.jpg D7V_7370.jpg
No such bucket: af37c3b95c4aa1fd5fXXXX

$ b2 ls af37c3b95c4aa1fd5fXXXX
No such bucket: af37c3b95c4aa1fd5fXXXX

```

I added `print response` below line `443` for debugging purposes - not sure if that helps:

```shell
$ b2 ls af37c3b95c4aa1fd5fXXXX
{u'buckets': [{u'bucketType': u'allPublic', u'bucketId': u'af37c3b95c4aa1fd5fXXXX', u'bucketName': u'public01', u'accountId': u'f739ca1dXXXX'}]}
No such bucket: af37c3b95c4aa1fd5fXXXX
```

**Comment by pgonin** [comment]
upload_file syntax recently changed.
you should use Bucket Name now and not Bucket Id

```
$ b2 upload_file public01 D7V_7370.jpg D7V_7370.jpg
```

**Comment by bwbeach** [comment]
That's right.  It now takes the bucket name.  We thought that would be easier to deal with.  Sorry for the confusion.

**Comment by ferricoxide** [comment]
While human-friendly names are better for interactive tool-use, depending on outputs of other operations, it might be better if the _default_ is human-friendly but overridable to be ID number.

**Comment by frdmn** [comment]
Thanks for the udate!
