### ISSUE TITLE
In-memory cache mixin for AccountInfo classes

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#132]
To reduce I/O, some information could be safely cached in memory:
1. bucket name / id mapping
2. minimum part size
3. account_id / auth_token / api_url / realm
4. download_url

**Comment by ppolewicz** [comment]
@bwbeach, do you think all of them can be cached? I think those will change only in corner case, so if a change is committed to a database, parallel processes could refresh the information on their own, right?

**Comment by bwbeach** [comment]
Yes.  I think they can all be cached.  The minimum part size never changes.  And we have ways to refresh the rest when they are stale.

In general, I prefer delegation to mixins and inheritance.  But I'm open to a different approach.

**Comment by ppolewicz** [comment]
The idea here is to provide an ability for classes which implement `AccountInfo` interface to have an in-memory caching layer, which will handle some requests without touching underlying storage, so that it would avoid initialization and reading from an sqlite3 database so frequently.

**Comment by ppolewicz** [comment]
We have `InMemoryAccountInfo`, `AuthInfoCache` and `InMemoryCache` for years now.
