### ISSUE TITLE
Resuming large file uploads

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#137]
When uploading a large file, it's annoying to have it fail after uploading most of the parts, and then have to start the whole process over again.  It would be better to check and see if there is a matching upload (file name, content type, etc.) already in progress with parts that match the file being uploaded, and then continuing from there.

**Comment by svonohr** [comment]
This is a very useful feature. I will try to implement it. How should multiple unfinished files with the same name be handled? Do we just check the filename, file info and part size or also verify the SHA-1 hash of already uploaded parts?

**Comment by bwbeach** [comment]
I think it should verify the SHA1 of the uploaded parts.  If they don't match, you'll get an error at the end, and it will be frustrating.

**Comment by bwbeach** [comment]
It could be that two invocations try to resume the file.  I'm not sure how to prevent that, or how much to worry about it.
