### ISSUE TITLE
The script, b2, linked from the documentation, is broken

### ISSUE THREAD

**Issue by dotemacs** [Backblaze/B2_Command_Line_Tool#14]
Following the steps from your documentation on B2 usage here: https://www.backblaze.com/b2/docs/quick_bucket.html

and downloading the b2 script (not from this repo, but from the link provided in the documentation), after running:

`b2 authorize_account ACCOUNT_ID ACCOUNT_KEY`

I get:

```
Traceback (most recent call last):
  File "/Users/alex/bin/b2", line 949, in <module>
    main()
  File "/Users/alex/bin/b2", line 912, in main
    authorize_account(args)
  File "/Users/alex/bin/b2", line 355, in authorize_account
    url = auth_urls[option]
KeyError: '--production'
```
This is under Python 2:

```
$ which python
/usr/local/bin/python
$ python --version
Python 2.7.9
```
b2 script version:

```
b2 version
b2 command line tool, version 0.3.5
```

After downloading the script from this repo, version 0.3.7. the script works as expected and outlined in your documentation.

**Comment by bwbeach** [comment]
Yep.  Will be fixed in the web site refresh today.
