### ISSUE TITLE
Sync command error:  destination file is newer

### ISSUE THREAD

**Issue by alanfranz** [Backblaze/B2_Command_Line_Tool#144]
Hello,
I've just upgraded my b2 client from 0.5.0 to 0.5.4; now the sync command yields this error:

```
root@amaranta:/other/localbackup# /root/tools/backblaze/bin/b2 sync --delete ./ b2:amarantabackup
ERROR: destination file is newer: duplicity-full-signatures.20160422T100919Z.sigtar.gpg
```

this is the local file information (rest assured it was NEVER altered after creation):

```
root@amaranta:/other/localbackup# ls -l --time-style="full-iso" duplicity-full-signatures.20160422T100919Z.sigtar.gpg
-rw------- 1 root root 1114394497 2016-04-22 15:08:23.830379590 +0200 duplicity-full-signatures.20160422T100919Z.sigtar.gpg
```

The web gui for this file says:

```
duplicity-full-signatures.20160422T100919Z.sigtar.gpg 1.1 GB 04/22/2016 19:24
```

The last columns says "uploaded", by the way.

I see two problems here:

1) Is there a timezone issue? The web GUI doesn't make the timezone explicit - should I assume UTC?
2) There seems to be a creation vs upload time conflict. The upload time happens, of course, after creation time. The complaint about "destination file being newer" seems pointless.

There's another issue (which I think is separate) that I'll report separately.

**Comment by svonohr** [comment]
I'm not familiar with the sync command myself, but I know that there were significant changes in the newest version (0.5.4). Could you try that one?

**Comment by alanfranz** [comment]
@svonohr I had read the version improperly. I am using 0.5.4.

**Comment by bwbeach** [comment]
I'll look into this.  There was a problem where fileInfo wasn't getting saved with large files, so the modification time wasn't getting set properly.   This is definitely a large file, so it would have had that problem prior to 0.5.4.  Not sure what's going on now.

**Comment by bwbeach** [comment]
And to answer your question, all times should be in UTC.

**Comment by mjurbanski-reef** [comment]
If still occurring, please reopen this issue.
