### ISSUE TITLE
Sync command skipNewer replaces unmodified files

### ISSUE THREAD

**Issue by alanfranz** [Backblaze/B2_Command_Line_Tool#145]
After the facts described in #144 , I tried sync (b2 v 0.5.4) with the seemingly new ```--skipNewer``` option, which should act as a workaround to my issue.

This is what happened:

```
root@amaranta:/other/localbackup# /root/tools/backblaze/bin/b2 sync --skipNewer --delete ./ b2:amarantabackup
delete duplicity-inc.20160430T014501Z.to.20160501T014502Z.manifest.gpg (old version)
delete duplicity-inc.20160430T014501Z.to.20160501T014502Z.vol1.difftar.gpg (old version)
delete duplicity-inc.20160429T014502Z.to.20160430T014501Z.manifest.gpg (old version)
upload duplicity-inc.20160429T014502Z.to.20160430T014501Z.manifest.gpg
upload duplicity-inc.20160501T014502Z.to.20160502T014501Z.manifest.gpg
upload duplicity-inc.20160430T014501Z.to.20160501T014502Z.manifest.gpg
delete duplicity-new-signatures.20160430T014501Z.to.20160501T014502Z.sigtar.gpg (old version)
delete duplicity-new-signatures.20160429T014502Z.to.20160430T014501Z.sigtar.gpg (old version)
delete duplicity-full.20160422T100919Z.vol37.difftar.gpg (old version) 
upload duplicity-inc.20160430T014501Z.to.20160501T014502Z.vol1.difftar.gpg
upload duplicity-new-signatures.20160501T014502Z.to.20160502T014501Z.sigtar.gpg
upload duplicity-new-signatures.20160430T014501Z.to.20160501T014502Z.sigtar.gpg
delete duplicity-full.20160422T100919Z.vol45.difftar.gpg (old version)   
upload duplicity-new-signatures.20160429T014502Z.to.20160430T014501Z.sigtar.gpg
upload duplicity-inc.20160501T014502Z.to.20160502T014501Z.vol1.difftar.gpg
```

Unluckily, I hadn't saved a screenshot of the web gui before doing that, so I don't know what it did show.

But, rest assured again that the files were totally unmodified since they were originally uploaded, but the tool somehow detected they were changed (locale timestamp > remote timestamp?) and reuploaded them.

I'm including a full ```ls -l``` for the first reuploaded file:

```
root@amaranta:/other/localbackup# ls -l --time-style="full-iso" duplicity-inc.20160430T014501Z.to.20160501T014502Z.manifest.gpg 
-rw------- 1 root root 233 2016-05-01 03:49:12.653555465 +0200 duplicity-inc.20160430T014501Z.to.20160501T014502Z.manifest.gpg
```

What I notice, right now, is that such files' "uploaded" column in the web gui matched the LOCAL creation time:

```
duplicity-inc.20160430T014501Z.to.20160501T014502Z.manifest.gpg 233.0 bytes 05/01/2016 03:49
```

I don't know whether the webgui is autodetecting my browser's timezone or doing geolocalization otherwise, or there's a "timezone stripping" issue which should be fixed.

Also, it seems that, by now, the "uploaded" field with the "sync" command doesn't actually save the "uploaded time", but the "original creation" time - which is a bit of a different beast, isn't it?

Thanks.

**Comment by bwbeach** [comment]
I'll look into this.  Thanks for the report.

**Comment by bwbeach** [comment]
Both the sync command and the web UI should use the modification time of the file when setting src_last_modified_millis, which is what the sync command uses to determine which file is newer.

I just tried uploading a file with the web UI, and then syncing the same file.  Sync didn't do anything because the modification times matched.

My best guess is that the src_last_modified_millis wasn't set when the original file was uploaded.  If you uploaded with the b2 command-line tool, only the latest version is setting the modification time properly for large files.

**Comment by alanfranz** [comment]
Hello,
that makes some sense, but it's still a bit strange IMHO.

Some details:

1) Everything was uploaded with the b2 command line client, older versions (0.5.0 or 0.5.2). So they won't have the src_last_modified_millis metadata set.

2) There were more files than the ones I showed in the log: 175 in total, but the sync only tried to re-uploaded those seven, and I still wouldn't understand why, in such case. Let me know if I can use the API someway and show you the metadata you need.

3) This night the backup has worked properly, and only uploaded the 3 new files that were generated.


So, if you think everything makes sense, feel free to close this issue.
