### ISSUE TITLE
Provide an "exclude" option for the b2 sync command

### ISSUE THREAD

**Issue by segphault** [Backblaze/B2_Command_Line_Tool#150]
It'd be really useful to be able to exclude paths that match a certain pattern from synchronization. For example, if I'm synchronizing a bunch of node.js projects, I might want to have b2 sync ignore all the node_modules folders.

**Comment by bwbeach** [comment]
Good idea. 

Do you want the excluded things to be wildcards?  Regexp or glob?  Match the entire path, or just the file name?

I assume that if a folder is excluded, everything under it should be excluded, too.

**Comment by segphault** [comment]
For the case that I care about personally, I want to be able to match just the file name rather than the whole path, but I could see the latter also being useful in some situations. I'd like to be able to do something like `--exclude "node_modules"` and have it exclude directories that match that name everywhere they appear in the hierarchy.

Wildcards would also be great, I think either glob or regex would work well. And yep, it'd also skip the contents of excluded folders. Thanks!

**Comment by segphault** [comment]
I decided to take a crack at implementing this myself. Given the way that the sync feature builds its file list, matching against the full path ended up being the most practical and least intrusive approach. I also decided on using a regex for the match.

**Comment by sund** [comment]
I would also like to see rsync-style exclusion and inclusion, i.e. from the rsync help:

`
--exclude=PATTERN     exclude files matching PATTERN

--exclude-from=FILE     read exclude patterns from FILE

--include=PATTERN     don't exclude files matching PATTERN

--include-from=FILE     read include patterns from FILE
`

Just my thoughts.

**Comment by ppolewicz** [comment]
@sund this seems like a very small change after #153 is merged. Would you like to implement the options you mentioned?

**Comment by TJC** [comment]
Just wanted to say -- I think you should try and implement the same exclude patterns as rsync; they've become reasonably well-understood by many people, and supported by third-party apps.

**Comment by ppolewicz** [comment]
@TJC @sund @segphault do you still need this?

**Comment by simongreen-net** [comment]
I would like to see this option.

**Comment by ppolewicz** [comment]
@simongreen-net okay. Would you like to implement it?

We encourage outside contributors to perform changes on our codebase. Many such changes have been merged already. In order to make it easier to contribute, core developers of this project:

* provide guidance (through the issue reporting system)
* provide tool assisted code review (through the Pull Request system)
* maintain a set of integration tests (run with a production cloud)
* maintain a set of (well over a hundred) unit tests
* automatically run unit tests on 14 versions of python (including osx, Jython and pypy)
* format the code automatically using [yapf](https://github.com/google/yapf)
* use static code analysis to find subtle/potential issues with maintainability
* maintain other Continous Integration tools (coverage tracker)

this particular change is rather easy to implement.

**Comment by simongreen-net** [comment]
Sorry, my Python skills aren't at a level where I would be able to write a patch.

**Comment by sund** [comment]
I would also like this. But, like, @simongreen-net my python-fu depends on google more than it should.

**Comment by ppolewicz** [comment]
ok, I have somebody working on this. Assigning myself as a placeholder.

**Comment by TJC** [comment]
@ppolewicz -- Yes, I'd still like to see this feature.. but my Python skills aren't really up there, sorry.

**Comment by therecluse26** [comment]
Just my two cents... I think that instead of (or inaddition to) having a regex-based ignore function it'd be way more helpful to enable a sort of "ignore" file with a list of all the excluded sync directories, much like the way that the .gitignore file works.

**Comment by dougwollison** [comment]
@therecluse26 agreed. I'm personally very fond of the --filter=[file] option in rsync; I can have a nice include/exclude ruleset so that I can sync just what I need.

**Comment by therecluse26** [comment]
Any updates on this?

**Comment by ppolewicz** [comment]
#244 has been merged

as for `--exclude-from=FILE` and `--include-from=FILE`, maybe one day someone will contribute it, when doing so please reference this issue. For now, lets close it.

**Comment by dctremblay** [comment]
This would be nice to be able to exclude by regex, avoiding to backup cache files.
