### ISSUE TITLE
Feature Request: Ability to rename bucket

### ISSUE THREAD

**Issue by abraunegg** [Backblaze/B2_Command_Line_Tool#159]
As per the title, it would be great to have an additional command to rename a b2 bucket via the CLI

eg:
```
b2 rename_bucket <original_name> <new_name>
```

**Comment by bwbeach** [comment]
Unfortunately, the B2 service does not support renaming buckets.  If that feature is ever added to the service, we'll add it to the command-line tool.

**Comment by LinuxOnTheDesktop** [comment]
I second the request. Also, I would like to know what the recommended workaround is. Must one create a copy of the bucket, with the copy having the name that one wants for switch to, and then delete the old bucket? Presuming yes: what is most efficient way of creating the copy?
