### ISSUE TITLE
Feature Request: Ability to sync data between 2 b2 buckets

### ISSUE THREAD

**Issue by abraunegg** [Backblaze/B2_Command_Line_Tool#160]
It may be desirable at some point to make a new b2 bucket as a b2 'backup' before some destructive change to a local source replicating to a destination b2 bucket

To make this 'backup' on the b2 server side, the sync command could be used to replicate the data before making any local changes which may get replicated in an undesirable fashion.

The issue currently however, is that the b2 sync command expects 1 of the 'source' or 'destination' folders to be a local folder:

```
-bash-4.1# b2 sync b2://564dcdc2-4a25-fc44-af2a-b369d22dfa7d/* b2://564df3d9-26c9-bc34-6e42-a042e0948d28/
Traceback (most recent call last):                                 
  File "/usr/bin/b2", line 9, in <module>
    load_entry_point('b2==0.5.7', 'console_scripts', 'b2')()
  File "/usr/lib/python3.5/site-packages/b2/console_tool.py", line 873, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/lib/python3.5/site-packages/b2/console_tool.py", line 801, in run_command
    return command.run(args)
  File "/usr/lib/python3.5/site-packages/b2/console_tool.py", line 621, in run
    max_workers=max_workers
  File "/usr/lib/python3.5/site-packages/b2/sync.py", line 897, in sync_folders
    raise ValueError('neither folder is a local folder')
ValueError: neither folder is a local folder
```

Both s3cmd and gsutil are capable of syncing between buckets server side.

**Comment by nicolas17** [comment]
Both s3cmd and gsutil are capable of syncing between buckets server side, because both S3 and Google Cloud Storage have APIs to quickly copy files in the server. B2 doesn't, so the only way a "b2 sync b2://foo b2://bar" can work is by downloading all of your data and uploading it again to the destination.

Backblaze would need to add the ability to copy files between two B2 buckets first. This can't be fixed in the command line tool alone (which is what this github repository is about).

**Comment by ppolewicz** [comment]
As @nicolas17 said, it is request for a new API capability. Those should be sent to `b2contact at backblaze.com`, not filed here as issues. On the other hand, if the cloud side would support copying data between buckets and the CLI would not, here would be an appropriate place to request it.

**Comment by crazyshot** [comment]
I suggest reopening this.
The API seems to support it: https://www.backblaze.com/b2/docs/b2_copy_file.html

**Comment by ppolewicz** [comment]
This was already implemented a while ago, sync supports server-side bucket-to-bucket sync for a while now
