### ISSUE TITLE
Possible datarace in sync/account info

### ISSUE THREAD

**Issue by svonohr** [Backblaze/B2_Command_Line_Tool#162]
Using the b2 sync command I got this error:
`b2_upload(...): UnknownError('400 bad_request more than one upload using auth token xxxx_001_upld',) unknown error: 400 bad_request more than one upload using auth token xxxx_001_upld`

I can't reproduce this error, so it only seems to happen rarely. I think this is the second time I had this error.

**Comment by ppolewicz** [comment]
@svonohr did it reproduce since May?

**Comment by svonohr** [comment]
No, but I haven't been playing arround with the b2 cli in a while. Didn't we move the caching of auth tokens to RAM instead of the sqlite DB? If we did, then this bug is probably resolved.

**Comment by ppolewicz** [comment]
It is in RAM only and protected by a threading lock. Closing.
