### ISSUE TITLE
Command to delete files

### ISSUE THREAD

**Issue by svonohr** [Backblaze/B2_Command_Line_Tool#165]
I would like to see a unix-like `rm` command to accompany the `ls` command. The command should allow mass deletion of files matching a glob. The current `delete_file_version` command is rather complicated to use and we should have a more high-level command.

This command will also allow clearing an entire bucket, which was already worked on in #58.

**Comment by dmanikowski-reef** [comment]
I've implemented an 'rm' command. It is waiting for our internal review and we will make a PR as soon as it is ready :)

**Comment by yury-tokpanov** [comment]
Is it still under review?

**Comment by ppolewicz** [comment]
It has been implemented a long time ago, you can find the newest documentation here: https://b2-command-line-tool.readthedocs.io/

**Comment by yury-tokpanov** [comment]
Thanks! You should probably put a link to that doc on your website as well.
