### ISSUE TITLE
Handle ECONNRESET errors

### ISSUE THREAD

**Issue by svonohr** [Backblaze/B2_Command_Line_Tool#172]
This is a split from #163.
I did some investigation and found that probably the fall through case in `_translate_errors` function was executed. Maybe this is a problem with the requests library, since the documentation suggests that only a few types of exceptions may occur. The `SysCallError(104, 'ECONNRESET')` is not one of them.

**Comment by svonohr** [comment]
I was able to reproduce `ECONNRESET` by creating a fake server. On my system the `requests` library handles the error properly and the exception has the type `requests.exceptions.ConnectionError`. Though the wrapped exception type is different between Python versions:
Python 2: `('Connection aborted.', error(104, 'Connection reset by peer'))`
Python 3: `('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

Both messages are different from the one reported by @alanfranz.

**Comment by alanfranz** [comment]
@svonohr sorry for the long time it took me to get here, I seem to have missed the notification.

The error I reported in #163 was obtained on Ubuntu 14.04 64 bit, usually on a fully patched system.

**Comment by ppolewicz** [comment]
SysCallError was a python2-specific issue and we've dropped python2 already
