### ISSUE TITLE
Exit status when some files fail syncing

### ISSUE THREAD

**Issue by svonohr** [Backblaze/B2_Command_Line_Tool#174]
This is a split from #163.
I can confirm that the exit status is 0, even when some of the files couldn't be synced. It can be easily reproduced by trying to sync a file that cannot be read by the current user. If some sync actions failed we could summarize them in a report at the end.

**Comment by mdeboer** [comment]
Yes, same here. There is no way to know on the exit status if some files failed unfortunately. It is vital this is fixed!
