### ISSUE TITLE
How to rename file?

### ISSUE THREAD

**Issue by lastdates** [Backblaze/B2_Command_Line_Tool#175]
Can there be a way to rename a file in bucket, and rename bulk of files as rename folder?

**Comment by ppolewicz** [comment]
B2 api does not have such functionality. You'd have to download and upload the files in order to rename them, which would be costly. Thus, b2 CLI does not have such function.

**Comment by ahildoer** [comment]
That, is, nuts!

**Comment by ppolewicz** [comment]
Actually, it may be very clever:
- B2 is a cost-efficient storage with high resiliency
- renaming is a rare requirement (as we can see by the activity in this ticket, someone complains about this roughly once every 23 months)

I have researched b2 consistency model extensively about a year ago and one could build a consistent storage with an abstraction layer for fast renaming of files using b2 as the only storage medium. It would be slower than the current solution, but it would work reliably. Thanks to recent release of [compute partners](https://www.backblaze.com/blog/introducing-cloud-compute-services/), one could even amortize the cost of metadata operations. It would be an interesting project, but it seems almost nobody needs it.

**Comment by jeremybrown82** [comment]
I need the support to rename files, pity it does not.

**Comment by dkocher** [comment]
Duplicate for #57.

**Comment by ppolewicz** [comment]
BTW s3 does not let you rename files either, nor does Azure blob storage or object storage of Google object storage. Some of those have a rename option which performs an internal copy and removes the source file, but that's not atomic and not a rename, really.

**Comment by ahildoer** [comment]
Non-atomic, server side copy is infinitely better than no kind of rename at all. I had to rename a 56GB file on B2, which means re-uploading. For fun I uploaded to AWS S3 and Wasabi, then did a server side rename. It took several seconds. B2 took the time to upload the file again. And, the B2 upload method was significantly more of a problem as I had to have my application offline for about 20 minutes, vs 20 seconds for the S3 server side rename/copy. 

At any rate, we have dropped B2 and switched to Wasabi. Competition is good for consumers, but in this case not so much for B2.

**Comment by wesbos** [comment]
You can now do this via the Copy file API 

https://www.backblaze.com/blog/backblaze-b2-copy-file-beta-is-now-public/

**Comment by ppolewicz** [comment]
Support for large file copy (and also other nice things) is being implemented in https://github.com/Backblaze/b2-sdk-python/issues/77, some PRs are already merged but there is still some implementation and testing remaining

**Comment by asineth0** [comment]
S3 doesn't have renaming functionality either. Just copy the file & delete the old one.
