### ISSUE TITLE
LargeFileUploadState object has no attribute get_error_message

### ISSUE THREAD

**Issue by mdeboer** [Backblaze/B2_Command_Line_Tool#177]
In my backup log file I saw this line:

`b2_upload(/backup/#########.tar.gz,#########.tar.gz, 1466468375649): AttributeError("'LargeFileUploadState' object has no attribute 'get_error_message'",) 'LargeFileUploadState' object has no attribute 'get_error_message'`

No retry attempt were made and the file failed to upload.

(the ### were intentional and not the real file name)

**Comment by bwbeach** [comment]
Thanks for reporting.  I'll track this down.
