### ISSUE TITLE
Suggestion: upload speed and progress

### ISSUE THREAD

**Issue by DanielJLewis** [Backblaze/B2_Command_Line_Tool#18]
It would be a beautiful thing for B2 CLT to display the upload speed and progress, similar to what wget does.

This kind of feedback would also give assurance that something _is_ happening.

**Comment by ppolewicz** [comment]
Only for uploads or other operations as well?

**Comment by ppolewicz** [comment]
https://github.com/niltonvolpato/python-progressbar
https://github.com/rasbt/pyprind
https://github.com/tqdm/tqdm

tqdm seems to be best for this

**Comment by ppolewicz** [comment]
urllib doesn't support upload progress bar hooks, but there are [other ways](http://stackoverflow.com/questions/5925028/urllib2-post-progress-monitoring) to do it

**Comment by DanielJLewis** [comment]
I'm thinking uploads, downloads, and any other slow transactions.

**Comment by ppolewicz** [comment]
I got it working for uploads. If it is going to be used somewhere else, I need to know where to plug it in.

Progress bar has a dependency from tqdm, but if that can not be imported, then it just doesn't work (so in such case it works exactly as it did before).

**Comment by ppolewicz** [comment]
Ok, I got it working for downloads as well. See #21.
