### ISSUE TITLE
Suggestion: tag releases on GitHub

### ISSUE THREAD

**Issue by andreausu** [Backblaze/B2_Command_Line_Tool#19]
Hi!

Could you please tag new releases on GitHub? It would be useful in order to get notified when a new version is out and to have a nice release history.

Thanks!

**Comment by sentabi** [comment]
I agree, few days ago I download b2 from Github 
```
$ ./b2 version
b2 command line tool, version 0.3.9
```
few minute ago 

```
$ ./b2 version
b2 command line tool, version 0.3.9
```

I check few commit and dont see change on version number too.

**Comment by bwbeach** [comment]
Thanks for the suggestion.  I have tagged v0.3.10, and will tag future versions as they are released.

**Comment by andreausu** [comment]
@bwbeach thanks! I'm maintaining a [docker image](https://hub.docker.com/r/andreausu/backblaze-b2/) based on this repo, so this will be really useful :)
