### ISSUE TITLE
Implement move command

### ISSUE THREAD

**Issue by mdeboer** [Backblaze/B2_Command_Line_Tool#194]
It would be nice to have a move command like all other clients out there. Run a sync job then in case there are no errors, delete the local files that were uploaded. In case of an error, handle it as usual and don't delete any files (or optionally only delete the ones that were successful).

**Comment by ppolewicz** [comment]
This is trivial in bash: `b2 sync "$source" b2:target && rm -rf "$source"`. This way is also very explicit.
Do we need to implement this in the CLI?

**Comment by mdeboer** [comment]
Hmm, if you put it that way, that is indeed quite simple and the way I use it now.

Don't mind me, I haven't said a word! 🚶
