### ISSUE TITLE
Persistent 503 on sync after ECONNRESET issue

### ISSUE THREAD

**Issue by alanfranz** [Backblaze/B2_Command_Line_Tool#203]
Possibly related to #172 

Maybe it's a backend issue, but I don't know how to tell.

Context:
b2 version 0.6.2, Ubuntu 14.04 64 bit, python 2.7.6.

To make a long story short: in the early morning (CEST) of July 26th, a new automatic full backup of my system was triggered; that lead to a large upload to b2 servers (about 150GB). The invocation cmdline is

```
b2 sync --delete --compareVersions size ./ b2:amarantabackup
```

On several of those files, I experienced the ECONNRESET error, the same I reported in #172 , e.g.

```
b2_upload(/other/localbackup/duplicity-full.20160725T234504Z.vol1.difftar.gpg, duplicity-full.20160725T234504Z.vol1.difftar.gpg, 1469490392914): UnknownError() unknown error: SysCallError(104, 'ECONNRESET')
```

The backup+sync job runs every night; most of those files that had syncing issues got a strange error in the july 27th night:

```
unknown error: 400 bad_request not an active upload: 4_zfc0b363f8e92cc1559390916_f2018d4ef15f9118c_d20160726_m031937_c001_v0001001_t0011
```

then were properly uploaded at the next execution on July 28th, failing for two:

```
b2_upload(/other/localbackup/duplicity-full.20160725T234504Z.vol48.difftar.gpg, duplicity-full.20160725T234504Z.vol48.difftar.gpg, 1469494148162): ServiceError() 503 service_unavailable No uploads available in vault 0001022
 compare: 307/307 files   updated: 0/5 files   1.91 / 2.12 GB   236 MB/s
b2_upload(/other/localbackup/duplicity-full.20160725T234504Z.vol26.difftar.gpg, duplicity-full.20160725T234504Z.vol26.difftar.gpg, 1469492490690): ServiceError() 503 service_unavailable No uploads available in vault 0001022
```

Those still keep triggering that 503 error in the backend till last night. Now I tried deleting them from the web interface, where they were recognized as 0-bytes files.

I'm not sure what I could to provide more information; tell me and I will.

**Comment by ppolewicz** [comment]
In current `master` head we have a `--debugLogs` flag, which outputs full stacktraces to a log file during sync operation.
