### ISSUE TITLE
sync never finishes checking file system with 250K files

### ISSUE THREAD

**Issue by dwisehart** [Backblaze/B2_Command_Line_Tool#208]
When sync'g a drive with 250K files from the CLI on MacOS 10.11.6, the CLI will hang.  Even after letting it sit for more than 12 hours the console still says:

`compare: 257242/257471 files    updated: 0 files    0 B    0 B/s`

The program is hanging in `site-packages/b2/console_tool.py` and there is this comment just below where it is hung:

`# I haven't tracked down the root cause yet, but in Python 2.7, the futures` 
`# packages is hanging on exit sometimes, waiting for a thread to finish.` 
`# This happens when using sync to upload files.`

Is there any progress on this bug yet?

**Comment by ppolewicz** [comment]
Is this reproducible?

**Comment by dwisehart** [comment]
Yes.  It happens every day when I do a sync.

**Comment by ppolewicz** [comment]
If we'd give you a version of b2 CLI with verbose logs, would you run it in your environment and share the resulting logs?

**Comment by dwisehart** [comment]
Sure.

Daniel

**Comment by dwisehart** [comment]
It has been a few weeks.  Any updates?

**Comment by ppolewicz** [comment]
I am working on the `logging` branch, but it is not ready yet. Can you use python3 as a workaround for now?

**Comment by dwisehart** [comment]
I checked into the various Python packages I am using on Mac OS where the problem is occurring and, for now, I think I will just manually stop the backup process each morning instead of installing python3 just yet.

**Comment by ppolewicz** [comment]
You can have python2 system-wide and use python3 just for the b2 CLI. I run it like that on linux.

I hope to get to the bottom of the issue you are hitting, but first I need to ("just") add appropriate logging to a ~7 KLOC project.

**Comment by dwisehart** [comment]
That was an interesting tests, that come with a few of caveats: I had to modify the b2 startup script, I had to reinstall b2 and the problem is still there using python3.

To get python3 on my machine I decided to use pyenv, which keeps track of which version of Python you want to run based on a file it places in the local directory.  If there is no file, you run the 'global' version of Python (2.7.11 in my case).

    brew install pyenv
    pyenv install 3.5.1
    cd <directory where I run b2 from to do a sync>
    pyenv local 3.5.1

I added the required `$(pyenv init -)` to my .bash_profile, opened a new bash session and went to the correct directory.  When I started a sync, `ps -ef` showed me that the 2.7 version of Python was still being used.  The problem was the b2 startup script.

The /usr/local/bin/b2 script on my machine started with the line:

    # !/usr/local/opt/python/bin/python2.7

I changed it to this get it to work with the "current" version of Python:

    #!/usr/bin/env python

The first time I got b2 to run with python3, it complained about not having the site-packages in the 3.5.1 directory.  So I reinstalled b2 from the same directory marked for use with python3:

    pip install b2

This time b2 started fine with python3, as shown by `ps -ef`:

    501 47816 47730   0 11:25AM ttys003    1:10.27 /Users/dwisehart/.pyenv/versions/3.5.1/bin/python3.5 /Users/dwisehart/.pyenv/versions/3.5.1/bin/b2 sync /Volumes/BackupOld/ b2://DW-Backup/Vol-BackupOld/

You can see from that it is running python3.5 but you can also see that it is running a new b2 startup script that, sure enough, has the version hard-coded in the script again:

    #!/Users/dwisehart/.pyenv/versions/3.5.1/bin/python3.5

My suggestion is that you switch to using `#!/usr/bin/env python` on the systems that support that type of startup.

Unfortunately, after trying this test, `b2 sync` is stuck in exactly the same place it was before

     compare: 257287/257485 files   updated: 0 files   0 B   0 B/s

`ps -ef` verifies that python3.5 is being used and the runtime is not growing in this stuck state.

Looks like adding logging into those 7 KLOC is going to tell us something.

**Comment by ppolewicz** [comment]
This is just a guess, but do you by any chance have two named pipes, symlinks to devices etc in your sync source directory?

**Comment by dwisehart** [comment]
I have no named pipes, but find shows I did have some symlinks in 'iPhoto Library', 'Photo Library' and 'Photo Library 2'.  I removed them all and re-ran the sync with the same result: hung at the same point.
