### ISSUE TITLE
Deduplication not working?

### ISSUE THREAD

**Issue by clintinthecode** [Backblaze/B2_Command_Line_Tool#217]
We renamed some folders and the folders are having to do a full upload with the new names. I was under the impression before signing up that renaming folders was fine as a fingerprint at both ends was used to know its the same file, and just update the server.

According to the following page, if a file is renamed or moved, it should have a matching fingerprint and just be updated on the server rather than being uploaded again.

Could it be that our sync script is not using the right parameters on the CLI tool or is there a bug in the CLI?

Our content team need to rename a lot of folders, in total these folders contain about 8tb of data, which will take a good 1.5-2 weeks non stop to upload again when renamed, plus the manual job of deleting the old folders from the backblaze b2 server. 

Thank you.

Clint.

https://help.backblaze.com/hc/en-us/articles/217666638-What-Happens-If-I-Move-or-Rename-a-File-

"Our software contains a process called "deduplication" where files are digitally fingerprinted (checksummed) before they are sent to the server. When a file's fingerprint (SHA-1 checksum) matches an already backed up file, but it's renamed or moved (including drive to drive), it's simply updated at the servers, rather than re-transmitted.

You may see these files queued for back up, but once any given file is at the front of the queue, it will be checksummed, compared against the existing backup, and "deduplicate" resulting in it being updated on the server rather than re-uploading"

**Comment by ppolewicz** [comment]
This is a quote from Backblaze Backup service, and you are using Backblaze B2, which is a different product made by the same company. B2 itself doesn't care much about the type or form of data stored in it, so one could store deduplicated data on it, but B2 CLI does not have a deduplication feature. It could be added. We had no plans to do this any time soon (priorities are up for discussion though). 

If the sync scripts in question use the right flag (`--delete` I think), then removing old folders manually should not be necessary. You should also check out the `--keepDays` flag which may be handy in case someone accidentally deletes something during the renaming process.
