### ISSUE TITLE
b2 sync with "--delete" option

### ISSUE THREAD

**Issue by micfrip** [Backblaze/B2_Command_Line_Tool#218]
Hi,

I am trying to use the following command:
`b2 sync --delete "/path2mydir/" "b2://myBucket/"` but it is not working with the `--delete`option.
I get an error "AttributeError: 'NoneType' object has no attribute 'versions'".
Without the option, it works.

Many thanks for your help,

Michaël

**Comment by ppolewicz** [comment]
Which version of B2 CLI do you have?

**Comment by micfrip** [comment]
The latest I guess: b2 command line tool, version 0.6.5
