### ISSUE TITLE
Signed url with a token and expires param

### ISSUE THREAD

**Issue by benbro** [Backblaze/B2_Command_Line_Tool#22]
Does the API support creating a signed temporary url to download files?

**Comment by ppolewicz** [comment]
Currently it does not. Buckets are either allPublic or allPrivate. You can try emailing the b2 team - they are collecting requirements and implementing new functionality basing their roadmap on user feedback.

**Comment by benbro** [comment]
Thanks

**Comment by raulgrecio** [comment]
Signed url with a token and expires param on your roadmap to do this soon? Where I can see your roadmap of B2?
