### ISSUE TITLE
Add support for b2_get_download_authorization

### ISSUE THREAD

**Issue by nicolas17** [Backblaze/B2_Command_Line_Tool#223]
The new API call [b2_get_download_authorization](https://www.backblaze.com/b2/docs/b2_get_download_authorization.html) is currently not supported anywhere, not even at the `raw_api` level. I'm not sure if it's useful to have in the command line tool, but having it in the API certainly would.

**Comment by bwbeach** [comment]
It would be good to implement `b2_get_download_authorization`, and I think it would be useful in the command-line tool.

Would you like to make the code changes?  We have several helpful people on this project if you have any questions.

**Comment by bwbeach** [comment]
This functionality was merged into the master branch today.  It will be in the next release, going out next week.
