### ISSUE TITLE
Many EPIPE errors occur; files not synced

### ISSUE THREAD

**Issue by TJC** [Backblaze/B2_Command_Line_Tool#224]
Hi,
During syncs I experience many EPIPE errors -- I give one example below, but during a typical sync of 10-20 Gbytes, I'll experience many of these. At the end if I restart the sync, it finds many files that need to be re-synced, so it sounds like these errors prevent the files being uploaded completely.

`b2_upload(/filestore/homes/tjc/Pictures/2007/2007-04-07 Lake District/TJC_1068.NEF, Pictures/2007/2007-04-07 Lake District/TJC_1068.NEF, 1175962094000): UnknownError("SysCallError(32, 'EPIPE')",) Unknown error: SysCallError(32, 'EPIPE')`

I'm not sure, but it seems pretty similar to this error report in AWS pyopenssl land:  
https://github.com/boto/boto3/issues/220#issuecomment-171477361

**Comment by ppolewicz** [comment]
Please install the version from github and use the [--debugLogs](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs) flag and share the log, so that we can see the full stacktrace.

**Comment by TJC** [comment]
@ppolewicz I'm sorry, I must be an idiot, but I can't figure out how to get the CLI to accept that parameter.  
I've tried:
- b2 sync --debugLogs /tmp/example b2://example
- b2 --debugLogs sync /tmp/example b2://example

I checked and the installed Python version I'm using does parse for debugLogs in the arguments.

**Comment by ppolewicz** [comment]
it should be `b2 sync --debugLogs /tmp/example b2://example` and the log file should be `b2_cli.log` in the directory from which you launched the tool from. Did you install the current version from github?

**Comment by TJC** [comment]
Ah, I was right. I *am* an idiot. I was putting `--threads=1` and it needed to be `--threads 1`  
That's a different between the Python argument parser and the ones I normally deal with.

Upload sync started. I'll get back to you with some logs in a few hours.

**Comment by TJC** [comment]
here we go - see attached, if i have this right..
[b2_cli.log.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/479244/b2_cli.log.txt)

**Comment by ppolewicz** [comment]
we did not see anything due to Python 2 being Python 2. I filed #247 to improve logging also on Python2. After it is merged, we'll need to collect logs again.

**Comment by ppolewicz** [comment]
#247 is merged, please install current version from github, run again and share the log

**Comment by TJC** [comment]
It took a little while before I had enough data to be worth doing another big update, but.. since installing the updated version, I haven't _had_ any EPIPE errors.. just a couple of ECONNRESETs, but they're legitimate. (ADSL dropping out). The EPIPEs were more frequent.

I'll keep an eye on things and see if more pop up sometime, if you don't mind keeping this ticket open for a while longer?

**Comment by TJC** [comment]
I'm still seeing ECONNRESET errors from time to time, and I'm dubious that they're actually the ADSL going down _that frequently_ . I wonder where the EPIPE ones went though.

I'll attach some logs -- what do you think? Should these be getting retried internally?

[b2_cli.log.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/510180/b2_cli.log.txt)

**Comment by ppolewicz** [comment]
Thank you for the logs.

EPIPEs are quite random. Both should be retried automatically though.

By the way, do you think bucket names should be redacted automatically?

Also, do you have a way to monitor your ADSL?

**Comment by ppolewicz** [comment]
This issue should have been resolved upstream two years ago, but apparently they got stuck:
shazow/urllib3#367
kennethreitz/requests#2543
