### ISSUE TITLE
Handle a "Retry-After" if 429 Too Many Requests is received

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#229]
In such case **all threads** shall delay the next request

**Comment by bwbeach** [comment]
Arguing the other side of "all threads"...

I'm not sure it's worth a lot of complexity.  The B2 service would have to be able to handle the load if each of the threads were running independently on a separate client.

**Comment by ppolewicz** [comment]
I have in mind an easy way to implement that. Obviously it won't work very well if two clients run in parallel on the same account. Each of the processes could generate a random id on start and pass it to the server, so that it would be possible to make a smart server-side throttling (aware of multiple clients for the same account). That is a more advanced version though. Do you think it would be feasible for the server side? 

Not having this at all disallows the server operator from throttling clients effectively.

**Comment by ppolewicz** [comment]
This is the last item remaining in #97 to be finished

**Comment by ppolewicz** [comment]
This actually needs to support the header on any error, not just 429. b2 docs say that 503 could return it.
