### ISSUE TITLE
Feature request: InMemoryAccountInfo

### ISSUE THREAD

**Issue by sondree** [Backblaze/B2_Command_Line_Tool#252]
I plan on using B2 Command Line tool as a library to interface with B2. In order to do so I need an InMemoryAccountInfo, implementing the "AccountInfo" interface using only memory. 

Would this be possible to add?

Best
Sondre

**Comment by ppolewicz** [comment]
Sure!

**Comment by ppolewicz** [comment]
I finished the implementation and now I am refactoring tests (most will be same with `SqliteAccountInfo`)

**Comment by ppolewicz** [comment]
ok, it is now in review. Usage will be:
```python
from b2.account_info import InMemoryAccountInfo
account_info = InMemoryAccountInfo()
```
and then pass the object to `B2Api` and perform `api.authorize_account(...)` normally.
