### ISSUE TITLE
Feature request: "delete by id" in bucket

### ISSUE THREAD

**Issue by sondree** [Backblaze/B2_Command_Line_Tool#256]
Hello again,

It would be beneficial if B2Api was a simple, cheap and fast as possible (ref #250). As such I see no reason to implement "delete by file name". "Delete by id" on the other hand would be useful if was it was available as a function within the bucket (this should just be to expose the same call from the API object as a bucket function). Otherwise I have to retain both for full functionality.

Best 
Sondre

**Comment by ppolewicz** [comment]
@sondree @bwbeach I've looked at how `B2Api` handles it. It is `delete_file_version(self, file_id, file_name)`. I am going to make a PR with a simple pass-through between `Bucket` and `B2Api` in this regard, lets move the discussion there.
