### ISSUE TITLE
ERROR: 500 persistence Cannot read staves for bucket

### ISSUE THREAD

**Issue by georgiecasey** [Backblaze/B2_Command_Line_Tool#263]
i'm uploading a lot of 1gb files sequentially and getting a few 'connection reset by peer' errors which resolve when i retry. but getting a ERROR: 500 persistence Cannot read staves for bucket on all files now. is this related to the client or just network errors with backblaze?

at these storage prices, i can put up with occasional network errors but is this an error on my side?

**Comment by ppolewicz** [comment]
@bwbeach it looks like server-side unavailability of bucket structure internals for reading

**Comment by bwbeach** [comment]
The servers were having trouble this morning.  And we'll have to produce a better error message.  :-)

**Comment by georgiecasey** [comment]
ah great, so it's not my problem! this not an issue then with this code, should be closed

i spent a few minutes Googling what a 'stave' is, i still have no idea!

**Comment by bwbeach** [comment]
It's an internal data structure, and we shouldn't be exposing it in the error messages.

When we shard the database of names in a bucket, we call each part a "stave".

Closing.
