### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by git4xuan** [Backblaze/B2_Command_Line_Tool#264]
hello, recently I use pip command but failed.
The 0.6.8 b2 version needs logfury>=0.1.2 , while logfury stable version in Pypi had deleted.
I have to install logfury manually....
and travis CI use cache ,so this problem can be skipped.

**Comment by ppolewicz** [comment]
Logfury 0.1.2 is up, as it always was: https://pypi.python.org/pypi/logfury

Maybe you are using pypitest?

**Comment by ppolewicz** [comment]
I verified that in a fresh 2.7 virtualenv `b2` installs properly (with `logfury-0.1.2`).

**Comment by ilinuxadmin** [comment]
You could easily install the latest version of B2 from github:

$git clone https://github.com/Backblaze/B2_Command_Line_Tool.git
$cd B2_Command_Line_Tool/
$python setup.py build
$python setup.py install

Check your exit status to make sure that everything went well:
$echo $?

Now check your b2 version:
$b2 version
`b2 command line tool, version 0.6.9`

**Comment by git4xuan** [comment]
After I upgrade pip , It can be collect logfury correctly,recently I opened serveral VPS in different location and different biz , and  ignore to upgrade pip first . most of time old  pip  version works well~~~
Thanks for your test for me.

**Comment by ppolewicz** [comment]
Today I have probably fixed the root cause of old pip not being able to install logfury (by releasing sdist).

**Comment by git4xuan** [comment]
Now It can work even I used pip 1.1 version!
