### ISSUE TITLE
b2 sync on Windows fails on long paths

### ISSUE THREAD

**Issue by ncote** [Backblaze/B2_Command_Line_Tool#265]
Several of the following warnings appear:
`WARNING:  <long path e.g. 279 characters in one case> could not be accessed (broken symlink?)`

Then it finally fails with:

```
File "C:\Python27\lib\site-packages\b2\sync.py", line 540, in _walk_relative_paths
  for name in os.listdir(dir_path):
WindowsError: [Error 3] The system cannot find the path specified: u'<257-character-long-path>\\*.*'
```

**Comment by ppolewicz** [comment]
May be https://bugs.python.org/issue18199

**Comment by ncote** [comment]
That looks right.  Should I assume then that the issue is unfixable here until the python bugs are fixed?

**Comment by ppolewicz** [comment]
No. I am fairly certain that this can be fixed.
