### ISSUE TITLE
hyphens in bucket name gives "No such bucket", encoding issue?

### ISSUE THREAD

**Issue by henryoswald** [Backblaze/B2_Command_Line_Tool#266]
Hi,

I just signed up and created a new bucket but was unable to upload anything to my bucket, "my-bucket-important-backups", I was getting the following error:

`ERROR: No such bucket:myl\u2011bucket\u2011important\u2011backups`

The error message looked a bit like an an encoding issue so I created a new bucket with no hyphens and it works.

b2 command line tool, version 0.6.8

**Comment by ppolewicz** [comment]
Can you type the bucket name manually using the "-" button instead of pasting it? According to b2 documentation:

> Bucket names must be a minimum of 6 and a maximum of 50 characters long, and must be globally unique; two different B2 accounts cannot have buckets with the name name. Bucket names can consist of: letters, digits, and "-". Bucket names cannot start with "b2-"; these are reserved for internal Backblaze use.

From what you have reported, a bucket containing a unicode character `\u2011` (NON-BREAKING HYPHEN) is being used. Where did you get it from? Did you copy the bucket name from the b2 web interface and paste it in the command line?

**Comment by henryoswald** [comment]
Hi,

that did fix it thanks. I copied the bucket name from the web app where I created it.

**Comment by ppolewicz** [comment]
@nilayp there is a bug in b2 web app where the user creates a bucket containing hypens and when the bucket name is displayed back to the user, the hypens are replaced with `\u2011`. Some other way of preventing line-breaking in the bucket name must be used.

Please confirm that this is copied to the internal bug tracker and close this issue.

**Comment by bwbeach** [comment]
I'll follow up on this.

**Comment by bwbeach** [comment]
We're planning on getting this fixed for our weekly deployment on Thursday.

**Comment by ppolewicz** [comment]
I am closing this since this is not really a bug in the CLI
