### ISSUE TITLE
make it clear include and exclude regex need to be quoted

### ISSUE THREAD

**Issue by henryoswald** [Backblaze/B2_Command_Line_Tool#267]
Hi,

A small issue I just hit up against is the regexes for include and exclude in sync need to be quoted to work. I was trying them without quotes and slashes i.e. `/.*/ `both of which showed the help for sync but did not explain the problem.

**Comment by ppolewicz** [comment]
This is between you and your shell. It is not a b2 CLI specific issue, but rather something that you have to remember when using any tool through the shell. Nevertheless if you think the help text could be better, a PR will be welcome!
