### ISSUE TITLE
Need tests for sync command.

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#27]
There aren't any tests yet for the new sync code.

**Comment by bwbeach** [comment]
I'll be working on this today.

**Comment by ppolewicz** [comment]
Shouldn't refactoring (as per your TODO comments) come first? Or do you mean integration tests of console command?

**Comment by bwbeach** [comment]
I mean the integration tests.  I'd like to have those in place before refactoring.
