### ISSUE TITLE
Underscore in command should be avoided

### ISSUE THREAD

**Issue by szepeviktor** [Backblaze/B2_Command_Line_Tool#275]
AFAIK I've never seen underscores in commands `authorize_account`.

Please consider moving to dashes. `authorize-account`

See https://github.com/pallets/click and http://click.pocoo.org/5/why/

**Comment by ppolewicz** [comment]
That would break compatibility for all existing users of B2 CLI. Is it worth it?

**Comment by szepeviktor** [comment]
For a couple of releases you may provide both, and warn existing users.

**Comment by ppolewicz** [comment]
We could implement an 'alias' feature in our command option system, but I think it is not worth removing after we do it. So we can change the documented version and provide the new default as well as the old syntax, but we won't remove it any time soon. People have their b2 CLI run from scripts, they don't read the output, so they won't see the warning.
@bwbeach do you think the default could be changed to contain a dash?

**Comment by bwbeach** [comment]
I'm fine with changing the default.  We'll need to support underscores for a long time, and probably will never stop supporting them.

**Comment by ppolewicz** [comment]
@szepeviktor will you implement that?

**Comment by bwbeach** [comment]
I'm fine with just hard-coding a rule that always accepts "-" for "_".

**Comment by szepeviktor** [comment]
> will you implement that?

Is is one string replace in the magic function?
