### ISSUE TITLE
b2 freezes on read permission error

### ISSUE THREAD

**Issue by robertomurta** [Backblaze/B2_Command_Line_Tool#282]
When trying to sync another directory, which has some subdirectory owned by other (root in my case) without read permission, b2 prints python stacktrace then freeze (ctrl+c is enough to exit)
It should report (Warn) the permission error then continue.
Noticed that it Warns for broken symlinks (thats ok :)).

**Comment by robertomurta** [comment]
```
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 110, in _walk_relative_paths
    for name in os.listdir(dir_path):
```

**Comment by svonohr** [comment]
This seems to be the same bug as reported in #149 and should be fixed with #289.

**Comment by ppolewicz** [comment]
The resolution in #289 is vulnerable to a race condition where someone chmods or chowns a file after b2 CLI already scans it and determines that the access permissions are ok. This scenario is a bit surreal though and our implementation of sync is limited, not only in this way. Current implementation of sync can only provide basic functionality. It is not a full-featured enterprise-ready backup application.

Nevertheless, if someone ever hits the race scenario, please create a new issue.

**Comment by svonohr** [comment]
I also thought about this problem and I think it's quite likely that it will happen (thinking about it now, I'm even surprised that it didn't happen already). When the upload of a previous found file starts, the file may be already deleted/moved or whatever. Given that a sync of a large directory may take hours this could happen easily. I haven't checked the code but I think we don't handle this at the moment. There should be a log message if a previously listed file cannot be opened when the actual upload starts.

**Comment by ppolewicz** [comment]
It is difficult to handle reliably - the device from which data should have been read may become unresponsive and hang forever. Sync should then timeout when it is unable to read form a file... I can't commit much more time to sync reliability right now though. If someone would like to do that, we'll happily support the effort.

**Comment by robertomurta** [comment]
From the experience that motivated opening this, the simple solution would be to handle reading error at copying time, by showing a warning, and continuing... try...catch would solve it (I think) avoiding the entire process to stop (which is a real pain). The case of verifying a file that is modified during list uploading time is not much problem, since executing again at later time would resolve most cases.
Using both solutions, at inventory time, and at copying time are also nice.

**Comment by ppolewicz** [comment]
Right. As I said, if you want to implement a more reliable solution, please open a new issue for it so that design can be discussed.

a simple try...catch will not solve the problem reliably

If you actually encounter a problem where inventory went fine and the issue was hit during reading, please also create a new issue. Currently it is hard for me to justify significant development effort _for free_ to solve a problem nobody hits.
