### ISSUE TITLE
sync compatibility with b2sync command

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#29]
Backblaze has a sync tool written in C.  It would be nice if the sync command in Python were compatible.

I think the only issue is that the C tool has an option for encoding the modification time in the file name.  This makes scanning for updates faster because it doesn't have to call `b2_get_file_info` on each file.

**Comment by ppolewicz** [comment]
Is this tool available to the public?

**Comment by bwbeach** [comment]
https://www.backblaze.com/b2/docs/b2sync.html

**Comment by HenrikBengtsson** [comment]
Sorry for hijacking this thread, but it's there any chance for making b2sync source code available via GitHub?

I understand it's available for download as a https://www.backblaze.com/b2/docs/b2sync_src.zip

**Comment by brianwski** [comment]
Definitely plans!  I’m a little behind, I need to clean up a few things 
and then we will post it, sorry it is lagging.

-- Brian Wilson
   CTO, Backblaze
   brianw@backblaze.com
