### ISSUE TITLE
b2 upload_file ssl Certificate warning

### ISSUE THREAD

**Issue by vbs** [Backblaze/B2_Command_Line_Tool#290]
b2 upload_file warning as below. I use anaconda2 with pip install b2 as environment.
Hope to make it dispear.

> anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for api001.backblazeb2.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
>   SubjectAltNameWarning
> anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for pod-000-1003-08.backblaze.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
>   SubjectAltNameWarning

**Comment by bwbeach** [comment]
Server-side certificates were replaced a while ago for an unrelated reason.  Please open a new issue if this is still a problem.
