### ISSUE TITLE
b2 sync cannot handle chinese filenames

### ISSUE THREAD

**Issue by hinesmr** [Backblaze/B2_Command_Line_Tool#291]
I'm trying to perform a sync for the first time, and the utility has having trouble with chinese filenames. (Regular rsync can handle the filenames just fine).

Here is the python exception:

```
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 887, in run_command
return command.run(args)
File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 691, in run
max_workers=max_workers
File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
return function(*wrapee_args, **wrapee_kwargs)
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 209, in sync_folders
source_folder, dest_folder, args, now_millis, reporter
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 135, in make_folder_sync_actions
dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions, inclusions):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 81, in zip_folders
current_a = next_or_none(iter_a)
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 35, in next_or_none
return six.advance_iterator(iterator)
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 47, in _filter_folder
for f in folder.all_files(reporter):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 79, in all_files
for relative_path in self._walk_relative_paths(prefix_len, self.root, reporter):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 138, in _walk_relative_paths
for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 138, in _walk_relative_paths
for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 138, in _walk_relative_paths
for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 115, in _walk_relative_paths name = self._handle_non_unicode_file_name(name) File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 158, in _handle_non_unicode_file_name
raise EnvironmentEncodingError(repr(name), sys.getfilesystemencoding())
EnvironmentEncodingError: file name '+\xcc--\xcb\xa6' cannot be decoded with system encoding (UTF-8). We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8 ERROR: file name '+\xcc--\xcb\xa6' cannot be decoded with system encoding (UTF-8).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8
```

**Comment by ppolewicz** [comment]
Try UTF-16

**Comment by hinesmr** [comment]
Pardon? Is there a particular python patch that I'm supposed to try?

This should work with a local of UTF-8. If rsync works, why wouldn't b2 sync work?

**Comment by bwbeach** [comment]
Python things that the encoding used in your file system is UTF-8.  That's what sys.getfilesystemencoding() is returning.  But the byte sequence '+\xcc--\xcb\xa6', which appears to be one of the files on disk, is not valid UTF-8.  A byte with a high four bits of C (\xcc) is the start of a two-byte character that should be terminated with a byte in the range \x80 - \xbf.

Do you know what encoding your file system is using?  Could it be that some of the file names are encoded differently?

**Comment by hinesmr** [comment]
@bwbeach These files in particular were replicated from a Windows desktop cluster to the Linux server. We were then planning to use backblaze to offsite-backup the Linux server.

It's not possible to "fix" the files produced by the Windows cluster --- they were encoded that way by whatever windows software the various users were using during their daily work.

Is there no other way to fix this in python?

**Comment by ppolewicz** [comment]
Execute this before calling b2 sync:
```
export LANG=en_US.UTF-16
```

**Comment by hinesmr** [comment]
@ppolewicz The UTF-16 export gives me this error:

```
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 158, in _handle_non_unicode_file_name
    raise EnvironmentEncodingError(repr(name), sys.getfilesystemencoding())
EnvironmentEncodingError: file name '\xe4\xba\x8e\xe4\xb8\xb9' cannot be decoded with system encoding (ANSI_X3.4-1968).

```

**Comment by svonohr** [comment]
It seems that now you've encountered a file that is actually encoded using UTF8 (it decodes to 于丹, which looks like Chinese characters to me).
Somehow you got inconsistent filename encodings. I guess you have used some sort of network service to replicate the files from the Windows machine to your Linux server? You should make sure that this process properly converts the encoding of the filenames to the expected target encoding (usually UTF8). Windows uses UTF16 on its filesystem so there is probably a conversion missing somewhere. What software did you use for the replication?

**Comment by hinesmr** [comment]
@svonohr That's correct, we use the built-in Windows back service to replicate to a Samba share. In this particular case it involves a user with Chinese filenames. At no point in the process did we explicitly choose a specific encoding configuration.

I'll look into what's going on with the encoding when I have a spare minute to do so.

**Comment by bwbeach** [comment]
No action for a while.  

I'm going to close, and claim that `b2 sync` is doing the right thing by expecting consistent file name encoding.  Otherwise, it doesn't know how to translate the names to the UTF-8 required by the B2 service.

**Comment by hinesmr** [comment]
Honestly, guys, these filenames are generated by Windows, not by a human hand-picking an encoding. It's a little dissapointing that there aren't any test cases to cover the product for handling filenames from WIndows => Linux => Backblaze.

I'd love to be a regular customer, but I'm expecting it to "just work", rather than go and debug a toolset.
