### ISSUE TITLE
support for bucket info and lifecycle rules

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#294]
The B2 service now supports storing bucket info with a bucket, and will soon support setting lifecycle rules to automatically delete old versions of files.

Any thoughts on what the interface to the command-line tool should be?

The obvious thing to do is to add `--bucket-info` and `--lifecycle-rules` options to the `create_bucket` and `update_bucket` operations.  Each would take JSON as an argument, like this:

```
b2 update-bucket --bucket-info '{"color": "blue"}' my-bucket
```

That seems reasonable, but may be inconvenient for storing large bucket info or a long list of lifecycle rules.  We could support pulling from a file, perhaps by using the curl convention of "@" to indicate a file.  (That will be unambiguous because JSON can't start with "@".)

```
b2 update-bucket --lifecycle-rules @rules.json my-bucket
```

Does this sound reasonable?

**Comment by ppolewicz** [comment]
There are many more important issues than the "@" syntax, which has a trivial workaround: `--lifecycle-rules "$(<rules.json)` (unless one uses Windows, which is not supported officially yet). So I'd skip it for now. Apart from that it seems ok. I'd like to see an example json though.

**Comment by bwbeach** [comment]
I used to worry about Windows users, without real shell syntax.  But maybe that's not a problem any more, now that Windows 10 has a real shell.  I'll get rid of the "@".  It's messy.
