### ISSUE TITLE
Set `src_last_modified_millis` in `b2 upload_file`

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#296]
When you use `sync` to upload files, it always sets `src_last_modified_millis`.  But uploading single files doesn't, which can cause later syncs to get confused.

I propose that `src_last_modified_millis` be set for every uploaded file.  If the user doesn't specify a value on the command line, we can take it from the file.

It would be good to check and make sure that the local clock isn't too different from the server's clock before uploading anything.

**Comment by svonohr** [comment]
I agree with you. It doesn't hurt to set `src_last_modified_millis` for every file upload. Checking the difference between local and server time also seems useful, but this is a separate issue that should also apply to sync.

**Comment by ppolewicz** [comment]
I approve
