### ISSUE TITLE
Upload to backblaze very slow

### ISSUE THREAD

**Issue by khavishbhundoo** [Backblaze/B2_Command_Line_Tool#299]
I have the following in my php script

`$time_start = microtime(true);`
`$upload_info = shell_exec($upload_command);`
`echo 'Total execution time(upload only) in seconds: ' . (microtime(true) - $time_start);`

Here is an example of a full command

`B2_ACCOUNT_INFO=/path/to/.b2_account_info b2 upload_file --sha1 63eec5e7c78984492b958a399e5dc7e786226153 --contentType 'image/jpg' imgsv1 '/var/www/mysite.com/public_html/www/tmp/0000000090' 'WZ4zg3Z1.jpg'`

`Total execution time(upload only) in seconds: 1.5932109355927`

How come it takes 1.59 sec to upload a 270KB  image 

I am using python 2.7.5 with PHP 7.1.0

**Comment by khavishbhundoo** [comment]
Here is what i got when i  ran the command on my server directly via commandline 
`real    0m1.616s
user    0m0.165s
sys     0m0.046s`

**Comment by ppolewicz** [comment]
This is not a B2 CLI issue. B2 API just has high latency.

**Comment by khavishbhundoo** [comment]
is there anything that can be done to make it faster

**Comment by ppolewicz** [comment]
It depends. Could please you describe your entire use case?

**Comment by bwbeach** [comment]
There is latency inherent in the system.  B2 does not return "success" until the file has been written durably.  The file will be there even if the power fails at the data center right after returning the response.  This means writing 20 shards to 20 busy disk drives, collecting the answers, confirming checksums, etc.

B2 is designed for high throughput.  If you need to get a lot of data into B2 fast, you can upload many files in parallel.

**Comment by khavishbhundoo** [comment]
My web application is an image hosting service so i need to be able to upload images  fast so that it is available to the user asap

**Comment by ppolewicz** [comment]
You should probably have cache in your service anyway, to reduce the price of running it, as downloading from b2 directly to the user is not cost effective for the frequently viewed images (research shows that a small percentage of the images are viewed a lot, especially soon after they are uploaded, while the rest of them is almost never viewed).

Write the file to the cache (as you need it in the cache initially anyway) and return success to the user, then upload (or `sync`) them to b2 for long term storage.

**Comment by khavishbhundoo** [comment]
I already use cloudflare to serve the images to users so that it not an issue.Currently time taken to upload the image to b2 in the first place is very long.My application is done with processing in < 500 ms and it takes 1.5+ to upload the file

**Comment by ppolewicz** [comment]
If you want very low latency with small files, b2 might not be the best solution for you.

**Comment by bwbeach** [comment]
Closing.  This is an issue with the B2 service, not with the command-line tool.
