### ISSUE TITLE
Detect when local clock differs from B2 clock

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#301]
It would be nice if the command-line tool detected when the clock in the B2 service is too far off from the local clock.  This matters when setting `src_last_modified_millis` in a file upload.  

What should happen when the clocks don't match?  Is printing a warning enough?  Should sync stop?

**Comment by ppolewicz** [comment]
I think it should crash as soon as desynch is noticed, unless a special flag (like `--ignore-time-skew`) is passed.

**Comment by bwbeach** [comment]
It would be easy to add the current time to the response from `b2_get_upload_url`.  That would let us detect the problem before uploading a file, and report an error before anything is changed in B2.

For large files, I think that `b2_start_large_file` is the best place to check.  If the clock is off, it can cancel the large file and then report an error.

**Comment by bwbeach** [comment]
OTOH, it would be better to avoid calling `b2_start_large_file` at all if the clocks are off.  How about calling `b2_get_upload_url` before starting a large file (if it hasn't been called already) to check the clock?  It's one more server round trip, but it's a large file and it's going to take time anyway.

**Comment by ppolewicz** [comment]
Maybe we could make it more generic? We could give the API user ability to attach a post-request trigger function, which would, in this case, validate the time and raise an exception if the time is skewed (at any point).

**Comment by bwbeach** [comment]
That would work.  Are there any other calls where we care about clock skew?

**Comment by ppolewicz** [comment]
I think all requests are timestamped server-side, so if we install a trigger like this, we can detect the skew during all kinds of requests. This could also give a potential benefit of accounting (B2 cli API level user could count the requests as they deplete his daily limit).

**Comment by bwbeach** [comment]
Good point.  Response headers include the current date:

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Content-Length: 280
Date: Fri, 16 Dec 2016 20:17:49 GMT
```

**Comment by ppolewicz** [comment]
I was thinking about something similar to our reporter pattern:
```python
class MyCallback(AbstractRequestCallback):
    def pre_request(self, request):
        return super(MyCallback, self).pre_request(request)
    def post_request(self, request, response):
        super(MyCallback, self).post_request(request, response)

b2api = B2Api()

cb = MyCallback()
b2api.add_request_callback(cb)
```
the main difference is that one can attach many callback objects and the pre_request thing can return False, aborting the request before it is actually sent. Does that make any sense?

**Comment by bwbeach** [comment]
Sounds like a good plan.

**Comment by bwbeach** [comment]
I think it might be better for the callback to raise an exception if it doesn't want the request to be processed.  That way it can include information about why the request wasn't processed.

**Comment by ppolewicz** [comment]
Good idea, but lets document it in `AbstractRequestCallback` that the exception should inherit from our class, so that it can be caught accurately.

**Comment by bwbeach** [comment]
The requests library doesn't have a Request object.  I propose that instead of passing in a request object, the pre_request method take: `(method, url, headers)`.  We can't include the data when posting file uploads.

**Comment by ppolewicz** [comment]
We could wrap those three into a `namedtuple`, but I noticed `requests` actually has a `Request` class, as well as `PreparedRequest`, which I think we should use:
http://docs.python-requests.org/en/master/api/#lower-level-classes

A `Response` object has a `.request` member, which is a `PreparedRequest` instance, so they can be easily matched with each other to indicate completion.
