### ISSUE TITLE
Detect invalid dependencies in the environment automatically on UnknownError

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#314]
https://github.com/pypa/pip/pull/3750 describes `pip check`, available since pip 9.0.0, which can help diagnose issues such as #313.

Modify the way in which the `UnknownError` is constructed. If current version of pip allows it, run the diagnostic and output information to the user. If pip is too old, inform the user that he can upgrade it and use `pip check` to diagnose his environment to hopefully find what is causing the problem.

**Comment by mjurbanski-reef** [comment]
We will provide an Issue template instead.
