### ISSUE TITLE
Upload Issues 

### ISSUE THREAD

**Issue by cofeVP** [Backblaze/B2_Command_Line_Tool#317]
(Backblaze support have asked me to post this up here.)

I've been having problems uploading to B2, using both Cyberduck (5.2.2) and the command line interface on OSX 10.8.5. With larger files (4GB+) I'm getting error messages, usually about 'broken pipes'. I'm on fibre with an upload speed averaging about 1.7MB. 

The error text on the most recent command line attempt is:

/Users/VG/Desktop/BACKUP/Walking/Day-Walks-in-the-Lake-District-Stephen-Goodwin.zip: 28%|▎| 1.87G/6.73G [23:19<1:00:23, 1.34MB/s]
ERROR: unknown host

I've given up on Cyberduck. 

The upload command I used is:

b2 upload-file --sha1 --contentType \
--info 7d642e0eb266=accountID walking /Users/VG/Desktop/BACKUP/Walking/Day-Walks-in-the-Lake-District-Stephen-Goodwin.zip Day-Walks-in-the-Lake-District-Stephen-Goodwin.zip

Also, I have almost 1TB to upload in chunks varying from 1GB to 10GB plus – is the command line the best method or could you recommend an alternative? The files are uncompressed ZIPs.

(NB. I am a command line novice.)

Any help appreciated, thanks.

**Comment by bwbeach** [comment]
We can't help you with Cyberduck here, but can probably help with the command-line tool.

Uploading files from the command-line tool is expected to be reliable.  In the cases where there are problems, there is a hidden option `--debugLogs` that will create a log file that might be helpful to us.  Could you try again and post the logs?

For uploading a lot of files, the sync command can be useful.  To upload everything in the current directory on your local disk to the walking bucket:

```
b2 sync . b2://walking
```

**Comment by cofeVP** [comment]
Thanks for the help, much appreciated. Should I drop in the debug text anywhere in particular in the command?

**Comment by ppolewicz** [comment]
Just after `upload-file` or `sync` will be good.

**Comment by cofeVP** [comment]
Thanks again. I dropped the debug in, but I haven't been given any log info on the most recent failure?

**Comment by ppolewicz** [comment]
Log is in `b2_cli.log` file in the directory where the tool was started from.

**Comment by cofeVP** [comment]
[b2_cli.log.zip](https://github.com/Backblaze/B2_Command_Line_Tool/files/739183/b2_cli.log.zip)

Thanks again, I've attached a zip of the log file. I've had some success uploading files since opening this issue, but it is still a little hit and miss.

**Comment by mjurbanski-reef** [comment]
Closing as stale; please reopen if errors still occur with the current version.
