### ISSUE TITLE
b2 sync does not preserve modification dates in docker environment

### ISSUE THREAD

**Issue by vkonnyu-sensity** [Backblaze/B2_Command_Line_Tool#318]
It seems downloading from b2 (b2 sync to local) creates files with current timestamp on a Linux Ubuntu machine (docker image ubuntu 16.04). In turn, specifying `--replaceNewer` to keep the remote and local copies in sync as suggested by the b2 cli, keeps files re-syncing again and again. `--skipNewer` is a rough workaround because it leaves local modifications in place, `--compareVersions sha1` is not yet added afaik and `--compareVersion size` is still a bit off.

**Comment by ppolewicz** [comment]
We do have code for this, see [here](https://github.com/Backblaze/B2_Command_Line_Tool/blob/c033f95d95b6b69c6842db66be3db6d42a46c1b0/b2/download_dest.py#L81). Moreover, other users do not report this issue. It suggest a problem with the environment.

There is no unit test coverage for the line in question.

**Comment by bwbeach** [comment]
Fix for #367 fixed this.
