### ISSUE TITLE
B2 Upload Issue

### ISSUE THREAD

**Issue by dsjr2006** [Backblaze/B2_Command_Line_Tool#319]
I'm working on an application in Go that uploads files to the B2 service. I'm getting an "Internal Error"-500 response when attempting to do an upload. I am able to modify the code so that this does not occur, but it isn't ideal. I’m already re-attempting upload upon receiving a 500 response; however, this error remains despite the retries. I created a simple test API server in Go and was able to receive the same request/file with no issues. 

I'm wondering if you're able to provide me some insight as to why these requests are getting an error response.

**Comment by ppolewicz** [comment]
Can you provide the full error message? Usually there is some information in the headers or http content.

**Comment by dsjr2006** [comment]
```
Server: [Apache-Coyote/1.1]
Cache-Control: [max-age=0, no-cache, no-store]
Content-Type: [application/json;charset=UTF-8]
Content-Length: [78]
Date: [Fri, 27 Jan 2017 18:47:04 GMT]
{
  "code": "internal_error",
  "message": "internal error",
  "status": 500
}
```

**Comment by ppolewicz** [comment]
This is a server-side error. Malfunctioning storage pod or something like that. Most likely it is a temporary issue, which is being resolved by Backblaze staff as we speak. They do monitor for this sort of issues and get real-time data of that... However please contact b2contact@backblaze.com to get an update on when they finish dealing with this, so that you can continue your development in peace.

I am closing github issue this because this is a b2 CLI issue tracker and this one here is not really a b2 CLI issue.

**Comment by dsjr2006** [comment]
I've been having the issue for over a week. I emailed b2contact@backblaze.com and got the same person I was already talking to that directed me here.

**Comment by ppolewicz** [comment]
Please make sure they understand that you are not using b2 CLI tool, but you are accessing the b2 API directly through a client which you have implemented in Golang.

**Comment by dsjr2006** [comment]
> anthony, Jan 27, 09:41 PST:
> Hello,
> 
> Ah, I see. I would still like for you to create an issue on our github. Our developers answer questions there and will be able to help look into that further still.
> 
> Regards,
> -Anthony
> 
> https://www.backblaze.com/blog/anthony-technical-support-technician/
> The Backblaze Team
> 
> 
> Dwin, Jan 26, 10:34 PST:
> I think you might be misunderstanding what I'm saying. I'm not using the B2 CLI. I'm attempting to use an application I'm working on. Certain configurations are not working, but some are and I'm trying to find out why. The Error 500 is not descriptive enough for me to troubleshoot.

**Comment by nilayp** [comment]
Darwin,

Sorry that you were pointed to the GitHub forum; our mistake. Pawel is correct - this should be resolved by Backblaze support. I'll answer your request there.
