### ISSUE TITLE
ERROR: Connection error: Max retries exceeded with url

### ISSUE THREAD

**Issue by clintinthecode** [Backblaze/B2_Command_Line_Tool#330]
Hi, I am very frequently getting this error, maybe 20 times a day. I have a bash script to execute the sync via cli, i frequently get emails from cron with this error:

I have tried to contact BackBlaze support but they weren't very helpful and just said to report the issue here. 
```
ERROR: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v1/b2_list_file_versions (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x807ae3cd0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

**Comment by ppolewicz** [comment]
It would seem that there is no internet between your computer and Backblaze datacenter.

Is your internet connection stable?

**Comment by clintinthecode** [comment]
Very solid, it's a 100/100mb up/down business grade fibre connection.

**Comment by ppolewicz** [comment]
Are you from Australia?

Can you run additional diagnostic during a failing run? As you see logs don't show us what happens, additional measures are needed to find it out.

**Comment by clintinthecode** [comment]
Yes, the server is in Sydney. 

What kind of additional diagnostic do you want me to run? What can I do to do that?

**Comment by bwbeach** [comment]
At Backblaze, one of the monitoring systems we have tries all of the API calls once a minute.  It will rarely see this timeout error when trying to contact `api001.backblazeb2.com`.  It hasn't seen the error for the past 5 days.

We have seen errors like this with unreliable network connections from clients.  If the connection is losing packets, it can easily lead to timeouts.

An initial test to run would be to run `ping api001.backblazeb2.com` for a while, and see if there are any delays or lost packets.

**Comment by clintinthecode** [comment]
Ok just had it fail again, this time I was doing two ping tests while it failed. Ive pasted below the last 2 minutes of pings to both Backblaze and to google.com, this is approximately 1 minute of pings before the api error, and one minute after the api error.

During this time the ping to Backblaze is pretty solid considering thats over international connections, max deviation I can see is about 1.5ms, majority of the time its sits within a 0.4ms window which I consider pretty consistent. There was however during this period an inconsistent ping to google, most around 1.8ms, one ping came in at 35ms.

Over 40 minutes of pings, 3 packets out of 2409 were lost to Backblaze, oddly though when I scroll through the list of every single ping, I cant see any lost packets, I did find this though where the pings got a bit higher in this one spot, the rest of the 40 minutes was consistently around 162ms. 

64 bytes from 162.244.62.198: icmp_seq=1935 ttl=52 time=162.752 ms
64 bytes from 162.244.62.198: icmp_seq=1936 ttl=52 time=162.772 ms
64 bytes from 162.244.62.198: icmp_seq=1937 ttl=52 time=162.742 ms
64 bytes from 162.244.62.198: icmp_seq=1938 ttl=52 time=162.718 ms
64 bytes from 162.244.62.198: icmp_seq=1939 ttl=52 time=162.798 ms
64 bytes from 162.244.62.198: icmp_seq=1940 ttl=52 time=162.791 ms
64 bytes from 162.244.62.198: icmp_seq=1941 ttl=52 time=162.747 ms
64 bytes from 162.244.62.198: icmp_seq=1942 ttl=52 time=162.600 ms
64 bytes from 162.244.62.198: icmp_seq=1943 ttl=52 time=162.582 ms
64 bytes from 162.244.62.198: icmp_seq=1944 ttl=52 time=194.637 ms
64 bytes from 162.244.62.198: icmp_seq=1945 ttl=52 time=183.739 ms
64 bytes from 162.244.62.198: icmp_seq=1946 ttl=52 time=162.601 ms
64 bytes from 162.244.62.198: icmp_seq=1947 ttl=52 time=178.353 ms
64 bytes from 162.244.62.198: icmp_seq=1948 ttl=52 time=162.793 ms
64 bytes from 162.244.62.198: icmp_seq=1949 ttl=52 time=192.079 ms
64 bytes from 162.244.62.198: icmp_seq=1950 ttl=52 time=166.033 ms
64 bytes from 162.244.62.198: icmp_seq=1951 ttl=52 time=170.139 ms
64 bytes from 162.244.62.198: icmp_seq=1952 ttl=52 time=169.485 ms
64 bytes from 162.244.62.198: icmp_seq=1953 ttl=52 time=162.622 ms
64 bytes from 162.244.62.198: icmp_seq=1954 ttl=52 time=162.695 ms
64 bytes from 162.244.62.198: icmp_seq=1955 ttl=52 time=165.592 ms
64 bytes from 162.244.62.198: icmp_seq=1956 ttl=52 time=174.962 ms
64 bytes from 162.244.62.198: icmp_seq=1957 ttl=52 time=162.618 ms
64 bytes from 162.244.62.198: icmp_seq=1958 ttl=52 time=184.283 ms
64 bytes from 162.244.62.198: icmp_seq=1959 ttl=52 time=168.200 ms
64 bytes from 162.244.62.198: icmp_seq=1960 ttl=52 time=162.720 ms
64 bytes from 162.244.62.198: icmp_seq=1961 ttl=52 time=163.328 ms
64 bytes from 162.244.62.198: icmp_seq=1962 ttl=52 time=162.594 ms
64 bytes from 162.244.62.198: icmp_seq=1963 ttl=52 time=162.766 ms
64 bytes from 162.244.62.198: icmp_seq=1964 ttl=52 time=162.545 ms
64 bytes from 162.244.62.198: icmp_seq=1965 ttl=52 time=162.627 ms 

ERROR: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v1/b2_list_file_versions (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x807ae3cd0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

--- api001.backblazeb2.com ping statistics ---
2409 packets transmitted, 2406 packets received, 0.1% packet loss
round-trip min/avg/max/stddev = 161.974/163.166/199.204/2.769 ms

64 bytes from 162.244.62.198: icmp_seq=2281 ttl=52 time=163.760 ms
64 bytes from 162.244.62.198: icmp_seq=2282 ttl=52 time=162.605 ms
64 bytes from 162.244.62.198: icmp_seq=2283 ttl=52 time=162.741 ms
64 bytes from 162.244.62.198: icmp_seq=2284 ttl=52 time=162.622 ms
64 bytes from 162.244.62.198: icmp_seq=2285 ttl=52 time=162.617 ms
64 bytes from 162.244.62.198: icmp_seq=2286 ttl=52 time=162.670 ms
64 bytes from 162.244.62.198: icmp_seq=2287 ttl=52 time=163.026 ms
64 bytes from 162.244.62.198: icmp_seq=2288 ttl=52 time=162.633 ms
64 bytes from 162.244.62.198: icmp_seq=2289 ttl=52 time=162.653 ms
64 bytes from 162.244.62.198: icmp_seq=2290 ttl=52 time=162.712 ms
64 bytes from 162.244.62.198: icmp_seq=2291 ttl=52 time=162.649 ms
64 bytes from 162.244.62.198: icmp_seq=2292 ttl=52 time=162.672 ms
64 bytes from 162.244.62.198: icmp_seq=2293 ttl=52 time=162.669 ms
64 bytes from 162.244.62.198: icmp_seq=2294 ttl=52 time=162.665 ms
64 bytes from 162.244.62.198: icmp_seq=2295 ttl=52 time=162.660 ms
64 bytes from 162.244.62.198: icmp_seq=2296 ttl=52 time=162.619 ms
64 bytes from 162.244.62.198: icmp_seq=2297 ttl=52 time=162.740 ms
64 bytes from 162.244.62.198: icmp_seq=2298 ttl=52 time=162.642 ms
64 bytes from 162.244.62.198: icmp_seq=2299 ttl=52 time=162.822 ms
64 bytes from 162.244.62.198: icmp_seq=2300 ttl=52 time=162.664 ms
64 bytes from 162.244.62.198: icmp_seq=2301 ttl=52 time=162.615 ms
64 bytes from 162.244.62.198: icmp_seq=2302 ttl=52 time=162.625 ms
64 bytes from 162.244.62.198: icmp_seq=2303 ttl=52 time=162.735 ms
64 bytes from 162.244.62.198: icmp_seq=2304 ttl=52 time=162.607 ms
64 bytes from 162.244.62.198: icmp_seq=2305 ttl=52 time=162.694 ms
64 bytes from 162.244.62.198: icmp_seq=2306 ttl=52 time=162.629 ms
64 bytes from 162.244.62.198: icmp_seq=2307 ttl=52 time=162.707 ms
64 bytes from 162.244.62.198: icmp_seq=2308 ttl=52 time=162.795 ms
64 bytes from 162.244.62.198: icmp_seq=2309 ttl=52 time=162.792 ms
64 bytes from 162.244.62.198: icmp_seq=2310 ttl=52 time=162.660 ms
64 bytes from 162.244.62.198: icmp_seq=2311 ttl=52 time=162.638 ms
64 bytes from 162.244.62.198: icmp_seq=2312 ttl=52 time=162.689 ms
64 bytes from 162.244.62.198: icmp_seq=2313 ttl=52 time=162.662 ms
64 bytes from 162.244.62.198: icmp_seq=2314 ttl=52 time=162.682 ms
64 bytes from 162.244.62.198: icmp_seq=2315 ttl=52 time=162.648 ms
64 bytes from 162.244.62.198: icmp_seq=2316 ttl=52 time=162.682 ms
64 bytes from 162.244.62.198: icmp_seq=2317 ttl=52 time=162.834 ms
64 bytes from 162.244.62.198: icmp_seq=2318 ttl=52 time=162.755 ms
64 bytes from 162.244.62.198: icmp_seq=2319 ttl=52 time=162.735 ms
64 bytes from 162.244.62.198: icmp_seq=2320 ttl=52 time=162.669 ms
64 bytes from 162.244.62.198: icmp_seq=2321 ttl=52 time=162.708 ms
64 bytes from 162.244.62.198: icmp_seq=2322 ttl=52 time=162.773 ms
64 bytes from 162.244.62.198: icmp_seq=2323 ttl=52 time=163.618 ms
64 bytes from 162.244.62.198: icmp_seq=2324 ttl=52 time=162.635 ms
64 bytes from 162.244.62.198: icmp_seq=2325 ttl=52 time=162.639 ms
64 bytes from 162.244.62.198: icmp_seq=2326 ttl=52 time=162.617 ms
64 bytes from 162.244.62.198: icmp_seq=2327 ttl=52 time=162.638 ms
64 bytes from 162.244.62.198: icmp_seq=2328 ttl=52 time=162.982 ms
64 bytes from 162.244.62.198: icmp_seq=2329 ttl=52 time=162.678 ms
64 bytes from 162.244.62.198: icmp_seq=2330 ttl=52 time=162.690 ms
64 bytes from 162.244.62.198: icmp_seq=2331 ttl=52 time=162.623 ms
64 bytes from 162.244.62.198: icmp_seq=2332 ttl=52 time=162.796 ms
64 bytes from 162.244.62.198: icmp_seq=2333 ttl=52 time=162.748 ms
64 bytes from 162.244.62.198: icmp_seq=2334 ttl=52 time=162.789 ms
64 bytes from 162.244.62.198: icmp_seq=2335 ttl=52 time=162.702 ms
64 bytes from 162.244.62.198: icmp_seq=2336 ttl=52 time=162.615 ms
64 bytes from 162.244.62.198: icmp_seq=2337 ttl=52 time=162.632 ms
64 bytes from 162.244.62.198: icmp_seq=2338 ttl=52 time=162.687 ms
64 bytes from 162.244.62.198: icmp_seq=2339 ttl=52 time=162.636 ms
64 bytes from 162.244.62.198: icmp_seq=2340 ttl=52 time=162.784 ms
64 bytes from 162.244.62.198: icmp_seq=2341 ttl=52 time=163.462 ms
64 bytes from 162.244.62.198: icmp_seq=2342 ttl=52 time=162.614 ms
64 bytes from 162.244.62.198: icmp_seq=2343 ttl=52 time=162.787 ms
64 bytes from 162.244.62.198: icmp_seq=2344 ttl=52 time=162.943 ms
64 bytes from 162.244.62.198: icmp_seq=2345 ttl=52 time=162.604 ms
64 bytes from 162.244.62.198: icmp_seq=2346 ttl=52 time=163.350 ms
64 bytes from 162.244.62.198: icmp_seq=2347 ttl=52 time=162.637 ms
64 bytes from 162.244.62.198: icmp_seq=2348 ttl=52 time=162.798 ms
64 bytes from 162.244.62.198: icmp_seq=2349 ttl=52 time=162.965 ms
64 bytes from 162.244.62.198: icmp_seq=2350 ttl=52 time=162.619 ms
64 bytes from 162.244.62.198: icmp_seq=2351 ttl=52 time=162.630 ms
64 bytes from 162.244.62.198: icmp_seq=2352 ttl=52 time=163.291 ms
64 bytes from 162.244.62.198: icmp_seq=2353 ttl=52 time=162.820 ms
64 bytes from 162.244.62.198: icmp_seq=2354 ttl=52 time=162.617 ms
64 bytes from 162.244.62.198: icmp_seq=2355 ttl=52 time=162.633 ms
64 bytes from 162.244.62.198: icmp_seq=2356 ttl=52 time=162.599 ms
64 bytes from 162.244.62.198: icmp_seq=2357 ttl=52 time=162.769 ms
64 bytes from 162.244.62.198: icmp_seq=2358 ttl=52 time=162.638 ms
64 bytes from 162.244.62.198: icmp_seq=2359 ttl=52 time=162.644 ms
64 bytes from 162.244.62.198: icmp_seq=2360 ttl=52 time=162.674 ms
64 bytes from 162.244.62.198: icmp_seq=2361 ttl=52 time=162.740 ms
64 bytes from 162.244.62.198: icmp_seq=2362 ttl=52 time=164.120 ms
64 bytes from 162.244.62.198: icmp_seq=2363 ttl=52 time=162.627 ms
64 bytes from 162.244.62.198: icmp_seq=2364 ttl=52 time=162.716 ms
64 bytes from 162.244.62.198: icmp_seq=2365 ttl=52 time=162.753 ms
64 bytes from 162.244.62.198: icmp_seq=2366 ttl=52 time=162.613 ms
64 bytes from 162.244.62.198: icmp_seq=2367 ttl=52 time=163.046 ms
64 bytes from 162.244.62.198: icmp_seq=2368 ttl=52 time=163.031 ms
64 bytes from 162.244.62.198: icmp_seq=2369 ttl=52 time=162.664 ms
64 bytes from 162.244.62.198: icmp_seq=2370 ttl=52 time=162.663 ms
64 bytes from 162.244.62.198: icmp_seq=2371 ttl=52 time=162.734 ms
64 bytes from 162.244.62.198: icmp_seq=2372 ttl=52 time=162.740 ms
64 bytes from 162.244.62.198: icmp_seq=2373 ttl=52 time=162.698 ms
64 bytes from 162.244.62.198: icmp_seq=2374 ttl=52 time=162.668 ms
64 bytes from 162.244.62.198: icmp_seq=2375 ttl=52 time=162.834 ms
64 bytes from 162.244.62.198: icmp_seq=2376 ttl=52 time=162.635 ms
64 bytes from 162.244.62.198: icmp_seq=2377 ttl=52 time=162.641 ms
64 bytes from 162.244.62.198: icmp_seq=2378 ttl=52 time=162.787 ms
64 bytes from 162.244.62.198: icmp_seq=2379 ttl=52 time=162.742 ms
64 bytes from 162.244.62.198: icmp_seq=2380 ttl=52 time=162.653 ms
64 bytes from 162.244.62.198: icmp_seq=2381 ttl=52 time=162.624 ms
64 bytes from 162.244.62.198: icmp_seq=2382 ttl=52 time=162.616 ms
64 bytes from 162.244.62.198: icmp_seq=2383 ttl=52 time=163.020 ms
64 bytes from 162.244.62.198: icmp_seq=2384 ttl=52 time=162.557 ms
64 bytes from 162.244.62.198: icmp_seq=2385 ttl=52 time=162.789 ms
64 bytes from 162.244.62.198: icmp_seq=2386 ttl=52 time=162.576 ms
64 bytes from 162.244.62.198: icmp_seq=2387 ttl=52 time=162.641 ms
64 bytes from 162.244.62.198: icmp_seq=2388 ttl=52 time=162.876 ms
64 bytes from 162.244.62.198: icmp_seq=2389 ttl=52 time=164.394 ms
64 bytes from 162.244.62.198: icmp_seq=2390 ttl=52 time=162.680 ms
64 bytes from 162.244.62.198: icmp_seq=2391 ttl=52 time=162.510 ms
64 bytes from 162.244.62.198: icmp_seq=2392 ttl=52 time=162.655 ms
64 bytes from 162.244.62.198: icmp_seq=2393 ttl=52 time=162.552 ms
64 bytes from 162.244.62.198: icmp_seq=2394 ttl=52 time=162.572 ms
64 bytes from 162.244.62.198: icmp_seq=2395 ttl=52 time=162.873 ms
64 bytes from 162.244.62.198: icmp_seq=2396 ttl=52 time=162.622 ms
64 bytes from 162.244.62.198: icmp_seq=2397 ttl=52 time=162.682 ms
64 bytes from 162.244.62.198: icmp_seq=2398 ttl=52 time=162.883 ms
64 bytes from 162.244.62.198: icmp_seq=2399 ttl=52 time=162.677 ms
64 bytes from 162.244.62.198: icmp_seq=2400 ttl=52 time=162.578 ms
64 bytes from 162.244.62.198: icmp_seq=2401 ttl=52 time=164.459 ms
64 bytes from 162.244.62.198: icmp_seq=2402 ttl=52 time=162.800 ms
64 bytes from 162.244.62.198: icmp_seq=2403 ttl=52 time=164.283 ms
64 bytes from 162.244.62.198: icmp_seq=2404 ttl=52 time=163.244 ms
64 bytes from 162.244.62.198: icmp_seq=2405 ttl=52 time=162.701 ms
64 bytes from 162.244.62.198: icmp_seq=2406 ttl=52 time=162.775 ms
64 bytes from 162.244.62.198: icmp_seq=2407 ttl=52 time=162.673 ms
64 bytes from 162.244.62.198: icmp_seq=2408 ttl=52 time=164.092 ms




--- google.com ping statistics ---
2339 packets transmitted, 2339 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.709/2.368/35.675/2.821 ms

64 bytes from 172.217.25.174: icmp_seq=2211 ttl=58 time=1.874 ms
64 bytes from 172.217.25.174: icmp_seq=2212 ttl=58 time=1.856 ms
64 bytes from 172.217.25.174: icmp_seq=2213 ttl=58 time=1.832 ms
64 bytes from 172.217.25.174: icmp_seq=2214 ttl=58 time=1.844 ms
64 bytes from 172.217.25.174: icmp_seq=2215 ttl=58 time=1.822 ms
64 bytes from 172.217.25.174: icmp_seq=2216 ttl=58 time=1.827 ms
64 bytes from 172.217.25.174: icmp_seq=2217 ttl=58 time=1.865 ms
64 bytes from 172.217.25.174: icmp_seq=2218 ttl=58 time=1.845 ms
64 bytes from 172.217.25.174: icmp_seq=2219 ttl=58 time=1.861 ms
64 bytes from 172.217.25.174: icmp_seq=2220 ttl=58 time=1.851 ms
64 bytes from 172.217.25.174: icmp_seq=2221 ttl=58 time=1.868 ms
64 bytes from 172.217.25.174: icmp_seq=2222 ttl=58 time=1.851 ms
64 bytes from 172.217.25.174: icmp_seq=2223 ttl=58 time=1.870 ms
64 bytes from 172.217.25.174: icmp_seq=2224 ttl=58 time=1.849 ms
64 bytes from 172.217.25.174: icmp_seq=2225 ttl=58 time=1.864 ms
64 bytes from 172.217.25.174: icmp_seq=2226 ttl=58 time=1.890 ms
64 bytes from 172.217.25.174: icmp_seq=2227 ttl=58 time=1.873 ms
64 bytes from 172.217.25.174: icmp_seq=2228 ttl=58 time=1.804 ms
64 bytes from 172.217.25.174: icmp_seq=2229 ttl=58 time=1.858 ms
64 bytes from 172.217.25.174: icmp_seq=2230 ttl=58 time=1.842 ms
64 bytes from 172.217.25.174: icmp_seq=2231 ttl=58 time=1.851 ms
64 bytes from 172.217.25.174: icmp_seq=2232 ttl=58 time=1.845 ms
64 bytes from 172.217.25.174: icmp_seq=2233 ttl=58 time=1.883 ms
64 bytes from 172.217.25.174: icmp_seq=2234 ttl=58 time=1.853 ms
64 bytes from 172.217.25.174: icmp_seq=2235 ttl=58 time=1.852 ms
64 bytes from 172.217.25.174: icmp_seq=2236 ttl=58 time=1.768 ms
64 bytes from 172.217.25.174: icmp_seq=2237 ttl=58 time=1.885 ms
64 bytes from 172.217.25.174: icmp_seq=2238 ttl=58 time=1.866 ms
64 bytes from 172.217.25.174: icmp_seq=2239 ttl=58 time=1.826 ms
64 bytes from 172.217.25.174: icmp_seq=2240 ttl=58 time=1.892 ms
64 bytes from 172.217.25.174: icmp_seq=2241 ttl=58 time=1.853 ms
64 bytes from 172.217.25.174: icmp_seq=2242 ttl=58 time=1.825 ms
64 bytes from 172.217.25.174: icmp_seq=2243 ttl=58 time=1.841 ms
64 bytes from 172.217.25.174: icmp_seq=2244 ttl=58 time=1.870 ms
64 bytes from 172.217.25.174: icmp_seq=2245 ttl=58 time=1.857 ms
64 bytes from 172.217.25.174: icmp_seq=2246 ttl=58 time=1.883 ms
64 bytes from 172.217.25.174: icmp_seq=2247 ttl=58 time=1.869 ms
64 bytes from 172.217.25.174: icmp_seq=2248 ttl=58 time=1.863 ms
64 bytes from 172.217.25.174: icmp_seq=2249 ttl=58 time=1.893 ms
64 bytes from 172.217.25.174: icmp_seq=2250 ttl=58 time=1.879 ms
64 bytes from 172.217.25.174: icmp_seq=2251 ttl=58 time=1.858 ms
64 bytes from 172.217.25.174: icmp_seq=2252 ttl=58 time=1.856 ms
64 bytes from 172.217.25.174: icmp_seq=2253 ttl=58 time=1.906 ms
64 bytes from 172.217.25.174: icmp_seq=2254 ttl=58 time=1.829 ms
64 bytes from 172.217.25.174: icmp_seq=2255 ttl=58 time=1.861 ms
64 bytes from 172.217.25.174: icmp_seq=2256 ttl=58 time=1.858 ms
64 bytes from 172.217.25.174: icmp_seq=2257 ttl=58 time=1.861 ms
64 bytes from 172.217.25.174: icmp_seq=2258 ttl=58 time=1.864 ms
64 bytes from 172.217.25.174: icmp_seq=2259 ttl=58 time=1.800 ms
64 bytes from 172.217.25.174: icmp_seq=2260 ttl=58 time=1.841 ms
64 bytes from 172.217.25.174: icmp_seq=2261 ttl=58 time=1.800 ms
64 bytes from 172.217.25.174: icmp_seq=2262 ttl=58 time=1.881 ms
64 bytes from 172.217.25.174: icmp_seq=2263 ttl=58 time=1.842 ms
64 bytes from 172.217.25.174: icmp_seq=2264 ttl=58 time=1.866 ms
64 bytes from 172.217.25.174: icmp_seq=2265 ttl=58 time=1.850 ms
64 bytes from 172.217.25.174: icmp_seq=2266 ttl=58 time=1.819 ms
64 bytes from 172.217.25.174: icmp_seq=2267 ttl=58 time=1.891 ms
64 bytes from 172.217.25.174: icmp_seq=2268 ttl=58 time=1.896 ms
64 bytes from 172.217.25.174: icmp_seq=2269 ttl=58 time=35.675 ms
64 bytes from 172.217.25.174: icmp_seq=2270 ttl=58 time=1.841 ms
64 bytes from 172.217.25.174: icmp_seq=2271 ttl=58 time=1.909 ms
64 bytes from 172.217.25.174: icmp_seq=2272 ttl=58 time=1.908 ms
64 bytes from 172.217.25.174: icmp_seq=2273 ttl=58 time=1.877 ms
64 bytes from 172.217.25.174: icmp_seq=2274 ttl=58 time=1.860 ms
64 bytes from 172.217.25.174: icmp_seq=2275 ttl=58 time=1.886 ms
64 bytes from 172.217.25.174: icmp_seq=2276 ttl=58 time=1.883 ms
64 bytes from 172.217.25.174: icmp_seq=2277 ttl=58 time=1.879 ms
64 bytes from 172.217.25.174: icmp_seq=2278 ttl=58 time=1.834 ms
64 bytes from 172.217.25.174: icmp_seq=2279 ttl=58 time=1.862 ms
64 bytes from 172.217.25.174: icmp_seq=2280 ttl=58 time=1.859 ms
64 bytes from 172.217.25.174: icmp_seq=2281 ttl=58 time=1.868 ms
64 bytes from 172.217.25.174: icmp_seq=2282 ttl=58 time=1.888 ms
64 bytes from 172.217.25.174: icmp_seq=2283 ttl=58 time=1.768 ms
64 bytes from 172.217.25.174: icmp_seq=2284 ttl=58 time=1.853 ms
64 bytes from 172.217.25.174: icmp_seq=2285 ttl=58 time=1.817 ms
64 bytes from 172.217.25.174: icmp_seq=2286 ttl=58 time=1.849 ms
64 bytes from 172.217.25.174: icmp_seq=2287 ttl=58 time=1.865 ms
64 bytes from 172.217.25.174: icmp_seq=2288 ttl=58 time=1.778 ms
64 bytes from 172.217.25.174: icmp_seq=2289 ttl=58 time=1.863 ms
64 bytes from 172.217.25.174: icmp_seq=2290 ttl=58 time=1.869 ms
64 bytes from 172.217.25.174: icmp_seq=2291 ttl=58 time=1.918 ms
64 bytes from 172.217.25.174: icmp_seq=2292 ttl=58 time=1.839 ms
64 bytes from 172.217.25.174: icmp_seq=2293 ttl=58 time=1.864 ms
64 bytes from 172.217.25.174: icmp_seq=2294 ttl=58 time=1.792 ms
64 bytes from 172.217.25.174: icmp_seq=2295 ttl=58 time=1.872 ms
64 bytes from 172.217.25.174: icmp_seq=2296 ttl=58 time=1.881 ms
64 bytes from 172.217.25.174: icmp_seq=2297 ttl=58 time=1.846 ms
64 bytes from 172.217.25.174: icmp_seq=2298 ttl=58 time=1.860 ms
64 bytes from 172.217.25.174: icmp_seq=2299 ttl=58 time=1.864 ms
64 bytes from 172.217.25.174: icmp_seq=2300 ttl=58 time=1.937 ms
64 bytes from 172.217.25.174: icmp_seq=2301 ttl=58 time=1.872 ms
64 bytes from 172.217.25.174: icmp_seq=2302 ttl=58 time=1.853 ms
64 bytes from 172.217.25.174: icmp_seq=2303 ttl=58 time=1.897 ms
64 bytes from 172.217.25.174: icmp_seq=2304 ttl=58 time=1.970 ms
64 bytes from 172.217.25.174: icmp_seq=2305 ttl=58 time=1.870 ms
64 bytes from 172.217.25.174: icmp_seq=2306 ttl=58 time=1.897 ms
64 bytes from 172.217.25.174: icmp_seq=2307 ttl=58 time=1.901 ms
64 bytes from 172.217.25.174: icmp_seq=2308 ttl=58 time=1.897 ms
64 bytes from 172.217.25.174: icmp_seq=2309 ttl=58 time=1.881 ms
64 bytes from 172.217.25.174: icmp_seq=2310 ttl=58 time=1.995 ms
64 bytes from 172.217.25.174: icmp_seq=2311 ttl=58 time=1.908 ms
64 bytes from 172.217.25.174: icmp_seq=2312 ttl=58 time=1.884 ms
64 bytes from 172.217.25.174: icmp_seq=2313 ttl=58 time=1.929 ms
64 bytes from 172.217.25.174: icmp_seq=2314 ttl=58 time=1.837 ms
64 bytes from 172.217.25.174: icmp_seq=2315 ttl=58 time=1.848 ms
64 bytes from 172.217.25.174: icmp_seq=2316 ttl=58 time=1.775 ms
64 bytes from 172.217.25.174: icmp_seq=2317 ttl=58 time=1.820 ms
64 bytes from 172.217.25.174: icmp_seq=2318 ttl=58 time=1.779 ms
64 bytes from 172.217.25.174: icmp_seq=2319 ttl=58 time=1.878 ms
64 bytes from 172.217.25.174: icmp_seq=2320 ttl=58 time=2.116 ms
64 bytes from 172.217.25.174: icmp_seq=2321 ttl=58 time=1.865 ms
64 bytes from 172.217.25.174: icmp_seq=2322 ttl=58 time=1.858 ms
64 bytes from 172.217.25.174: icmp_seq=2323 ttl=58 time=1.859 ms
64 bytes from 172.217.25.174: icmp_seq=2324 ttl=58 time=1.865 ms
64 bytes from 172.217.25.174: icmp_seq=2325 ttl=58 time=1.907 ms
64 bytes from 172.217.25.174: icmp_seq=2326 ttl=58 time=1.912 ms
64 bytes from 172.217.25.174: icmp_seq=2327 ttl=58 time=1.821 ms
64 bytes from 172.217.25.174: icmp_seq=2328 ttl=58 time=1.839 ms
64 bytes from 172.217.25.174: icmp_seq=2329 ttl=58 time=1.758 ms
64 bytes from 172.217.25.174: icmp_seq=2330 ttl=58 time=1.826 ms
64 bytes from 172.217.25.174: icmp_seq=2331 ttl=58 time=1.782 ms
64 bytes from 172.217.25.174: icmp_seq=2332 ttl=58 time=3.111 ms
64 bytes from 172.217.25.174: icmp_seq=2333 ttl=58 time=1.874 ms
64 bytes from 172.217.25.174: icmp_seq=2334 ttl=58 time=2.574 ms
64 bytes from 172.217.25.174: icmp_seq=2335 ttl=58 time=1.903 ms
64 bytes from 172.217.25.174: icmp_seq=2336 ttl=58 time=1.865 ms
64 bytes from 172.217.25.174: icmp_seq=2337 ttl=58 time=3.699 ms
64 bytes from 172.217.25.174: icmp_seq=2338 ttl=58 time=1.967 ms

**Comment by ppolewicz** [comment]
Looks like nasty QoS or something - ping works, but data connection does not.

You can use this command to collect network traces:
`tcpdump -n -i any -C20 -s 68 -W 10 -w issue_330.pcap net 162.244.56.0/21`
it needs to be run from an privileged account and it needs to be stopped soon after you encounter an error.

**Comment by clintinthecode** [comment]
tcpdump -n -i any -C20 -s 68 -W 10 -w issue_330.pcap net 162.244.56.0/21
tcpdump: any: No such device exists
(BIOCSETIF failed: Device not configured)

I get the above error when trying to run it from root. I am using freeBSD os.

Im not sure the issue is at our end, in the past for about 6 months we were running two jails on this server, each jail an identical clone, one had one Backblaze account, the other jail had a second Backblaze account, everything else identical, yet one would give these errors and the other jail wouldn't give these errors, both jails set to run the bas script every 2 mins. That makes me believe its not a connection issue at our end otherwise both jails would experience the same connection issues.

Is there any kind of max connections in a time window set on the server it connects to? any way the server could be blocking connections by any chance?

**Comment by ppolewicz** [comment]
eh, freeBSD :)

instead of `-i any` use `-i NET_INTERFACE_NAME`, where NET_INTERFACE_NAME is the name of the network interface that routes the packets to the internet (for me it is `eth0`, you can probably view interfaces by using `ifconfig` console command)

**Comment by clintinthecode** [comment]
Ok cool that does something, what is the expected output? I let it run for 10 seconds and didn't see any output so hit ctrl c to stop it and got this:

tcpdump -n -i igb0 -C20 -s 68 -W 10 -w issue_330.pcap net 162.244.56.0/21
tcpdump: listening on igb0, link-type EN10MB (Ethernet), capture size 68 bytes
^C127205 packets captured
128660 packets received by filter
0 packets dropped by kernel

What should I be looking for?

**Comment by ppolewicz** [comment]
It hangs until you kill it. What it does, is it listens to what happens in the network, filters the traffic so that only what goes to/from backblaze is considered and it saves that to `.pcap` files for analysis later. Additionally, it cuts each packet just after 68 bytes, so no actual data is collected, only the packet headers.

If this is running when you have an error, then the packet traces can be opened using a special program (usually Wireshark) and a human then can see what was going on.

Network administrators are known to actually react sometimes if you show them a packet dump and a screenshot made with wireshark, showing that something is not working correctly.

**Comment by clintinthecode** [comment]
Thank you for the explanation, all makes sense now :) Ok cool so I just start that now, and wait however long until the next error happens and kill it then and put the log file here?

**Comment by ppolewicz** [comment]
Basically yes, however the command makes a rotating ring of the log files, of total size not more than 200MB. Probably the file with the latest modification date will be sufficient for analysis, but we may need a couple more files in a rare case.

**Comment by clintinthecode** [comment]
Ok I've had it fail again, and a minute after I noticed the email alert I stopped the log, was running for about an hour or so, there is 10 files, 9 at 20mb and one at 9.4mb, will get them off the server soon and attach here or host somewhere else

**Comment by ppolewicz** [comment]
the 9.4mb file should be sufficient for analysis. Probably it can be compressed quite well with `gzip filename`.

**Comment by clintinthecode** [comment]
[issue_330.pcap2.gz](https://github.com/Backblaze/B2_Command_Line_Tool/files/849720/issue_330.pcap2.gz)

Ok, I've got the 9.4mb file, compressed down a bit smaller.

**Comment by ppolewicz** [comment]
It looks like the freeBSD box is trying to open and close a port at the same time.

**Comment by ppolewicz** [comment]
I found a missing flag in a series of packets. It seems that the server and the client have a different idea of the state of the socket.

The trace for a given ip-port pair is:
```
(successful connection goes on, client is receiving data, then)
client: FIN,ACK
1s later client: FIN,ACK
2s later client: FIN,ACK
3.5s later client: FIN,ACK
6.6s later client: FIN,ACK
(here client probably gave up)
6.7s later server: ACK
25us later server FIN,ACK
3us later client: RST
18us later client: RST
(client doesn't recognize the connection anymore at this point, so RST)

then there is a loop of server trying to say something over the closed connection (already confirmed with FIN,ACK long time ago), probably https "goodbye", with exponential backoff, and client replying RST to all of that.

And then, freebsd box, **on the same source port**:
client: SYN
server: ACK (not SYN,ACK!)
client: RST

3s later:
client: SYN
server: ACK (not SYN,ACK!)
client: RST

3s later:
client: SYN
server: ACK (not SYN,ACK!)
client: RST

and this happens every 3 or so seconds for a while until client gives up.
```
Weird.

It doesn't look like a bug in our code at all. Maybe it is [this](https://lists.freebsd.org/pipermail/freebsd-net/2011-July/029350.html) or long "time to forget" set in freebsd kernel?

**Comment by bwbeach** [comment]
Thanks @ppolewicz for looking at this!

**Comment by ppolewicz** [comment]
It was a network-level issue triggered most likely by a large file commit over high latency network. Unseen for 4 years, I think it's been resolved with one of the readjustments of the network stack at Backblaze, or maybe freebsd was patched to not reuse ports the way it did in that fascinating network dump (because that could not have ended well).
