### ISSUE TITLE
"[Error 3] Windows error" during sync - sync stops - no continuing - maybe bad folder name???

### ISSUE THREAD

**Issue by willkathy** [Backblaze/B2_Command_Line_Tool#336]
While backing up a major folder with B2 sync, encountered an "[Error 3]
Windows error". Cannot explain why. Error stops the entire sync and will not
continue.  Console output is attached. Folder listed has (1) file in it that I can
open and browse.

Thank you for any help

[SyncTestOutput.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/911483/SyncTestOutput.txt)

**Comment by svonohr** [comment]
It seems that this a problem on windows regarding long path names. As a quick solution you could try to prepend your local path with `\\?\` which should allow for longer paths. For your example this would be:
`b2 sync --excludeRegex 'DS_Store' --skipNewer \\?\p:\Agilent_LCMS b2://TWIBackupE`

**Comment by willkathy** [comment]
svonohr - Thank you for the quick update - that solution worked great.  Wil.
