### ISSUE TITLE
Enhacements

### ISSUE THREAD

**Issue by ingejae** [Backblaze/B2_Command_Line_Tool#338]
Hi Guys, I'm evaluating to move from Google Nearline to B2, but I have the next comments about B2 CLI:
- I think it should work like Linux rsync; I made some tests cancelling a file upload, and the upload started over, even if some MB where already uploaded.
- The command b2 upload-file, it should take only two parameters, because in general, the **localFilePath** is the same as the **b2FileName**; besides it should take **wildcards** for uploading several files at once.

**Comment by svonohr** [comment]
Resuming uploads works only with files that are beeing uploaded in several parts (so called large files). When starting a file upload that matches an unfinished large file, only the missing parts are uploaded. But if none of the parts finished before, the whole file needs to be sent again. Depending on your network connection you could change the minimum part size (default 100MB) and the number of threads.

**Comment by ppolewicz** [comment]
for uploading a series of files you can use b2 sync, or a bash loop
