### ISSUE TITLE
list_file_versions not working with startFileName

### ISSUE THREAD

**Issue by ender9441** [Backblaze/B2_Command_Line_Tool#341]
list_file_versions is not working correctly.

1) doesn't seem to honor the --maxFileCount=10000
2) doesn't honor --startFileName=...

I have just over 10k files and I'm trying to delete those older than 90 days.  If either maxFileCount or startFileName worked, I would be able to do it.  I have tested with a script and manually.

```
[01:21 root@hostname tools]$ b2 version
b2 command line tool, version 0.6.9
```

```
[01:31 root@hostname tools]$ b2 list_file_versions dbops-mysql-backup --maxFileCount=10 > /tmp/b2_orphan_list.out
[01:31 root@hostname tools]$ ls -alh /tmp/b2_orphan_list.out
-rw-r--r-- 1 root root 43K Apr 22 01:31 /tmp/b2_orphan_list.out
[01:31 root@hostname tools]$ wc -l /tmp/b2_orphan_list.out
1106 /tmp/b2_orphan_list.out
[01:32 root@hostname tools]$ b2 list_file_versions dbops-mysql-backup --startFileName=us0101acsd002_3300 | head -10
{
  "files": [
    {
      "action": "upload",
      "contentLength": 4522378552,
      "contentSha1": null,
      "contentType": "application/octet-stream",
      "fileId": "4_z92fc1393117294535d6d0b16_f202fd0c5e75f8165_d20170124_m093002_c001_v0001011_t0026",
      "fileInfo": {},
      "fileName": "us0101aasd002_3306/backup_full_20170124091840.tgz",

```

**Comment by svonohr** [comment]
I does work if you follow the correct syntax. I've tested with
`b2 list-file-versions sebi707-test aaa.txt 4_zfa90141fcad85236564d0d16_f11573cd2f1ee1b9c_d20160621_m204513_c001_v0001031_t0004 2`
Which does return only 2 file versions starting at the correct file.

**Comment by ender9441** [comment]
Thank you!  That works.

Is it incorrect to use things like --maxFileCount=?  I was looking at https://www.backblaze.com/b2/docs/b2_list_file_versions.html

It lists some of the values as optional.  Perhaps there is different documentation somewhere else?

**Comment by svonohr** [comment]
The documentation you referenced is for the HTTP API and not for the commandline tool. For information about the commandline tool you can run `b2 help` or `b2 help list-file-versions` for more information on specific commands:
```
b2 list-file-versions <bucketName> [<startFileName>] [<startFileId>] [<maxToShow>]

    Lists the names of the files in a bucket, starting at the
    given point.  This is a low-level operation that reports the
    raw JSON returned from the service.  'b2 ls' provides a higher-
    level view.
```
Currently it's not supported to specify only the maximum number of files because it's the last optional argument.
