### ISSUE TITLE
Ability to read part of the file?

### ISSUE THREAD

**Issue by k06a** [Backblaze/B2_Command_Line_Tool#344]
Can't find this option in doc.

**Comment by svonohr** [comment]
This feature is not yet supported by B2 CLI. It's possible using the HTTP Range header though, as described here: https://www.backblaze.com/b2/docs/b2_download_file_by_id.html

**Comment by k06a** [comment]
@svonohr oh, thanks a lot!

**Comment by k06a** [comment]
Looks like it is implemented in `api.py` and `raw_api.py` but not yet supported by `console_utility.py` yet.
