### ISSUE TITLE
Memory leak when using "sync --delete" command

### ISSUE THREAD

**Issue by dpedu** [Backblaze/B2_Command_Line_Tool#347]
I'm using the following command:

```
b2 sync --delete . b2://my-bucket-name
```

The current directory has nothing in it; I'm using this to "empty out" a bucket. The bucket contains no "normal" files and over 1 million "hidden" files.

After about 250,000 files are deleted, the b2 program is killed by my linux system's OOM killer:

```
May 30 22:15:54 homeapps8 kernel: [2299486.889839] Out of memory: Kill process 73571 (b2) score 474 or sacrifice child
May 30 22:15:54 homeapps8 kernel: [2299486.889940] Killed process 73571 (b2) total-vm:1736112kB, anon-rss:961892kB, file-rss:0kB
```

**Comment by ppolewicz** [comment]
This is a perfect task for someone who never investigated memory consumption issues.

**Comment by mjurbanski-reef** [comment]
The 1GB of memory use doesn't sound disastrous, so it may have happened just due to the sheer amount of parallelization. Limiting threads may help. Nevertheless, please reopen if error still occurs with current version and default parallelization.
