### ISSUE TITLE
B2 authorisation fails

### ISSUE THREAD

**Issue by silversurfpc** [Backblaze/B2_Command_Line_Tool#351]
Using MacOS Sierra. Installed b2 using pip, (no error message regarding six library). 

Unable to authorise, when I try to use command 'b2 autorize_account' command. Account ID and Application Key newly generated and copied from webpage. Here's the output:
---
b2 authorize_account 
Using https://api.backblazeb2.com
Backblaze account ID: a6954f70xxxx
Backblaze application key: <pasted from webpage, lowercase hex 57 characters>
ERROR: unable to authorize account: Invalid authorization token. Server said: Invalid authorization token (bad_auth_token)
---

What am I doing wrong?

**Comment by svonohr** [comment]
Are you sure that you copied the application key correctly? My application key is only 42 characters and an odd number like 57 seems really unusual for hex.

**Comment by silversurfpc** [comment]
Using a temporary account I generated a test key :

001595bc99b5dbfe1c91496159d63c416a31ace7cc

42 characters 

I'll check again with the live application

**Comment by silversurfpc** [comment]
Yes, you're correct. The key was wrong.
