### ISSUE TITLE
Sync does not recursively sink an entire folder

### ISSUE THREAD

**Issue by taz77** [Backblaze/B2_Command_Line_Tool#352]
I started to experiment with the command line utility but I notice one flaw. It will not recursively sync a folder. I read the documentation a couple of times and I see no controls for this. I sync'ed a local folder and it got all the files in the root minus a few (separate issue) but it did not sync the sub-folders.

**Comment by svonohr** [comment]
That's strange. It should sync all the subfiles aswell. Can you describe your setup? What operating sytem do you use? Are these local files or some mounted network path, etc.?

**Comment by taz77** [comment]
Mac. Installed the B2 tools via Homebrew. Local files, no remote mount.

I tried several times. It will not sync subfolders. 

It also will not sync files beginning with a `!` in the file name.

**Comment by taz77** [comment]
I may have found something. Still investigating. The folder I was syncing was a local folder that is a part of my Dropbox folder.

**Comment by bwbeach** [comment]
I just tried syncing folders (with subfolders) inside by Dropbox.  Worked fine.

This is on macOS Sierra, python 2.7.13, and B2 command line 0.7.2.

**Comment by ppolewicz** [comment]
Dropbox may mount a transparent filesystem that uploads and downloads data in the background, so that one thinks he sees his own folder, but really that folder does not contain the files (they are in the cloud). You can see the mounted filesystems by using `mount` command in your terminal.

**Comment by taz77** [comment]
I haven't the foggiest idea what was going on with Dropbox folders. I cannot replicate my own issue now so I am going to close this.
