### ISSUE TITLE
How to get uploadTimestamp to show in human readable format?

### ISSUE THREAD

**Issue by nsills** [Backblaze/B2_Command_Line_Tool#353]
When I list files the uploadTimestamp is not in human readable format, ex) "uploadTimestamp": 14894296390000.

How can I get this to show up as a MMddYYYY or similar format? I am trying to use the cli to verify the backups are up to date.

Thanks.

**Comment by svonohr** [comment]
You could try `b2 ls --long <bucketName>`

**Comment by ppolewicz** [comment]
```
$ echo "Your file was created $(( $(date +%s) - 14894296390000/10000 )) seconds ago"
Your file was created 10275560 seconds ago
```
So like ~118 days.
