### ISSUE TITLE
0.7.3 is not released on pypi

### ISSUE THREAD

**Issue by szepeviktor** [Backblaze/B2_Command_Line_Tool#355]
@bwbeach Could you please release it?

**Comment by szepeviktor** [comment]
@bwbeach Not even tagged here.

**Comment by svonohr** [comment]
Version 0.7.3 is the current development version. The current release is 0.7.2 as available on pypi. Note that release versions have an even number at the end, while development versions are odd.

**Comment by szepeviktor** [comment]
Oh, thank you!
