### ISSUE TITLE
Looking for an official Docker container from the Backblaze team.

### ISSUE THREAD

**Issue by pascalandy** [Backblaze/B2_Command_Line_Tool#358]
Hi

### Manual installation:

I tried to run it a container and it works perfectly. Here is how I installed it manually.

```
# Run Node container
docker run -dit --name b2cli \
python:alpine sh && \

# Connect into Node container
docker exec -it b2cli sh;

# Alpine preparation
apk update && \
apk upgrade && \
apk add git

# Install b2cli
git clone https://github.com/Backblaze/B2_Command_Line_Tool.git && \
cd B2_Command_Line_Tool && \
python setup.py install

# See version
b2 version
        # b2 command line tool, version 0.7.3
```

### Looking for:

Now, I don't want to preserve the accountId & applicationKey in the container of even on the host for security reasons.

I'm looking for a Docker container where we could pass the accountId & applicationKey as vars (or even better via Docker secrets).

Is it in you plans to build one?

Thank you in advance!
P.S. Actually using rclone and Arq with backblaze.

**Comment by bwbeach** [comment]
A docker container would be great.  I'm wondering if there's a way for the build on Travis CI to build it.

Would you be interested in giving it a try?  There's a bunch of helpful people here who can answer questions and offer advice.  And it would be great for you to join us.

**Comment by msrumon** [comment]
> A docker container would be great. I'm wondering if there's a way for the build on Travis CI to build it.
> 
> Would you be interested in giving it a try? There's a bunch of helpful people here who can answer questions and offer advice. And it would be great for you to join us.

I'd like to. What do I need to do?

**Comment by ppolewicz** [comment]
I think the pull request for adding the docker container is in review already, I've seen someone working on it a few weeks ago. Let me check on the progress of it.

**Comment by ppolewicz** [comment]
@msrumon #859 has just been merged. Would you like to take it for a spin before we upload the image to dockerhub?

**Comment by msrumon** [comment]
> @msrumon #859 has just been merged. Would you like to take it for a spin before we upload the image to dockerhub?

Thanks. I'll have a look at it tonight.

**Comment by ppolewicz** [comment]
@msrumon you should run `nox -s docker` to create the `Dockerfile` and then you can run that

Also please note that if you edit a github issue comment, no notifications are sent. I only noticed your message by accident.

**Comment by msrumon** [comment]
> Also please note that if you edit a github issue comment, no notifications are sent. I only noticed your message by accident.

Oops! 😬

> @msrumon you should run `nox -s docker` to create the `Dockerfile` and then you can run that

Is `nox` some kind of CLI I have to install? Look, I don't work with Python and I barely have any stack installed natively on my PC. I run everything off of Docker (Yes, all my projects are maintained with Docker Compose file).

**Comment by ppolewicz** [comment]
`nox` can be installed with `pip3 install nox` - it's a development tool we use in this project to run tests, build documentation etc - and now also to build a docker image.

**Comment by ppolewicz** [comment]
it's been built but not published so that we could catch any bugs in it and we've found some. Now that those are addressed, we'll publish it.

**Comment by ianthetechie** [comment]
Fantastic; thanks for the update @ppolewicz!

**Comment by mpnowacki-reef** [comment]
The official image has been released https://github.com/Backblaze/B2_Command_Line_Tool#docker-image
