### ISSUE TITLE
Upload error: File names must contain unicode characters with codes less than 32 - need indication of file

### ISSUE THREAD

**Issue by taz77** [Backblaze/B2_Command_Line_Tool#362]
I get a 400 error syncing files due to some file names that B2 does not like.
`UnknownError: Unknown error: 400 bad_request File names must not contain unicode characters with codes less than 32`

That is fine, but the problem is the b2 command line tool is not telling me which file it doesn't like so I have no way of fixing this (huge folders with over 300,000 files). The stdout should identify the filepath that caused the error so the user can correct the file name.

**Comment by ppolewicz** [comment]
you are right, this should be fixed. For now, I think you could try enabling [detailed logs](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs), it should give you some more information which will hopefully be sufficient to resolve the issue in your filesystem.

**Comment by Znarkus** [comment]
Sadly --verbose doesn't help to identify which file is the problem

**Comment by bwbeach** [comment]
One possibility is to validate the names before attempting to upload.  

The rules for file names are in the [B2 docs](https://www.backblaze.com/b2/docs/files.html).

**Comment by dgentry** [comment]
This is fixed (by validating names before upload), although it could "try harder" in the face of an unusable filename.  The new `sync` behavior reports the offending filename in an exception (and stack trace), and stops execution.

The two "try harder" behaviors I can think of would be to:
1.  Report the offending filename and continue sync'ing everything else, or
2. Attempt to encode the offending filename into something usable, report the attempt, and continue.

But perhaps that should be opened in a separate issue.  The second one especially has additional details to work out.

**Comment by bwbeach** [comment]
I agree that either of those two options should be a new issue, if somebody wants to argue for one of them.

I'm a little worried about changing the offending file name because it might change the sort order, so the the next sync would not match the source file with the one that was uploaded.
