### ISSUE TITLE
src_last_modified_millis in -info is not applying to the download

### ISSUE THREAD

**Issue by doomsayr** [Backblaze/B2_Command_Line_Tool#367]
When I upload a file with src_last_modified_millis and the timestamp, when the file is downloaded it is not retaining the data, and the file displays today's date.

**Comment by svonohr** [comment]
I can confirm this bug on Ubuntu. There is code which is supposed to change the timestamp, but somehow it's not working.

**Comment by bwbeach** [comment]
I can confirm on MacOS.
