### ISSUE TITLE
Add option to exit sync if source directory is empty 

### ISSUE THREAD

**Issue by shane-axiom** [Backblaze/B2_Command_Line_Tool#369]
An option to exit the `sync` command if the source directory is empty would be useful. Currently it's easy to run `sync` with a typo in the source path or against an unmounted source path and delete all files in a B2 bucket. Since the normal use case is to run against a non-empty source directory, an option to check if the source directory is non-empty and fail if it is would be a nice sanity check.

**Comment by bwbeach** [comment]
This is an excellent idea.  Would you be interested in making the extension to the code?

**Comment by shane-axiom** [comment]
@bwbeach I took a stab at it here. Tested and seems to be working correctly.

https://github.com/Backblaze/B2_Command_Line_Tool/pull/370
