### ISSUE TITLE
b2 upload

### ISSUE THREAD

**Issue by dougwyu** [Backblaze/B2_Command_Line_Tool#372]
i tried to upload an admittedly fairly large tar file to B2 for archiving. However, the job failed three times.

here is my command, and I attach the err file. I don't think that the problem is on my side, but please let me know if it is.

b2 upload-file --threads 16 --sha1 f0196b9c969f0e933f839bae85a46eade6cbbb83 greenland-2016-Copenhagen-mtgenome-refs Copenhagen_mtgenome_refs.tar Copenhagen_mtgenome_refs.tar

[b2upload_old.err.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/1317885/b2upload_old.err.txt)

**Comment by ppolewicz** [comment]
This was fixed in https://github.com/Backblaze/B2_Command_Line_Tool/pull/356
