### ISSUE TITLE
Cant install on CentOS 7

### ISSUE THREAD

**Issue by ArvyRogerio** [Backblaze/B2_Command_Line_Tool#373]
(...)
Installed /usr/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg
Searching for funcsigs
Reading https://pypi.python.org/simple/funcsigs/
Best match: funcsigs 1.0.2
Downloading https://pypi.python.org/packages/94/4a/db842e7a0545de1cdb0439bb80e6e42dfe82aaeaadd4072f2263a4fbed23/funcsigs-1.0.2.tar.gz#md5=7e583285b1fb8a76305d6d68f4ccc14e
Processing funcsigs-1.0.2.tar.gz
Writing /tmp/easy_install-BwQ8X8/funcsigs-1.0.2/setup.cfg
Running funcsigs-1.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BwQ8X8/funcsigs-1.0.2/egg-dist-tmp-TvMeor
error: Installed distribution setuptools 0.9.8 conflicts with requirement setuptools>=17.1

[root@h4 B2_Command_Line_Tool]# python --version
Python 2.7.5

[root@h4 B2_Command_Line_Tool]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

[root@h4 B2_Command_Line_Tool]# uname -a
Linux xxx 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bwbeach** [comment]
What was the (failed) command you used to install b2?

From the snipped of error you posted, it looks like it failed trying to install `funcsigs`.

**Comment by ArvyRogerio** [comment]
Git clone and then ... "python setup.py install".
My server already has setuptools (0.9.8) installed, probably by Let's Encrypt (git) or other.

**Comment by ArvyRogerio** [comment]
June 2018, still cannot install on CentOS 7.5

[root@mercurio inweb]# yum install python python-setuptools -y
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
Package python-2.7.5-68.el7.x86_64 already installed and latest version
Package python-setuptools-0.9.8-7.el7.noarch already installed and latest version
Nothing to do

[root@mercurio inweb]# cd /root

[root@mercurio ~]# git clone https://github.com/Backblaze/B2_Command_Line_Tool.git
Cloning into 'B2_Command_Line_Tool'...
remote: Counting objects: 5316, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 5316 (delta 12), reused 21 (delta 10), pack-reused 5284
Receiving objects: 100% (5316/5316), 1.34 MiB | 9.46 MiB/s, done.
Resolving deltas: 100% (3783/3783), done.

[root@mercurio ~]# cd B2_Command_Line_Tool

[root@mercurio B2_Command_Line_Tool]# python setup.py install
setuptools 20.2 or later is required. To fix, try running: pip install "setuptools>=20.2"

**Comment by ppolewicz** [comment]
`pip install -U setuptools`?

**Comment by texupport-git** [comment]
Is this still a live thread ? I am having the same errors, the upgrade command does not work. 

[root@mdb-hc-01 ~]#  pip install "setuptools>=20.2"
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/cmdoptions.py", line 107
    binary_only = FormatControl(set(), {':all:'})
                                               ^
SyntaxError: invalid syntax

[root@mdb-hc-01 ~]# pip install -U pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python2.6/site-packages/pip/_internal/cli/cmdoptions.py", line 107
    binary_only = FormatControl(set(), {':all:'})
                                               ^

**Comment by ppolewicz** [comment]
@texupport-git the trackback shows that you are using python 2.6, which is not supported since 2013

**Comment by mjurbanski-reef** [comment]
At the current time, for current B2 CLI version, Python 3.7 is required at the minimum. You can install a self-contained binary version as described here: https://www.backblaze.com/docs/cloud-storage-command-line-tools#selfcontained-download .
