### ISSUE TITLE
Linux b2 only syncing files, not folders

### ISSUE THREAD

**Issue by Rickymundo** [Backblaze/B2_Command_Line_Tool#376]
Hi there,

I have an Ubuntu server with Samba configured. On that server I have a share located at:
/mnt/raid1/shares/xxxxxx/Dropbox

Through another pc with Windows I can read and write to this network share. With a batch script I daily copy the contents of my Dropbox folder from the Windows pc to the network share, hence the name Dropbox of the share on the server. 

Now, with crontab I have the following code:

`*/1 * * * * run-one /usr/local/bin/b2 sync --keepDays 365 --replaceNewer --threads 1 /mnt/raid1/shares/xxxxx/Dropbox b2://xxxxxx/Dropbox >> /home/xxxxx/cronjob.log
`

This code is ran by root. For testing purposes it is set to every minute.
Now the problem is that when I create a few test files with Notepad from the Windows pc and they're stored on to the network share, every minute they are synced with Backblaze B2, however, only the files. If I create folders, they aren't synced. 

So on my share I have the following files:
- Test1.txt
- Text2.txt
- Folder1
- Folder2

But only the files are being copied, not the folders. The output of the cronjob log shows that the files are being uploaded but never talks about the folders. I don't get this. First I thought it could be a permission issue from the folder but since the folders are syncing I believe that this can't be the issue. Is this a bug or is it me that I'm not seeing something? ( I'm from The Netherlands so please forgive my typo's and grammar ).

 
Edit:
I've done some more testing. It think it needs to be narrowed down to syncing empty folders ( which it doesn't ) ?

**Comment by bwbeach** [comment]
(Hello Netherlands from Hawaii.  Your typing and grammar are excellent!)

B2 does not have any concept of directories/folders.  There are only files.  The [Backblaze doc page about files](url) have a section on this called "Folders (There Are No Folders)".

Some of the tools that have integrated with Backblaze create a file called ".bzEmpty" as something to sync when there are empty directories.

**Comment by Rickymundo** [comment]
Hi Hawaii! 

thank you for your prompt response and your compliment! I've read the docs and I feel stupid. I've spend more than 5 houres figuring this out. Now I understand how it works. This case can be closed now. Thanks for the help!
