### ISSUE TITLE
Off by one error in raw_api._download_file_from_url

### ISSUE THREAD

**Issue by obeleh** [Backblaze/B2_Command_Line_Tool#377]
I keep thinking this must be an error on my part but I can't see how I'm wrong.

I'm calling the following function:

```python
def download_file_by_id(
        self, download_url, account_auth_token_or_none, file_id, download_dest, range_=None
    )
```

The [documentation](https://www.backblaze.com/b2/docs/b2_download_file_by_id.html) for downloading a file says about the range parameter:

> The value "bytes=0-99" selects bytes 0 through 99 (inclusive) of the file, so it will return the first 100 bytes

range_ is specified as a tuple (in _download_file_from_url)

```python
if range_ is not None:
    assert len(range_) == 2, range_
    assert (range_[0] + 0) <= (range_[1] + 0), range_  # not strings
    assert range_[0] >= 0, range_
    assert range_[1] >= 1, range_
    request_headers['Range'] = "bytes=%d-%d" % range_
```
So When I want the first 1048576 bytes and I request the range `(0, 1048576 - 1)`. The response header contains `'Content-Length', '1048576'` which is correct. But later on there is the following validation:

```python
desired_length = range_[1] - range_[0]
if bytes_read != desired_length:
    raise TruncatedOutput(bytes_read, desired_length)
```

But that fails with the message:
> TruncatedOutput: only 1048576 of 1048575 bytes read

I can only come to the conclusion that the desired length should have been:

```python
desired_length = range_[1] - range_[0] + 1
```

But I'm confused because I wouldn't expect me to be the only one to have this issue.

**Comment by svonohr** [comment]
I think you are correct and this is an actual bug. Possibly you are the first one who used this range parameter since the CLI doesn't use it and I don't know how many people use the Python API. Since you seem to be a Python developer, would you like to fix this bug and add a test case for this?

**Comment by obeleh** [comment]
I don't think a test is really needed since it's checked by this line:

```python
if bytes_read != desired_length:
    raise TruncatedOutput(bytes_read, desired_length)
```
