### ISSUE TITLE
Version 0.7.3 - No longer support syncing an empty bucket

### ISSUE THREAD

**Issue by doomsayr** [Backblaze/B2_Command_Line_Tool#379]
Version 0.7.3 of the B2 cli, no longer supports syncing an empty folder.
This is used to to delete all of the files in a bucket.

b2 sync --delete bucketName emptyDir b2://destination

**Comment by svonohr** [comment]
In PR #360 it was decided to change the default behavior and not allow empty sync sources. The old behavior can be restored by using the `--allowEmptySource` option. Since 0.7.3 is not an official release yet, we haven't announced this breaking change.

**Comment by bwbeach** [comment]
I'm going to update the error message to suggest `--allowEmptySource` if you want to sync an empty directory.

**Comment by bwbeach** [comment]
I have reverted 0.7.3 to the old behavior.

When we release 1.0, it will have the new behavior, with the improved error message.
