### ISSUE TITLE
What's the relationship between lifecycle rules and b2 sync --delete and --keepDays?

### ISSUE THREAD

**Issue by cy18** [Backblaze/B2_Command_Line_Tool#392]
I'm confused with the two features.
For example, if I use "Keep only the last version of the file" lifecycle rule, will "b2 sync --keepDays 7" still work, i.e., keep old versions for 7 days?
Otherwise, if I use "Keep prior versions for this number of days: 30" lifecycle rule, will "b2 sync --delete" delete the deleted files immediately, or kept them for 30 days?
Furthermore, what if I use "Keep prior versions for this number of days: 30" lifecycle rule and "b2 sync --keepDays 7"? How long will the old versions be kept?

**Comment by bwbeach** [comment]
Sorry for the delay getting back to you...

The two features are independent.  Both are ways to delete files that are older than you want.

When you run `b2 sync --keepDays 7 ...`, it will delete files that have been hidden for more than 7 days.  If you have a lifecycle rules with `daysFromHidingToDeleting` set to 7, it has the same effect.

The difference is when the rules are applied.  The option to sync applies just to when you sync.  If you stop syncing, it will stop cleaning up old files.  Lifecycle rules, on the other hand, are applied automatically once a day by the Backblaze servers.

**Comment by cy18** [comment]
Thank you for your reply.
Just to make sure, does it means "b2 sync --delete" will delete the file immediately, even "keep all versions" lifecycle rule is applied?

**Comment by bwbeach** [comment]
Yes.  That's right.  If you tell the command-line tool to delete files, it will delete them.  Having a lifecycle rule in place does not prevent any deletions.

**Comment by cy18** [comment]
Thank you
