### ISSUE TITLE
Non-English characters don't display properly in the output

### ISSUE THREAD

**Issue by dima-ser** [Backblaze/B2_Command_Line_Tool#399]
I have lots of files with Cyrillic paths and this is what I see in the logs when I sync them:

```
!WARNING! this terminal cannot properly handle progress reportingupload Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0444\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b.jpg
upload Music Stuff/Uncompressed WAVs/April Instrumental.wav
upload Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0413\u043e\u043b\u0443\u0431\u043e\u0435 \u043d\u0435\u0431\u043e.wav
upload Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u041f\u0435\u0441\u043d\u044f \u0434\u043b\u044f \u0434\u0440\u0443\u0433\u0430 (\u0441\u0432\u0430\u0434\u0435\u0431\u043d\u0430\u044f).wav
```

Is there a way to make them show up properly? I'm on Ubuntu 16.04 LTS

**Comment by ppolewicz** [comment]
I suggest that you try setting encoding of your terminal to utf8, like [this](https://askubuntu.com/questions/298971/full-switch-locale-ubuntu-server-installed-with-no-locales-how-to-enable-local)

**Comment by dima-ser** [comment]
Sorry, I'm new to Linux. I read your link but I'm still not sure what command should I run.

The content of my /etc/default/locale is 

```
#  File generated by update-locale
LANG="en_US.UTF-8"
```
It appears my locale is already set to UTF8?
I don't want to switch my locale to Russian or anything, I just want it to be able to display those characters. The suggested solution I saw was to run

```
locale-gen en_US.UTF-8
```
but isn't my locale already set to that? Should I change it to Russian to display those characters? If so, what command do I run and will that affect other things on my system?

**Comment by bwbeach** [comment]
I still find encoding in Python confusing.  You can check the current setting like this:

```
$ python
Python 3.5.4 (default, Sep 22 2017, 08:33:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
```

I think it can get the setting from the `LANG` environment variable, but if `PYTHONIOENCODING` is set, it will override.

```
$ export PYTHONIOENCODING=ASCII
$ echo $LANG
en_US.UTF-8
$ echo $PYTHONIOENCODING
ASCII
$ python
Python 3.5.4 (default, Sep 22 2017, 08:33:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'ASCII'
```

**Comment by dima-ser** [comment]
Ok, my current python encoding (sys.stdout.encoding) is UTF-8. Are you saying I should switch it to ASCII like in your example? Won't that do the opposite, I thought ASCII can only handle English characters? What should I set my python encoding to?

**Comment by svonohr** [comment]
I'm not sure how python decided to print the string like in your output, but your example it looks like UTF-16 encoding. At least the `\u0424` at the begin of your path corresponds to a cyrillic letter (see [here](http://www.fileformat.info/info/unicode/char/0424/index.htm)). ASCII definatly can't represent cyrillic letter, only extensions like [ISO 8859-5](https://de.wikipedia.org/wiki/ISO_8859-5).

**Comment by bwbeach** [comment]
I don't think it implies UTF-16 encoding; that's just how Python represents unicode strings when you call `repr`.  Printing that string works for me.  It might be worth trying it yourself:

```$ python
Python 3.5.4 (default, Sep 22 2017, 08:33:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> u'Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0444\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b'
'Music Stuff/Uncompressed WAVs/Фонограммы/фонограммы'
```

(And: No, I'm not suggesting changing it to ASCII.  It would work with UTF-8, and will definitely not work with ASCII.)

**Comment by bwbeach** [comment]
Like I said before, this stuff is annoying...

And you say that `sys.stdout.encoding` is `UTF-8`?

It looks like Python 2.7 is different, and only encodes if you `print` the string:

```$ python
Python 2.7.14 (default, Sep 22 2017, 00:06:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> u'Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0444\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b'
u'Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0444\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b'
>>> print u'Music Stuff/Uncompressed WAVs/\u0424\u043e\u043d\u043e\u0433\u0440\u0430\u043c\u043c\u044b/\u0444\u043e\u043d\u043e\u0433\u0440
Music Stuff/Uncompressed WAVs/Фонограммы/фонограммы
```

**Comment by dima-ser** [comment]
`print u'bla bla'` did work, it decoded the string properly.
So, what does this mean, how do I make it work in b2 tool?

**Comment by bwbeach** [comment]
The only explanation I can come up with is that the Python environment the `b2` command is running in has a different output encoding.  I just submitted pull request #400 to add a little more info to the error message, and the logging about it.  Running with this change might give some clues.

**Comment by dima-ser** [comment]
Thank you @bwbeach. I'm new to open source development, how do I test this, do I need to wait until this gets merged into a release or can I compile and test it myself?

**Comment by bwbeach** [comment]
The `README` on the project has instructions for setting up a development environment.

To just run it, you should be able to clone the repository, go to that directory, and run it as a Python module:

```
$ pwd
/Users/brianb/sandbox/B2_Command_Line_Tool
$ ls
2017-09-25			appveyor.yml			doc				run-unit-tests.sh
LICENSE				b2				empty				setup.cfg
MANIFEST.in			b2.egg-info			pre-commit.sh			setup.py
README.md			ci				requirements-setup.txt		test
README.release.md		contrib				requirements-test.txt		test_b2_command_line.py
__pycache__			dist				requirements.txt		test_b2_command_line.pyc
$ python -m b2 version
b2 command line tool, version 1.1.1
```

**Comment by dima-ser** [comment]
Thanks! So, when I cloned the repo and ran b2 as a python module, it actually displays Cyrillic characters correctly in the output. Not sure if it's been updated now in the latest version (my installed version is 1.1.0, the one I cloned is 1.1.1).

**Comment by bwbeach** [comment]
That's a puzzle.  Maybe the installed version is running in a different Python?

Version 1.1.1 has almost no changes from 1.1.0.

**Comment by dima-ser** [comment]
The tool is being called from a cron job under root. After more testing, I found out that if I call it interactively from my terminal, it works fine. So, it's got to be the environment. I added the $LANG and python --version checks in the script to compare it with mine, and the both report the same

```bash
echo $LANG
en_US.UTF-8
python --version
Python 2.7.12
```
Not sure what else to check.

**Comment by bwbeach** [comment]
The only other check I can think of is to have Python tell you what it things the encoding is when running in the cron job:

```
python -c 'import sys; print sys.stdout.encoding'
```

The `PYTHONIOENCODING` variable is the other thing that could affect it.

**Comment by dima-ser** [comment]
Aha! The output of this 
```
python -c 'import sys; print sys.stdout.encoding'
```

in my cron job is this:

```
None
```

In my interactive session it's
```
UTF-8
```

**Comment by dima-ser** [comment]
Update: solved by including

```bash
export PYTHONIOENCODING=UTF-8
```

in my cron script.
