### ISSUE TITLE
Explain Class A, B, C transactions on the website

### ISSUE THREAD

**Issue by PeterNerlich** [Backblaze/B2_Command_Line_Tool#403]
*(This project is not about the web interface, but there is no project or bug tracker for that here so I hope for forwarding and deletion)*

At no point in the web interface (*Caps & Alerts*) or the FAQ I found an explanation of how Class `A`, `B` and `C` transaction are *actually defined*. Only that `A` is free, `C` seems to relate to sync queries (but doesn't match file count or `b2 sync` command execution counts) and I seem to exhaust this almost by trying around a bit (e.g. for #402) and `B` gives me the first 2,500 for free as well, just that it seems to be untouched for now and might relate to download.

It seems incredible to me how this didn't pop up at least in the FAQ already, since without explanation it seems to be an arbitrary choice.

**Comment by nilayp** [comment]
Transactions groups by class are available from the Backblaze B2 pricing page: https://www.backblaze.com/b2/b2-transactions-price.html

**Comment by svonohr** [comment]
As for B2 CLI the sync command uses `b2_list_file_versions` to get a list of remote files. This should cost one class C transaction for every 1000 file versions in the bucket. If your experiments already exhausted the 2500 free queries you probably have a lot of files in the bucket.

**Comment by PeterNerlich** [comment]
Ah, okay, this explains it a bit. Yes, it's a full backup of my personal files (including programming stuff, Pictures and Videos) currently summing up to 384,562 files taking up 600 GB in the bucket. I wrote a bash backup script that backs up various subdirs (because priorities):

    ...
    doB2 $H/Documents "'(^programming/Asterisk/test/.*)'"
    
    doB2 $H/.config
    doB2 $H/Todo
    doB2 $H/.thunderbird
    doB2 $H/OBS
    doB2 $H/.local
    doB2 $H/Templates
    doB2 $H/ "'(^.*/.*)'"
    
    doB2 $H/Music
    doB2 $H/Pictures
    doB2 $H/Videos
    doB2 $H/Games
    doB2 $H/.minecraft

You see, the function will have executed a `b2` command a total of 13 times. Or is there a better way to do this? I don't want to loose the ability to exclude dirs like `programming/Asterisk/test` by excluding *everything* and then including again what I do want to back up. Though, of course, I could, with the current configuration, compress this down to two calls (or three, keeping the main priority blocks).

**Comment by svonohr** [comment]
When you sync to a folder inside your bucket, e.g., `b2://mybucket/test`, the B2 CLI does not list all files in the bucket, but only those files inside the `test` folder. So splitting your sync into 13 calls does not result in 13x the `b2_list_file_versions` calls, but only a maximum of 12 additional calls.

**Comment by bwbeach** [comment]
Closing.  Let us know if you have further questions.
