### ISSUE TITLE
--excludeDirRegex does not work when source is B2

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#419]
The new filtering that lets you exclude an entire directory works in the `LocalFolder` class, but not the `B2Folder` class.

I think there are two possible approaches to fixing it: (1) change B2Folder to simulate the existence of directories, and check them for exclusion, or (2) extend `ScanPoliciesManager.should_exclude_file` to also test whether any of the directories in the path are excluded.  I like #2, but I think it would need optimization to avoid checking every parent directory of every file.

**Comment by ppolewicz** [comment]
To do this right, we should use `startFileName` parameter accordingly while running `b2_list_file_names`, this way someone may sync down a bucket without a large chunk in the middle, saving the C transactions on listing. When we'd run into a directory that should be skipped and it doesn't end within the currently processed `b2_list_file_names` chunk, then we'd skip to the next "directory".

But... does anyone actually need it?

**Comment by bwbeach** [comment]
I agree with the optimization you suggest.  Not sure how much this feature would be used.  If the CLI could use the prefix matching that the API provides, that would be another way to save calls.

I'd like to start with correctness, then optimize it.

**Comment by ppolewicz** [comment]
I'd like to suggest that we hold off the implementation until at least a couple of potential users are identified. There are many other areas that need attention more than this one (unless it bothers you personally, like it was with `sync.py` in my case, ha ha).

**Comment by bwbeach** [comment]
It bothers me that it's incorrect.  People might start using `--excludeDirRegex`, and then expect the current behavior to continue.
