### ISSUE TITLE
When will b2_create_key be available?

### ISSUE THREAD

**Issue by uj** [Backblaze/B2_Command_Line_Tool#421]
Does anyone know when b2_create_key will be available in the b2 api?
https://www.backblaze.com/b2/docs/b2_create_key.html

It says "coming soon", whatever timeframe that implies I don't know.  Sometimes there is a developer or beta option to enable pre-release features in an API for testing before they are official.  Does b2 offer anything like that?

**Comment by bwbeach** [comment]
Backblaze has not announced a release date.

This question is not about the command-line tool, and this is not the right forum.  Closing.
