### ISSUE TITLE
B2 SYNC stopped working

### ISSUE THREAD

**Issue by vdellaglio** [Backblaze/B2_Command_Line_Tool#422]
b2 sync no longer works, I already re-installed python and b2 command line.

I am getting this:

> C:\Users\Administrator>b2 sync D:\BACKUP b2:/bucketname
> ERROR:b2.console_tool:ConsoleTool command error
> Traceback (most recent call last):
>   File "c:\python27\lib\site-packages\b2\console_tool.py", line 1074, in run_com
> mand
>     return command.run(args)
>   File "c:\python27\lib\site-packages\b2\console_tool.py", line 857, in run
>     allow_empty_source=allow_empty_source
>   File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in w
> rapper
>     return function(*wrapee_args, **wrapee_kwargs)
>   File "c:\python27\lib\site-packages\b2\sync\sync.py", line 261, in sync_folder
> s
>     source_folder, dest_folder, args, now_millis, reporter
>   File "c:\python27\lib\site-packages\b2\sync\sync.py", line 149, in make_folder
> _sync_actions
>     sync_type, source_file, dest_file, source_folder, dest_folder, args, now_mil
> lis
>   File "c:\python27\lib\site-packages\b2\sync\sync.py", line 106, in make_file_s
> ync_actions
>     for action in policy.get_all_actions():
>   File "c:\python27\lib\site-packages\b2\sync\policy.py", line 123, in get_all_a
> ctions
>     if self._should_transfer():
>   File "c:\python27\lib\site-packages\b2\sync\policy.py", line 52, in _should_tr
> ansfer
>     return self.files_are_different(self._source_file, self._dest_file, self._ar
> gs)
>   File "c:\python27\lib\site-packages\b2\sync\policy.py", line 100, in files_are
> _different
>     dest_file, source_file, cls.DESTINATION_PREFIX, cls.SOURCE_PREFIX
> DestFileNewer: source file is older than destination: local://APPS01/01022018/WE
> B/Candidato/assets/images/upload/ft_curriculo/00848688562_3x4.jpg with a time of
>  1517409644776 cannot be synced to b2://APPS01/01022018/WEB/Candidato/assets/ima
> ges/upload/ft_curriculo/00848688562_3x4.jpg with a time of 1520947532000, unless
>  --skipNewer or --replaceNewer is provided
> ERROR: source file is older than destination: local://APPS01/01022018/WEB/Candid
> ato/assets/images/upload/ft_curriculo/00848688562_3x4.jpg with a time of 1517409
> 644776 cannot be synced to b2://APPS01/01022018/WEB/Candidato/assets/images/uplo
> ad/ft_curriculo/00848688562_3x4.jpg with a time of 1520947532000, unless --skipN
> ewer or --replaceNewer is provided
> 

The issue is not with the files from the output, the sync no longer works with any new object.

Running the command with the --dryRun I get this:

> C:\Users\Administrator>b2 sync --dryRun D:\BACKUP b2://bucketname
upload APPS01-FULL/10032018.rar
upload APPS01-FULL/11032018.rar
upload APPS01-FULL/12032018.rar
upload APPS01-FULL/13032018.rar
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1074, in run_com
mand
    return command.run(args)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 857, in run
    allow_empty_source=allow_empty_source
  File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in w
rapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 261, in sync_folder
s
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 149, in make_folder
_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_mil
lis
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 106, in make_file_s
ync_actions
    for action in policy.get_all_actions():
  File "c:\python27\lib\site-packages\b2\sync\policy.py", line 123, in get_all_a
ctions
    if self._should_transfer():
  File "c:\python27\lib\site-packages\b2\sync\policy.py", line 52, in _should_tr
ansfer
    return self.files_are_different(self._source_file, self._dest_file, self._ar
gs)
  File "c:\python27\lib\site-packages\b2\sync\policy.py", line 100, in files_are
_different
    dest_file, source_file, cls.DESTINATION_PREFIX, cls.SOURCE_PREFIX
DestFileNewer: source file is older than destination: local://APPS01/01022018/WE
B/Candidato/assets/images/upload/ft_curriculo/00848688562_3x4.jpg with a time of
 1517409644776 cannot be synced to b2://APPS01/01022018/WEB/Candidato/assets/ima
ges/upload/ft_curriculo/00848688562_3x4.jpg with a time of 1520947532000, unless
 --skipNewer or --replaceNewer is provided
ERROR: source file is older than destination: local://APPS01/01022018/WEB/Candid
ato/assets/images/upload/ft_curriculo/00848688562_3x4.jpg with a time of 1517409
644776 cannot be synced to b2://APPS01/01022018/WEB/Candidato/assets/images/uplo
ad/ft_curriculo/00848688562_3x4.jpg with a time of 1520947532000, unless --skipN
ewer or --replaceNewer is provided

Any help is welcome, my off-site backup is stopped now.

**Comment by svonohr** [comment]
As it says in the error messsage, B2 sync encountered a file where the destination is newer than the source. You have to use either the `--skipNewer` or `--replaceNewer` option to continue. Or you somehow fix the timestamps of your files, so that all source files are older or the same age as the files on the destination.

**Comment by ppolewicz** [comment]
There is a file in your b2 bucket uploaded today, while the local file that b2 sync is trying to upload is from 2018-01-31. This should not be possible, the whole sync relies on those timestamps being accurate and some files clearly went back in time, so sync stopped and provided a couple of options to make it work anyway.

Why haven't you added one of those options to your sync invocation as instructed by the error message?

**Comment by vdellaglio** [comment]
As mentioned on the first post, the files I am having issues with are not the ones from the output.

Here is an example:

one backup folder:

>  Directory of D:\BACKUP\SQL-SEMANAL
> 
> 03/04/2018  02:35 AM           219,858 company1_backup_semanal_20180304_010000.rar
> 03/11/2018  02:35 AM           225,042 company1_backup_semanal_20180311_010000.rar
> 03/12/2018  10:19 AM           123,541 New Text Document.txt
> 02/11/2018  02:36 AM       139,857,626 company2_backup_semanal_20180211_010000.rar
> 02/18/2018  02:36 AM       140,069,050 company2_backup_semanal_20180218_010000.rar
> 02/25/2018  02:36 AM       140,344,429 company2_backup_semanal_20180225_010000.rar
> 03/04/2018  02:36 AM       140,817,142 company2_backup_semanal_20180304_010000.rar
> 03/11/2018  02:36 AM       141,220,277 company2_backup_semanal_20180311_010000.rar
> 
>                8 File(s)    702,876,965 bytes

And now the contents of the folder in Backblaze:

> b2 ls bucketname SQL-SEMANAL/
> SQL-SEMANAL/company1_backup_semanal_20180304_010000.rar
> SQL-SEMANAL/company2_backup_semanal_20180211_010000.rar
> SQL-SEMANAL/company2_backup_semanal_20180218_010000.rar
> SQL-SEMANAL/company2_backup_semanal_20180225_010000.rar
> SQL-SEMANAL/company2_backup_semanal_20180304_010000.rar

Why is it not syncing the newer files here? 

Thanks again!

**Comment by ppolewicz** [comment]
Because it realized the filesystem is not "syncable" - some files are newer on the destination than at the source. This situation is usually triggered by mis-configuration of your backup scripts, where several machines target the same bucket accidentally. In order to prevent potential corruption of the backup destination, `b2 sync` stops as soon as it notices that something is wrong, giving the instructions on how to proceed if the situation is expected.

**Comment by bwbeach** [comment]
Closing.  Please re-open if using one of the `--skipNewer` or `--replaceNewer` flags does not work.
