### ISSUE TITLE
Test suite failing if run as root (inside docker container)

### ISSUE THREAD

**Issue by anjos** [Backblaze/B2_Command_Line_Tool#427]
I'm trying to build a conda package out of this project. The builds work fine on OSX, for both python 2.7 and 3.6, but I'm stuck with the test suite on Linux (tested via a docker container based on continuumio/conda-concourse-ci:latest). Errors repeat for any of these two versions of Python. The following error occurs:

```text
+ nosetests test/test_account_info.py test/test_b2http.py test/test_base.py test/test_bucket.py test/test_console_tool.py test/test_download_dest.py test/test_exception.py test/test_parse_args.py test/test_policy.py test/test_progress.py test/test_sync.py test/test_sync_report.py test/test_utils.py
...............................................................................
WARNING: Unable to print unicode.  Encoding for stdout is: '<MagicMock name='mock.encoding' id='140584093796280'>'
Trying to print: ('Using http://production.example.com',)
............................................................F.............................................................
======================================================================
FAIL: test_invalid_permissions (test.test_sync.TestLocalFolder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/miniconda/conda-bld/b2_1521727913797/test_tmp/test/test_sync.py", line 103, in test_invalid_permissions
    self.assertEqual(self.NAMES[1:], list(f.name for f in folder.all_files(self.reporter)))
AssertionError: Lists differ: ['hello.', 'hello/a/1', 'hello/a/2', 'hello/b', 'hello0', '自由'] != ['.dot_file', 'hello.', 'hello/a/1', 'hello/a/2', 'hello/b', 'hello0', '自由']

First differing element 0:
'hello.'
'.dot_file'

Second list contains 1 additional elements.
First extra element 6:
'自由'

- ['hello.', 'hello/a/1', 'hello/a/2', 'hello/b', 'hello0', '自由']
+ ['.dot_file', 'hello.', 'hello/a/1', 'hello/a/2', 'hello/b', 'hello0', '自由']
?  +++++++++++++


----------------------------------------------------------------------
Ran 201 tests in 1.037s

FAILED (failures=1)
```

Is this a known problem?

**Comment by anjos** [comment]
I think I understand what is happening: the test assumes that by doing `chmod 0 .dot_file`, the user will not be able to read this file. Inside a docker container though, one is typically root - so the test fails. My impression is that `os.access(local_path, os.R_OK)` on `b2.utils`, line 176 is resolving to True, despite the chmod operation done on the test suite. Maybe a better test would be to use `os.stat` instead and check if the permission is literally set on the file.

How to reproduce this issue? Just execute the test with root permissions:

```sh
$ sudo nosetests -sv test.test_sync.TestLocalFolder
```

I printed the result of both `os.access` and `os.stat`:

```text
root: INFO: os.access(/tmp/tmpxcsuggyl/.dot_file, os.R_OK) == True
root: INFO: os.stat(/tmp/tmpxcsuggyl/.dot_file).st_mode == 0o100000
```

As you can see, on the relevant test, because the user is `root`, `os.access` will pass even if the file does not have any read permissions.

**Comment by anjos** [comment]
This patch should fix this issue:

```diff
diff --git a/b2/utils.py b/b2/utils.py
index 9a7be8c..987517d 100644
--- a/b2/utils.py
+++ b/b2/utils.py
@@ -12,6 +12,7 @@ from __future__ import division, print_function

 import hashlib
 import os
+import stat
 import platform
 import re
 import shutil
@@ -173,7 +174,7 @@ def is_file_readable(local_path, reporter=None):
         if reporter is not None:
             reporter.local_access_error(local_path)
         return False
-    elif not os.access(local_path, os.R_OK):
+    elif not os.stat(local_path).st_mode & (stat.S_IRUSR|stat.S_IRGRP|stat.S_IROTH):
         if reporter is not None:
             reporter.local_permission_error(local_path)
         return False
```

**Comment by bwbeach** [comment]
What if the test is wrong and the code was right?

What behavior do we want when running as root?  I think that if I were using the tool, I would expect to be able to back up all files, even those those files don't have read access.

What about the case where I'm running as user A, the file is owned by user B, and the mode is S_IRUSR.  I don't have read access to the file, but the new code will see the read-by-owner bit and think it's readable.
