### ISSUE TITLE
Add get-file-info-by-name command.

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#440]
The quickest and cheapest way to get information about a file is to use a `HEAD` request on the URL that downloads a file by name.  This is faster that getting the file info using `b2_get_file_info` and the file ID.  (The B2 internals are optimized for accessing files by name, which is the most common use case.)

It would be nice to have a `get-file-info-by-name` option in the command-line tool that returns the same information as `get-file-info` for the most recent version of a file with a given name.  It should use a `HEAD` request for the download-by-name API, which means that hidden files will get a 404 and will look like they're not there.

**Comment by mjurbanski-reef** [comment]
New command fulfilling this request has been merged (https://github.com/Backblaze/B2_Command_Line_Tool/pull/959/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R81 ) into B2 CLI and will be out in the next minor release (i.e. `b2>3.13`).

Example usage:
```
b2 file-info b2id://fileId
b2 file-info b2://bucket/fileName
```
