### ISSUE TITLE
Large file download speed improvement

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#450]
Over the next few weeks I am going to implement a major change to how files are downloaded by B2 CLI.

Currently, if the user has large latency, his (single threaded) download speed is constrained by that. We want B2 CLI users to be able to download large files (such as backup snapshots, can be terabytes in size) effectively even on high-latency connections.

The points that need to be considered, are:
- CPU consumption cost increase (important for embedded devices)
- memory cost increase
- I/O cost. Some of our users have higher latency to their hard drive, than to the B2 server and we should not make the situation much worse to them
- possible impact on small-file downloads
- possible impact on minimum storage size. An approach which downloads parts of the file into separate files on disk, to only stitch them up in the end, can make it impossible to download a 1GB file to a filesystem which has less than 2GB free space for the duration of the download
- platform compatibility (some low-level operations are not available on some operating systems
- hashing needs to be taken care of differently. Ideally, we would not delay the hashing until the file is downloaded completely. Also, additional I/O operations for hashing should be avoided if possible.
- users should be able to disable the new algorithm, tweak the number of used threads etc
- the cost of running the download in parallel, in terms of B2 transactions, should be reasonable
- generally we should avoid a situation where with the release of this version with this feature implemented, something gets severely broken and requires downgrade to a non-major version. We should change the default behavior only in the major version
- python version. For now we support python 2.6, which makes many things hard. Perhaps it is time to consider dropping it? RHEL6 Extended Update Support ends 2018-12-31, but Centos 6 is going to be maintained until 2020-11-30. On the other hand, Python team has abandoned 2.6 with "With its release on October 29, 2013, all official support for Python 2.6 has ended. Python 2.6 is no longer being maintained for any purpose." and that was almost 5 years ago and we have more severe issues with dependencies dropping 2.6, so it might be the time to let it go
- platform compatibility. Each operating system handles things differently. Ideally the design would be consistent across platforms, but an approach that delivers higher performance with separate implementations for different systems might be preferable
- restarting downloads needs to be considered, both due to an exception/process termination and due to a crash. Things will not go as planned and we need to be able to tell what happened
- server-side resources should be conserved if possible by optimistically aligning the threads to (guessed) chunk boundaries. Each part can be anywhere from 5MB to 5GB, so we should at least align to 5MB, but default for B2 CLI is 100MB, so if possible, we should align to that
- in a high-latency setting, the speed per thread raises slowly. Very small chunks will not improve speed.
- progress reporting should be supported
- if something goes wrong during download, b2 CLI should crash rather than hang forever
- the solution should be tested

Design A:

Run the first request with a limit of, say, 100MB and check the return status code. If the response status 200 OK, then we got the whole file already. If the response status is 206, then we could run a HEAD request to check the file size (Content-Length) and then schedule more requests for specific file ranges... However, if the connection is very slow, the first 100MB would need to stay with the first thread. The download speed plotted against the file size would vary greatly around the 100MB boundary (or other, but still artificially constant). 102MB files would behave erratically.

Design B:

Run the first request without limit, but implement a stream receiver object which would raise an exception to stop the first thread when we realize the file is large enough (or that the download is slow enough) to spawn more threads. The first connection would need to be kept alive to keep the advantage of ramping up the speed since the start. The major concern here would be handing small chunks of a stream directly in python, consuming CPU... but the existing implementation already does this for progress reporting and nobody has ever complained, so it might not be an important issue. To be on the safe side, we can raise the chunk size from 4KB to decrease the update frequency of progress reporting and save CPU. Users probably don't need the progress bar to be updated every 4KB anyway.

I am strongly leaning towards Design B. Comments are welcome.

**Comment by bwbeach** [comment]
That would be a help even for single-threaded downloads (one per file).  Multiple files could be downloaded in parallel.

**Comment by ppolewicz** [comment]
One thread per file has a strong advantage of hasher adding no overhead to the local storage device. I think I have an idea on how to implement the single file download improvement and then continue to build further optimizations on top of it (also covering upload and sync)

**Comment by promethe42** [comment]
@ppolewicz with your changes, `b2 download-file-by-id` is now 10x faster with our setup.
Thank you very much for this!

**Comment by ppolewicz** [comment]
Thanks @promethe42! Can I ask what your setup is (so that I can understand what changes to plan for the future)?

**Comment by promethe42** [comment]
We use GitLab CI to build our binaries/packages. Most are in the 100s of MBs. One of them is a large Docker container ~4GB. Anyway we use B2 to upload/store/download those CI artifacts.

AFAIK our bandwidth is still not used at 100% by `b2` but it is already a huge improvement.

It would be cool if we could specify the number of download threads.

**Comment by ppolewicz** [comment]
The performance improvement has been tested on i5-6600K CPU, with 8 threads it has bottlenecked the strongest download connection I could find in the range of 30km from where I live. It would seem that I am as far away from the B2 datacenter as I can be (latency-wise).

You are probably using a VM based on some a server with a 2.5GHz clocked, relatively cheap datacenter CPU. What I have not taken into account when setting the maximum number of threads, was that my CPU may perform significantly better than the CPU of the machine that executes the download.

Settable thread count is on the TODO list, however implementation-wise, we want to move all transfer operations into the new _transferer_ module and set the thread count there consistently across all b2 cli commands. There are also other configuration parameters that can be set for downloads, such as minimum chunk size, which is currently set to 100MB, but maybe you'd like to set it to a smaller value to use parallel downloads better even on the smaller binaries/packages. I guess since this is a CI build, you don't really need progress reporting (which is relatively CPU intensive, if you ask me), so letting you set a larger internal chunk size would optimize your CPU load... since large files are not currently comparing hashes on download, we could probably skip hashing too, save lots of CPU and a few more seconds of download time caused by re-reading chunks 2 to N... and so on. There are many configuration options for people who like them.

**Comment by ppolewicz** [comment]
Could you please check the maximum download speed in your environment? My test on VM based on i5-6600K with 4GB RAM and a single consumer-grade SSD managed to pump 250Mbps hitting a network bottleneck with quite a lot of cpu to spare.

It kind of seems that the server in question has a network port with link capped to 10Mbps.

**Comment by promethe42** [comment]
Prometheus tells me the same server can have at least 6x more bandwidth. And the vendor guarantees a 100Mbps bandwidth. 

I'll try to run more tests locally. I can't really toy around with a CI server :)
