### ISSUE TITLE
Mark description content-type as Markdown

### ISSUE THREAD

**Issue by florisla** [Backblaze/B2_Command_Line_Tool#460]
To solve this code comment question:

https://github.com/Backblaze/B2_Command_Line_Tool/blob/3d9eefefb11efa1680b8c143f6dca4b5b9afb230/setup.py#L36

You can include `long_description_content_type = 'text/markdown'`, as described here: 
https://packaging.python.org/guides/distributing-packages-using-setuptools/#description (example [here](https://github.com/pypa/sampleproject/blob/master/setup.py)).

That will fix the layout of the description on PyPI.

**Comment by bwbeach** [comment]
The fix looked right to me, but it doesn't work.  :-(

**Comment by florisla** [comment]
Did you update `setuptools` before making the sdist or wheel? This is only supported from very recent setuptools (v40 I believe).

Normally you can extract the `.whl` file as a zip archive and look at the `METADATA` file to see if it looks ok.

**Comment by bwbeach** [comment]
Good catch.  I get this warning that I missed last time when it scrolled by quickly:

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
```

**Comment by florisla** [comment]
Note, according to this article, you need a recent `setuptools` to make this work, but *also* a recent `twine` to do the upload to PyPI.

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

I see twine is not listed in requirements-setup.txt`.

**Comment by bwbeach** [comment]
Adding twine to the list seems like a good idea anyway.
