### ISSUE TITLE
pip Installation failures - mac OSX default python version 2.x 

### ISSUE THREAD

**Issue by spartan218** [Backblaze/B2_Command_Line_Tool#469]
Mac ships with a default version of Python 2.x in (/System/Library/Frameworks/Python.framework/Versions/xx).

It was recently discovered that the mac default OSX installation of Python (which tends to be version 2.x) has issues when running the install command for b2. This is because pip uses Python packages to install b2 and it does not have access to the directories/packages of the default Python.

Whats broken:
`sudo pip install --upgrade b2`
The fix for this previously used to be to run 
`sudo pip install --upgrade --ignore-installed b2`

However even with the --ignore flag, the upgrade continues to fail because of permissions issues when using the Apple version of Python libraries.

ERRORS such as the following:
`Command "python setup.py egg_info" failed with error code 1 in /private/tmp/`
`Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/man'`

Potential work arounds:
- Using HomeBrew
1) install HomeBrew (which requires XCode for macOS)
2) install the version of Python you want (brew install python or brew install python2)
**Note: when using HomeBrew to install Python it comes with the corresponding pip**
python 2.x -> pip
python 3.x -> pip3
3) Run the pip install command as specified
`sudo pip install --upgrade b2` (for Python 2.x)
`sudo pip3 install --upgrade b2` (for Python 3.x)

- Use Macports to install Python

Resources:
FileSystemProtection - https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/FileSystemProtections/FileSystemProtections.html
Using Pip with new OSX - https://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade/223163#223163

**Comment by ppolewicz** [comment]
Perhaps you could also use virtualenv

**Comment by lattmongoria** [comment]
I'm experiencing this issue. I get the error setuptools 20.2 or later is required, but I have setuptools-44.0.0 installed. Shouldn't that meet the requirement?

**Comment by ppolewicz** [comment]
Try virtualenv, it should fix the problem

**Comment by ppolewicz** [comment]
python2 was dropped a long time ago now
