### ISSUE TITLE
Refactor ConsoleTool

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#47]
- [x] eliminate `message_and_exit` in favor of exceptions
- [ ] ~~use a decorator to pretty print results as json~~
- [x] improve option parsing (use `optparse`? We can't use `argparse` due to RHEL6 not having it)
- [x] generate help messages through the refactored option parsing
- [x] move remaining v0.3.x functions to a class

**Comment by bwbeach** [comment]
There is a [backport of the arg parse](https://pypi.python.org/pypi/argparse) that's supposed to work on 2.6.  Maybe that's the way to clean up the arg parsing.

**Comment by bwbeach** [comment]
I tried setting up argparse for two of the b2 commands, and I'm not very happy with the help text that argparse provides:

    $ b2 -h create_bucket
    usage: b2 [-h] {create_bucket,authorize_account} ...

    Command-line tool that provides access to the Backblaze B2 service.

    positional arguments:
      {create_bucket,authorize_account}
        create_bucket       Creates a new bucket. Prints the ID of the bucket
                            created.
        authorize_account   Prompts for Backblaze accountID and applicationKey
                            (unless they are given on the command line). The
                            account ID is a 12-digit hex number that you can get
                            from your account page on backblaze.com. The
                            application key is a 40-digit hex number that you can
                            get from your account page on backblaze.com. Stores an
                            account auth token in ~/.b2_account_info

    optional arguments:
      -h, --help            show this help message and exit

    $ b2 create_bucket -h
    usage: b2 create_bucket [-h] bucketName {allPrivate,allPublic}

    positional arguments:
      bucketName
      {allPrivate,allPublic}

    optional arguments:
      -h, --help            show this help message and exit

What I'd rather see is a summarized list of commands and arguments, with details when you pick one:

    $ b2
    Usage: b2 <command> <options>

        b2 authorize_account [accountId] [applicationKey]
        b2 create_bucket [bucketName] [bucketType]

    $ b2 create_bucket
    Usage: b2 create_bucket [bucketName] [bucketType]

        Creates a new bucket.  The name must be ..., and the bucket
        type should be either allPublic or allPrivate.

**Comment by bwbeach** [comment]
I just push up a branch called "args" with an alternate approach that prints usage messages I like.
