### ISSUE TITLE
Consider adding a bash completion script to this repo

### ISSUE THREAD

**Issue by mapio** [Backblaze/B2_Command_Line_Tool#49]
I've written an (almost complete) bash completion script for b2 https://gist.github.com/mapio/67eb007b2f995b708759 I'll be glad if you want to consider it for inclusion in this repo.

**Comment by ppolewicz** [comment]
Could you please create a pull request for it?

**Comment by mapio** [comment]
Of course… where do you want me to put it (I mean do you want it in the repository root, or do you prefer an alternative directory)?

**Comment by ppolewicz** [comment]
I don't know where such things are usually put - you seem to be much more experienced in creating those :) Could you recommend something that is usually used in such situations?

It would be very nice if you could also share some information about installation of the thing for the user.

**Comment by mapio** [comment]
I did it… feel free to edit the `README`  and move the code as you feel suitable.
