### ISSUE TITLE
Unexpected error 'incident id' calling b2_upload_part via API

### ISSUE THREAD

**Issue by mattdwen** [Backblaze/B2_Command_Line_Tool#506]
I know this isn't CLI related, but Backblaze are saying they can't provide API support and I should post on Github.

I have a C# based implementation which is successfully backing up regularly to B2, including large files.

At August 30th 2018, 23:08:40 UTC, a large file part upload failed, with a properly formatted B2 JSON error, with the message:

`incident id edc7712711ba-0501b3f37f9d`

Unfortunately the logging did not record the code or status, but that was the message.
The file was successfully backed in the next attempt an hour later.

The API often returns odd errors, but `incident id` sounds particularly ominous, hence my enquiry to Backblaze support. Unfortunately there only response has been they cannot provide support to my "my code".

I was hoping someone could provide some insight onto this message, and whether or not the part upload should be retried immediately (with a new b2_get_upload_part_url call?), or if the whole file should be abandoned and re-uploaded?

**Comment by bwbeach** [comment]
That’s a 500 error.  When you get an error on in range 500 - 599, you should get a new upload URL and try again. (See the “Uploading” page in the docs.)

The incident id is for internal use tracking internal errors.  We’ll take a look, see what happened, and get it fixed. Meanwhile, retrying the upload worked, as expected.

**Comment by mattdwen** [comment]
Thanks @bwbeach, appreciate the quick response!

**Comment by madroach** [comment]
I got an incident id, too: `ad58f8e66711-6e4119d9ae496828`.
This rarely happens to me when trying to download several small files over the same connection.
