### ISSUE TITLE
Broken symlink returns warning but stops sync.

### ISSUE THREAD

**Issue by AlexanderProd** [Backblaze/B2_Command_Line_Tool#517]
When I'm running the b2 sync script without any arguments except for the thread count I'm getting this error. It ran perfect for a while though. 

I'm using version 1.3.6 installed using pip3 

```
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/fsevents/node_modules/.bin/node-pre-gyp could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/node-pre-gyp/node_modules/.bin/needle could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/node-pre-gyp/node_modules/.bin/detect-libc could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/node-pre-gyp/node_modules/.bin/nopt could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/svgo/node_modules/js-yaml/node_modules/.bin/esvalidate could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-spa/node_modules/svgo/node_modules/js-yaml/node_modules/.bin/esparse could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/fsevents/node_modules/.bin/node-pre-gyp could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/node-pre-gyp/node_modules/.bin/needle could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/node-pre-gyp/node_modules/.bin/detect-libc could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/node-pre-gyp/node_modules/.bin/nopt could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/svgo/node_modules/js-yaml/node_modules/.bin/esvalidate could not be accessed (broken symlink?)
WARNING: /Users/alexanderhoerl/Developer/react-upload/node_modules/svgo/node_modules/js-yaml/node_modules/.bin/esparse could not be accessed (broken symlink?)
```

After this the program stops.

**Comment by AlexanderProd** [comment]
I've also tried `--excludeDirRegex '(node_modules)'` to escape the node modules since all of the broken symlinks seem to be in one of those. But its still happening.

**Comment by ppolewicz** [comment]
Could you please run the sync with [detailed logs](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs)? Those warnings work as intended, but it seems strange that the sync has stopped.

**Comment by AlexanderProd** [comment]
@ppolewicz Unfortunately I can't prove detailed logs at the moment because I deleted the broken symlinks so I could resume the sync process. But I going to provide them if it happens again.

**Comment by dcowan-london** [comment]
HI, I've been having the same issue.

With `--verbose`, after the `WARNING`s, I just get `INFO:__main__:\\ ========================================  exit=0  ======================================== //`, then it exits

**Comment by ppolewicz** [comment]
It would appear that you've already synced everything (except for the broken symlinks). Isn't that the case? To test this you could create a file such as `ZZZZ` and then run the sync again with debug to see if it will be uploaded.

**Comment by mjurbanski-reef** [comment]
Please reopen if the problem still occurs with the current version. When reporting it, please attach [detailed logs](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-log) that way we can reduce back-and-forth and thus solve the issue together faster. The most important information here would be if sync indeed did not complete. Warnings should not stop the process, and seeing how process produced multiple of them indicates that was the case.

**Comment by mjurbanski-reef** [comment]
An important piece of information for the user: these Warnings are printed at the end of the process by design.
