### ISSUE TITLE
authorise_account - Account ID

### ISSUE THREAD

**Issue by marcobarriosfi** [Backblaze/B2_Command_Line_Tool#520]
When using the authorize_account command, the CLI requests for Account ID and Application Key. However, if I have created an Application Key that is only authorised to access a specific bucket, I should enter an Application Key ID instead of my Account ID. Perhaps this could be clarified. I tested this with version 1.10 so if this has changed since, please ignore my feedback.

**Comment by winduptoy** [comment]
Scratching my head for a while until I found this issue...

**Comment by ppolewicz** [comment]
This was fixed an unknown amount of time ago. Current version is 3.0.2 and it asks for `applicationKeyId` and `applicationKey` - this is a case for longer than I can remember. Anyway, we can close this issue as fixed now.
