### ISSUE TITLE
Upload speed is steadily decreasing

### ISSUE THREAD

**Issue by AlexanderProd** [Backblaze/B2_Command_Line_Tool#521]
Whenever I start uploading a bunch of files using this [script](https://gist.github.com/AlexanderProd/cb645cf858fd5c89780e7df267226b80) I start with a normal speed of around 1Mb/s (normal for my connection) but it is steadily decreasing until I stop the script and restart it. I'm sure its not a problem with my connection. 

This is pretty annoying when uploading large amounts of data because after 1 hour or so I'm at about 500Kb/s speed and I have to restart the script. 
Does anyone els experience this? 

I'm using version 1.3.6 installed with pip on macOS Mojave.

**Comment by ppolewicz** [comment]
This is a tough one.

Please run `top` in your console when the slowdown occurs, press `1` to enable detailed CPU view and show us the top of the output (until the line which has `PID USER PR` etc, we don't need to see anything below it)

**Comment by AlexanderProd** [comment]
Nothing changes when I press `1` after running `top` also I don't have a line saying `PID USER PR`

This is the top of the `top` output.
```
Processes: 390 total, 2 running, 1 stuck, 387 sleeping, 1640 threads                                                                                                                                       16:44:35
Load Avg: 2.11, 2.07, 1.98  CPU usage: 11.19% user, 8.92% sys, 79.88% idle   SharedLibs: 230M resident, 58M data, 20M linkedit. MemRegions: 73031 total, 2082M resident, 94M private, 906M shared.
PhysMem: 8122M used (1941M wired), 68M unused.  VM: 3856G vsize, 1313M framework vsize, 268604(0) swapins, 296887(0) swapouts. Networks: packets: 386193/360M in, 252255/205M out.
Disks: 478939/8145M read, 187887/3649M written.
```

 Also I have noticed the speed normally isn't dropping below 500Kb/s. Also after starting the script i sometimes start with an upload speed that is way higher than what I can get from my ISP.  
I suspect the speed indicator just takes some time to adjust and its about the same speed all the time.

**Comment by ppolewicz** [comment]
Ok, this is a very tough one. Looks a bit like ISP-level or router-level QoS, except that the speed reduction is gradual, which is not typical for router-level QoS possible settings that I have seen so far.

Do you experience slowdowns during downloads too?

Could you please start a `ping` process, observe latency before uploading and then see how the latency behaves during the upload? Is the latency during the slowdown higher or lower than the latency during the initial ("fast") period?

Can you make a targeted tcpdump? It's all encrypted, but we can see some patterns in the traffic.

**Comment by AlexanderProd** [comment]
I couldn't test it anymore since the last time I've ran the script the speed was realistic from the start on.

> Do you experience slowdowns during downloads too? 
I've not used the b2 cli tool for downloads yet. 

I'm going to perform the test when I notice a slowdown again.

**Comment by AlexanderProd** [comment]
Closing because the problem didn't occur anymore and it seems it wasn't part of the CLI tool.
