### ISSUE TITLE
exclude regex syntax

### ISSUE THREAD

**Issue by cweinhofer** [Backblaze/B2_Command_Line_Tool#522]
I trying to sync a folder located at 
`"/media/Storage/Central/`" but exclude the directory 
`"/media/Storage/Central/Documents/Symlinks/'`.

I entered the command `b2 sync --delete --excludeDirRegex '^Documents/Symlinks/' /media/Storage/Central/ b2://W2-Backup` but it still synced the `Symlinks` directory.

I'm guessing there is a problem with by syntax (documentation on this -- especially with examples -- has been pretty hard to find), but I'm not sure what. Any help would be appreciated.

**Comment by GlitterCakes** [comment]
I wasn't able to get this to work either. As a side note this tool is pretty awful and you should probably find something else.

**Comment by svonohr** [comment]
I think there is a typo in the documentation:
> [...] so don't include **one** in your regular expression.

**Comment by cweinhofer** [comment]
@ppolewicz Sorry, I accidentally copied the command from one of my earlier attempts. I've tried lots of combinations (as it sounds like this person has: https://github.com/Backblaze/B2_Command_Line_Tool/issues/402)

I did read in the documentation that you referenced about not including the trailing slash and also tried that without success. I also just tried the command you provided, and that didn't work either.

Interestingly, I also tried contacting Backblaze's customer support, but they said they couldn't deal with any technical stuff and just sluffed me off to Github. Seems pretty poor that the company doesn't at least have a page / pages explaining the different options for the CLI with a few examples of each. There's only so much you can provide via terminal help.

**Comment by svonohr** [comment]
I just did some tests and also wasn't able to get the expected result using the command by @ppolewicz. What seems to work is the following command:
`b2 sync --delete --excludeDirRegex '^Documents/Symlinks$' /media/Storage/Central/ b2://W2-Backup`
I've verified this using the current version (1.3.6) and mirroring your folder structure.

**Comment by cweinhofer** [comment]
Thank you @svonohr! This is indeed the syntax I needed.

**Comment by ppolewicz** [comment]
@svonohr since you figured out the proper syntax, could you please adjust the help message?

**Comment by bwbeach** [comment]
I think the confusion comes from this paragraph in the doc, which is unclear:

```
    You can specify --excludeRegex to selectively ignore files that
    match the given pattern. Ignored files will not copy during
    the sync operation. The pattern is a regular expression
    that is tested against the full path of each file.
```

The paths matched are actually relative to the directory being synced, as @svonohr figured out.

**Comment by cweinhofer** [comment]
You may also want to add a note to the paragraph (...path being matched does not have
a trailing '/', so don't include on in your regular expression.) about needing the $ at the end. May be obvious to those familiar with regex, but would be helpful for (and avoid unnecessary question from) regex newbies like me.

**Comment by inspire22** [comment]
It's really confusing that it requires ^ and $, that should be mentioned in the help displayed.
