### ISSUE TITLE
Enhancement: move/rename and copy commands

### ISSUE THREAD

**Issue by gwk** [Backblaze/B2_Command_Line_Tool#525]
I have just read through `b2 help` and see no way to rename file within a bucket, or copy a file from one bucket to another. Is this possible? If not, could it be added in the future? Thank you!

**Comment by bwbeach** [comment]
The B2 service does not have move/rename.  Nor do the other object storage services.

Copy is a frequently requested feature.  If/when Backblaze implements copy, it will also be added to this tool.

**Comment by gwk** [comment]
@bwbeach that is not true: AWS CLI does have a move command. See `aws s3 mv help` for details.

I searched existing issues but did not find anything; if this is really a duplicate then I would appreciate a link to the original so that I can track the issue. Thanks again, -George

**Comment by gwk** [comment]
Is this the wrong repo to be filing this issue against?

**Comment by bwbeach** [comment]
@gwk - You're correct that the AWS CLI does have a "move" command.  S3 does not support moving files, so the CLI does a copy-then-delete.  Once B2 has the ability to copy, then adding a "move" command to the CLI would make sense.

This repo is for the CLI for B2.  For new feature requests in b2, contact Backblaze.

**Comment by ppolewicz** [comment]
Duplicate of #57
