### ISSUE TITLE
503 service_unavailable No uploads available in vault 0001099

### ISSUE THREAD

**Issue by rwky** [Backblaze/B2_Command_Line_Tool#531]
When uploading I'm consistently getting this error after uploading for a while, I contacted support and they said that the b2 cli should retry with another vault but it doesn't, instead it exits with this error:

b2.exception.ServiceError: 503 service_unavailable No uploads available in vault 0001099

**Comment by ppolewicz** [comment]
Could you please run the upload command with `--verbose` flag and show us the output?

**Comment by bwbeach** [comment]
Looks like it's an issue at Backblaze, and that vault is not accepting uploads right now.  There's a policy that large file uploads put the entire file in the same vault, so it's probably not able to finish uploading some large files.

We'll get things fixed on the Backblaze side.

Meanwhile, a workaround would be to re-start large file uploads by doing `b2 cancel-all-unfinished-large-files <bucketName>` and then trying again.

**Comment by rwky** [comment]
:+1: running `b2 cancel-all-unfinished-large-files <bucketName>` solved the problem.
