### ISSUE TITLE
Unable to authorize account on Ubuntu

### ISSUE THREAD

**Issue by nickbasham** [Backblaze/B2_Command_Line_Tool#535]
Hi, I just installed b2 on my server and created and application key with read/write privileges for it, but I'm receiving an "unable to authorize account" error. I've tried several times with two different application keys, double-checking that I was using the correct strings.

Here's my log: [b2_cli.log](https://github.com/Backblaze/B2_Command_Line_Tool/files/2663776/b2_cli.log)

Any help would be greatly appreciated. Thanks in advance!

**Comment by ppolewicz** [comment]
does the key have access to listing buckets?

**Comment by bwbeach** [comment]
Be sure to use the application key ID in place of the account ID in `authorize-account`.  Here's an example of using it.  (I've deleted the key, so this key won't work for you.)

```
$ b2 create-key --duration 3600 test listFiles,readFiles,listBuckets
0018f5033aa08600000000001 K001vDfC2g1YGmwwvViowy+HgMhFQ6U
$ b2 authorize_account 0018f5033aa08600000000001 K001vDfC2g1YGmwwvViowy+HgMhFQ6U

Using https://api.backblazeb2.com
$ b2 list-buckets
...
$
```

**Comment by nickbasham** [comment]
@ppolewicz Yep, I gave that key read/write access to a test bucket.

@bwbeach Ah, that was it, I was using my account ID, not the application key ID. Thanks!

It would be nice if the command prompt was "application key id" instead of "application id", just to avoid this confusion.
