### ISSUE TITLE
No support for listing files in a bucket by prefix

### ISSUE THREAD

**Issue by spantaleev** [Backblaze/B2_Command_Line_Tool#537]
Using the `b2` CLI tool, it's impossible to list files in a bucket by only finding files with a given prefix.

The command signature is:

```
b2 list-file-names <bucketName> [<startFileName>] [<maxToShow>]
```

This may give the impression that supplying a `startFileName` is what one wants in order to filter by a given prefix, but that's not the case.

----------

Moreover, your [How does the startFileName parameter work on the b2_list file_names API?](https://help.backblaze.com/hc/en-us/articles/218975607-How-does-the-startFileName-parameter-work-on-the-b2-list-file-names-API-) article says:

> If you want to get the files and folder structure at the level "cats" the startFileName prefix should be "cats/"

Which appears to be completely wrong.

-------------

This same article contains other weird things as well:

> If you wanted to get the file and folder structure at the level "kittens"
> the startFileName prefix should be "cats/kittens/"

This leads you to believe that `kittens/` is nested inside `cats/`, while the example shows otherwise.

-------------

What appears to work (for finding files with a given prefix) is using the [b2_list_file_names](https://www.backblaze.com/b2/docs/b2_list_file_names.html) API with a `prefix` parameter (not `startFileName`!).

Looking at "API Versions" on that page, it doesn't seem like there had been a change to the semantics of `startFileName` or `prefix` parameters, so I guess what held true in 2016 still holds true now. That is to say, the aforementioned article appears to have been lying to people for 2 years now.

Of course, using the API manually is not convenient at all. Not being able to list files by prefix is a serious deficiency in the `b2` CLI tool.

**Comment by ppolewicz** [comment]
Are you looking for [this](https://github.com/Backblaze/B2_Command_Line_Tool/blob/7746440cbeb95287efdf15202f6f29015fd928bf/b2/console_tool.py#L947)?

**Comment by ppolewicz** [comment]
Thanks! If you think #408 is useful, maybe you could contribute to it?

**Comment by spantaleev** [comment]
Given that `b2 ls` exists, this issue is no longer valid.

There are various other issues:
- having 2 different "listing" ([b2_list_file_names](https://www.backblaze.com/b2/docs/b2_list_file_names.html)) commands (`b2 ls` and `b2 list-file-names`) is not straightforward

- inconsistencies: some commands output JSON, others output plain text or some weirdly formatted tabular data (`b2 ls --long`)

.. but those are separate issues.

---------

As for #408, I don't think I'll have the necessary time to contribute and make it work.

---------

Thank you!
