### ISSUE TITLE
Obscure and Annoying Errors

### ISSUE THREAD

**Issue by JohnRobson** [Backblaze/B2_Command_Line_Tool#540]
```
File "/usr/lib/python2.7/site-packages/b2/bucket.py", line 374, in upload
    validate_b2_file_name(file_name)
  File "/usr/lib/python2.7/site-packages/b2/utils.py", line 168, in validate_b2_file_name
    raise ValueError("file names segments (between '/') can be at most 250 utf-8 bytes")
ValueError: file names segments (between '/') can be at most 250 utf-8 bytes
ERROR:b2.sync.action:an exception occurred in a sync action
```
```
File "/usr/lib/python2.7/site-packages/b2/bucket.py", line 374, in upload
    validate_b2_file_name(file_name)
  File "/usr/lib/python2.7/site-packages/b2/utils.py", line 162, in validate_b2_file_name
    raise ValueError("file names must not contain '\\'")
ValueError: file names must not contain '\
```

Maybe you can handle (try...catch) these errors and just output a warning with the full "file_path/name".

**Comment by bwbeach** [comment]
The fix may be as simple as raising `UnusableFileName` instead of a `ValueError`.  Exceptions that are subclasses of `B2Error` are reported more cleanly, without the ugly stack trace.

**Comment by sirleech** [comment]
I noticed it also throws an exception for the Mac Os Icon file ('Icon?') which has a carriage return in the file name. This may be a common item to fail gracefully, or ignore.

**Comment by mjurbanski-reef** [comment]
Related code is currently being worked on and will be part of next release (b2 4.0) - all "invalid" filenames will be reported as warnings and won't stop sync from continuing.

`b2v3` will report status code 0 (i.e. success) in case of warnings emitted to preserve backwards compatibility where we emitted access-permission warnings, but still reported success
`b2v4` will report status code 1 (fail) in case of any file-access/filename encoding warnings.
