### ISSUE TITLE
Accept authorize-account arguments via environment

### ISSUE THREAD

**Issue by numo68** [Backblaze/B2_Command_Line_Tool#542]
The command line arguments can be visible in the `ps` output revealing sensitive information to untrusted users. As it is not always possible to have someone to type in the credentials interactively it would be nice to have a possibility to specify the application id and key via environment variables such as

`B2_ACCOUNT_ID=001...`
`B2_ACCOUNT_KEY=K001...`

This would be also a perfect way to pass this info into dockerized environments via `--env-file`

**Comment by ppolewicz** [comment]
resolved by #576
