### ISSUE TITLE
This repository will be soon split in half

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#547]
Hi everyone,

currently this repository holds the source code of two distinct projects:
- python client library for b2 cloud with supporting classes
- a CLI tool, which uses thaet client library

Those probably should have been split a long time ago, but that didn't happen. The current plan is to document the client library, put it [here](https://github.com/Backblaze/b2-sdk-python) and document it, so that python software developers can write tools which integrate with b2 with minimum effort.

The plan to do the move is as follows:
- [x] consult the plan with the community
- [x] push the whole code of the CLI to the SDK repository
- [x] remove the CLI from SDK code
- [x] release the SDK on pypi
- [x] remove SDK code from CLI, adding a dependency in the CLI from SDK instead, keeping the SDK classes which were accessible in namespace of the CLI, but providing a warning for anyone who tries to import those directly, so that users will update their dependencies
- [ ] close the SDK-related issues and PRs in the CLI. Their authors will be free to open a new issue in the SDK repository and reference the beginning of the discussion thread
- [ ] while we will be clearing the SDK issues, we will also close most of the stale CLI issues and PRs to clear the tracker from things which are not important, but make management of the project harder. Authors of the closed issues will be free to reopen them, if the issue is still relevant - it may sometimes be difficult for a reviewer to judge whether the problem has dissipated or not, so there will be some mistakes, but that's ok, since reopening can be done in a couple of clicks.
- [x] eventually with a top-version release of the CLI, we will remove the exposure of SDK code in the CLI package. Nobody is in a rush to do this, but eventually it is going to happen.

Please note that the plan does *not* have a stage in which the SDK is already separated, but there is no deprecation warning in the CLI when using the SDK code.

If anyone has a suggestion on how the plan outlined above may be improved, please speak up in the coming days.

**Comment by whitebarry** [comment]
I like this idea a lot. I'm currently working on a thin client for an active project but it does seem very important to have an official standalone python library. Happy to help out any way I can.

**Comment by ppolewicz** [comment]
Hi @whitebarry, we'll need someone to proofread and improve the public API documentation before release, could you help with that?

**Comment by sww1235** [comment]
@ppolewicz I would also be willing to help out. I can certainly proofread as well.

**Comment by whitebarry** [comment]
@ppolewicz Yeah absolutely happy to help on that.

**Comment by jhart-r7** [comment]
Related questions:

1. What is the timeline for this to be complete?  More specifically, when will 1.4.0 be released?
1. Are the plans to backport fixes added to SDK to this client before 1.4.0?  (context is https://github.com/Backblaze/b2-sdk-python/pull/33)

**Comment by ppolewicz** [comment]
@jhart-r7 there are no plans to backport fixes added to SDK to the client before the split release.

The release of CLI after split is very close now, I expect it to happen this week or next week.

**Comment by mjurbanski-reef** [comment]
SDK-CLI split has been done and it was a success :tada:
