### ISSUE TITLE
no server side Move or Copy. Error while suggested on Apps on Desktop recent newsletter.

### ISSUE THREAD

**Issue by Bartmax** [Backblaze/B2_Command_Line_Tool#548]
I was reading [Desktop Apps](https://www.backblaze.com/blog/cloud-storage-made-easy/?utm_campaign=Backblaze-B1C&utm_source=hs_email&utm_medium=email&utm_content=69679715&_hsenc=p2ANqtz-8DyeXk3es_y_I7a-DFGa0p9aLOOwiObCIXQZgAK_HWEl0E6PQ5WR0UPuqeFWNgf28g6bI_GkBK5tBamqAlck4Jlh9z4Q&_hsmi=69679715) that includes rclone as sync capabilities, but without move/rename I don't see how that really works. I get errors like:
```
2019/02/07 17:03:11 ERROR : first.txt: Dir.Rename error: Fs "B2 bucket BartMountTest" can't rename files (no server side Move or Copy)
```

for simple moving a file.

**Comment by bwbeach** [comment]
This repository is for the B2 command-line tool.  We can't address issues about the B2 service.  Nor about rclone.

Copying files is a highly requested feature for the B2 service, and Backblaze may well implement it at some point.  When that happens, we can add it to the command-line tool.
