### ISSUE TITLE
Feature request : Command or option to delete all versions of a file except latest

### ISSUE THREAD

**Issue by whysthatso** [Backblaze/B2_Command_Line_Tool#549]
There might be a way to utilize a combination of a file query and `delete-file-version` or `possibly backblaze-b2 ls --versions --long` and some scripting, but i think this might be a handy housekeeping tool?

**Comment by ppolewicz** [comment]
This issue doesn't have a lot of traffic. If someone would like to actually implement the solution for this, please create a new issue to discuss how the interface would look like.

It seems that this function is not needed that much and it can be fairly easily implemented using bash or python by the users who need it.

Also please note that this is already solved server-side on a bucket level: https://www.backblaze.com/blog/backblaze-b2-lifecycle-rules/
while one could argue that this could also be possible to do via a cron job on a per-directory level or something, it's a bit of reach at this point. I personally don't think such option is necessary and adding rarely used options actually degrades the quality of the CLI tool as every user needs to dig through the options they won't use.
