### ISSUE TITLE
excludeRegex does not work as expected

### ISSUE THREAD

**Issue by dctremblay** [Backblaze/B2_Command_Line_Tool#552]
When I run this command, it does still upload that kind of files and the many others :

```
b2 sync --skipNewer --keepDays 30 --threads 17 \
    --excludeRegex '(cache|sess).+[a-z0-9]{26,}' \
    /var/www b2://somebucket/coolstuff
```

Sample output :

```
upload stuff/apps/www/public/cache/smarty/cache/socialsharing/69/1/1/1/1/1/177/8f/75/92/8f7592d0aecdb5969dcf1d1be1e576b8bb7fb8e1.socialsharing.tpl.php
```

The regex does match as expected using other tools, but not in b2.
What am I doing wrong ?

Thanks

**Comment by ppolewicz** [comment]
It matches (not searches!) the pattern in a relative path. Try this:
```
b2 sync --skipNewer --keepDays 30 --threads 17 \
    --excludeRegex '^.+(cache|sess).+[a-z0-9]{26,}.*$' \
    /var/www b2://somebucket/coolstuff
```

You could also consider using `excludeDirRegex`, it seems it could improve performance in your usage pattern

**Comment by dctremblay** [comment]
Ahhh I understand now, only full string matches are matched. Sorry for the issue !!

Thank you very much
