### ISSUE TITLE
b2 file upload so slow it is not usable 

### ISSUE THREAD

**Issue by promethe42** [Backblaze/B2_Command_Line_Tool#557]
Hello,

for the past 3 days, our backup system powered by `duplicity` + `b2` has become incredibly slow for no apparent reason:

* we have not updated `b2` (nor `duplicity`), we're using version 1.1.0 (AFAIK we cannot update it because of compatibility issues with `duplicity`)
* AFAIK we have not updated the machine itself
* caps & alerts in the backblaze admin are more than fine

We have the same issue when we use `b2` directly (without `duplicity`).

Backups have become so slow that they now take 15 hours instead of 15 minutes. It's so slow we have to, in fact, disable backups.

We're in Paris, France. And the machines suffering from this issue are also in France.

The machine itself does not have any network bandwidth issue:

```
$ curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
Retrieving speedtest.net configuration...
Testing from OVH SAS (178.33.231.213)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Naitways (Paris) [1.88 km]: 8.737 ms
Testing download speed................................................................................
Download: 913.37 Mbit/s
Testing upload speed................................................................................................
Upload: 797.91 Mbit/s
```

Any idea how to diagnose and fix this?

Regards,

**Comment by bwbeach** [comment]
This is not an issue with the commant-line tool, but with the Backblaze service.  

Please contact Backblaze support.  We've had other reports of slow uploads recently, and are working to track down the problem.

**Comment by promethe42** [comment]
I just contacted the support. I'll let you know what happens.

**Comment by promethe42** [comment]
FYI support asked me to run multiple `traceroute` on the corresponding server. I was told it helped them resolve the issue. But I'm not seeing any changes so far...

**Comment by ppolewicz** [comment]
the internet is constructed in a funny way. Two "AN" parties are responsible for the quality of your connection. Your ISP is one AN and they decide how to send data from you to some other place (for example Backblaze) and Backblaze decides how to send data (here confirmations of receiving your data) back to you. Those routes can be completely different. Backblaze may change the route it uses to reach you and so it can make sure the connection between them and you is very good.
Backblaze cannot really fix the routes for sending data from you to them. That is in control of your ISP. If this route is causing a problem (and that's kind of how it looks from your description), then it is your ISP that can fix whatever they did last week that caused your backups to slow down.

Usually it's not even fault of your ISP, but a fault of a network provider of that they use, or that they use indirectly (provider uses a provider who uses a provider etc) or (in my experience very frequently) fault is actually on an exchange point between ANs, which has an overloaded port which causes trouble to every route that passes through it. While Backblaze can try to alter their routes to avoid this overloaded traffic exchange point, your ISP should be doing the same (and, unless I missed something, they have not been effective at that so far).

I'm curious if we can modify b2 CLI and b2sdk in such a way that would improve performance even in case of flawed network conditions. @promethe42 could you describe your usage pattern? How many objects (and of what size are you uploading), how many (and what size) are you downloading?

**Comment by bwbeach** [comment]
Please let Backblaze support know what you're seeing.  We found and fixed some performance problems in the service, but were not able to reproduce the slow uploads ourselves.

If uploads are continuing to be slow, could you run with `--debugLogs`?  That will tell us if it's having trouble connection, if it's failing and retrying, and may have other clues to the slowness.

**Comment by promethe42** [comment]
Backup times/upload bandwidth are finally back to normal on my side. Thanks for your help.
