### ISSUE TITLE
Master Application Key being renamed to "Default Key (ID)"

### ISSUE THREAD

**Issue by spartan218** [Backblaze/B2_Command_Line_Tool#561]
We learned that some customers and integration partners were confused between the terminology of Application Keys.

Specifically we use the accountId and Master Application Key interchangeably.
Moving forward we just want anything to do with application keys to be called such.

This means accountId's will still work (and so will master application key ID's) but we just are renaming it into one entity called Default Key ID.

**Comment by ppolewicz** [comment]
Fixed in https://github.com/Backblaze/B2_Command_Line_Tool/pull/570
