### ISSUE TITLE
f002.backblazeb2.com blocked by Russia ISP's

### ISSUE THREAD

**Issue by mr-kobalt** [Backblaze/B2_Command_Line_Tool#568]
Hello team,

I wonder if you could help me with this problem, even if it doesn't directly relate to your app, rather to _Backblaze_ services as a whole.

At first I wanted to create an issue with thorough investigation process and deep technical details on a seemingly elusive case of weird SSL handshake error while trying to download files from [f002.backblazeb2.com](url), but after hours of trial-and-error I found out that reality is much simpler and more prosaic - our f government agency just blocked your IP because one of your users stored some [picture](https://f002.backblazeb2.com/file/files-gab/image/bb-5bb5371b65209.jpeg) that our politicians consider illicit (it's hard to tell whether these statement is valid in that particular case since your server returns **403** on that URL). And because they cannot block specific https URL they decided to just block an entire subdomain (sic!).

I don't know how to contact you infrastructure team, so would you be so kind to take their attention on that issue? Our activists keep a log on all banned IP's and domains that you could find here:
https://github.com/zapret-info/z-i

Obviously, from the end user point of view it would be much simpler, hence more robust, if we could avoid as many intermediate layers, like proxies, as possible.

Thank you for your time, any feedback would be much appreciated.

**Comment by bwbeach** [comment]
This github repo is specifically for the command-line tool.  For issues with the B2 service itself, please contact Backblaze Support.  They can work with the infrastructure team to investigate this issue.  The links are at the bottom of the [help page](https://www.backblaze.com/help.html).
