### ISSUE TITLE
Files in bucket 1 second newer than local files when performing 'b2 sync'

### ISSUE THREAD

**Issue by nizedk** [Backblaze/B2_Command_Line_Tool#571]
I have a borgbackup repository, containing a lot of files (180K~) which I periodically, however not often lately, syncs to a bucket with 'b2 sync'. I have a script for it, so I do it the same way every time.

However, at the last attempted sync, a lot of the files are claimed by 'b2 sync' in the 'compare' phase, to be 1 second newer in the bucket, so I should 'replaceNewer' or 'skipNewer' etc. If I use the 'compareTreshold' set to 1100 ms fuzzynes, the issue goes away:

```
ERROR: source file is older than destination: local://data/14/146128 with a time of 1490735828201 cannot be synced to b2://data/14/146128 with a time of 1490735828202, unless --skipNewer or --replaceNewer is provided
```

My local files look like this:

```
...
-rw------- 1 z z  6398967 2017-03-28 23:17:06.834059600 +0200 146127
-rw------- 1 z z  7160434 2017-03-28 23:17:08.201996600 +0200 146128
-rw------- 1 z z  7156487 2017-03-28 23:17:09.472059400 +0200 146129
-rw------- 1 z z  8421598 2017-03-28 23:17:10.821059400 +0200 146130
...

```
... and they are residing in a btrfs file system, where I'm very confident they haven't been touched or changed. It's files that were uploaded some time ago, that has since been synchronized without problems.

So - why now, suddenly, does 'b2 sync' think that some of them are exactly 1 second newer than the local files?

Is it a client/b2 issue, or a b2/server-side issue?

**Comment by ppolewicz** [comment]
Could you please show us your output of `ntpq -p`?

Has your last sync taken place before `2016-12-31 23:59:60` (last [leap second](https://en.wikipedia.org/wiki/Leap_second))?

Have you upgraded b2 CLI since the last sync?
I seem to vaguely remember a fix for a rounding error in regards to this sort of thing, but I can't find it in the changelog.

**Comment by nizedk** [comment]
```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 0.dk.pool.ntp.o .POOL.          16 p    -   64    0    0.000    0.000   0.000
 1.dk.pool.ntp.o .POOL.          16 p    -   64    0    0.000    0.000   0.000
 2.dk.pool.ntp.o .POOL.          16 p    -   64    0    0.000    0.000   0.000
 3.dk.pool.ntp.o .POOL.          16 p    -   64    0    0.000    0.000   0.000
 dk.pool.ntp.org .POOL.          16 p    -   64    0    0.000    0.000   0.000
-92.246.24.228   .kPPS.           1 u  174 1024  377    8.466   -1.389   0.231
+n1.taur.dk      .PPS1.           1 u  764 1024  377    4.105   -0.010   0.082
+212.99.225.86   .GPS.            1 u  996 1024  377    9.944   -0.375   0.245
*static-5-103-12 .GPS.            1 u  465 1024  377    8.282    0.056   0.075
```

No, it was 2017-march last sync - so some time ago, admittedly.

Yes, it was upgraded since. I don't know the version at the time of the last sync.

**Comment by ppolewicz** [comment]
perhaps you could use `git pickaxe` to find the version which broke this for you?

**Comment by nizedk** [comment]
Sorry for no reply on this. I got sidetracked by life; In the end I simply overwrote the newer files, and thus it was fixed.
