### ISSUE TITLE
Missing/incorrect releases; deprecation

### ISSUE THREAD

**Issue by jhart-r7** [Backblaze/B2_Command_Line_Tool#572]
The last official release in github was 1.3.8.  In the README it lists 1.4.0 twice -- I assume one is 1.4.1.  Please correct the README and provide releases for these missing versions.  Assuming the two 1.4.x releases were meant to be released, it would be great to have this result in an updated version of the `b2` python package.

Also it seems that in 1.4.x most of the code was migrated to b2sdk.  It would be great to link to this code since most attempts at figuring out bugs in the b2 client will involve looking at that code instead.

**Comment by ppolewicz** [comment]
1.4.0 was not released yet (the dates were entered in parenthesis by mistake) (and there are two 1.4.0 sections for some reason, that needs to be merged).

A link is a good idea. Would you like to submit a PR to add it?
