### ISSUE TITLE
Add b2 make-url --friendly switch?

### ISSUE THREAD

**Issue by rnkn** [Backblaze/B2_Command_Line_Tool#577]
It would be lovely to be able to get the friendly URL of a public file from the command line, perhaps with `b2 make-url --friendly FILEID`?

**Comment by ppolewicz** [comment]
This seems like a nice and small feature to add. Would you like to implement the changes? It's just a few lines of code, I think.

**Comment by rnkn** [comment]
Cool. I'm having a go at this, although I don't really know Python. I figured it would be as easy making an API call, but found there does not appear to be an API call for friendly URLs, so this I started with (unworking):

~~~diff
diff --git a/b2/console_tool.py b/b2/console_tool.py
index d1c6fc3..c6956d9 100644
--- a/b2/console_tool.py
+++ b/b2/console_tool.py
@@ -1005,10 +1005,20 @@ class MakeUrl(Command):
         it is public.
     """
 
+    OPTION_FLAGS = ['friendly']
+
     REQUIRED = ['fileId']
 
     def run(self, args):
-        self._print(self.api.get_download_url_for_fileid(args.fileId))
+        if args.friendly:
+            file_url = self.api.get_download_url_for_fileid(args.fileId)
+            file_info = self.api.get_file_info(args.fileId)
+            file_name = self.file_info["fileName"]
+            bucket_info = self.api.get_bucket_by_name(file_info["bucketId"])
+            bucket_name = self.bucket_info["bucketName"]
+            self._print("https://f002.backblazeb2.com/file/%s/%s".format(bucket_name, file_name))
+        else:
+            self._print(self.api.get_download_url_for_fileid(args.fileId))
         return 0
~~~

The thing I found is that the `make-url` command should only return a URL if the bucket is public, but the way I started going about it would return a URL regardless.

This might be something I'll have to return to once I actually learn Python...

**Comment by meganekko** [comment]
Hello, please see pull request #612. It generates a friendly URL by passing a bucket name and a file name.

**Comment by rnkn** [comment]
Cool!

**Comment by rnkn** [comment]
I'm a bit embarrassed to see how simple this was.
