### ISSUE TITLE
b2 authorize_account return (bad_auth_token)

### ISSUE THREAD

**Issue by irrelevantspechack** [Backblaze/B2_Command_Line_Tool#579]
Hello,

I installed python 2 and B2 command line tool as explained here : https://www.backblaze.com/b2/docs/quick_command_line.html

And tried to "log" into my account by following the step here : https://www.backblaze.com/b2/docs/quick_bucket.html

I write :

` b2 authorize_account masterkeynumber`

then it return :

```
Using https://api.backblazeb2.com

Backblaze application key:

```

Then I copy the "newly generated" master application key, by copying it and past it and pressing enter (since it's all hidden), and it return :

`ERROR: unable to authorize account: Invalid authorization token. Server said: (bad_auth_token)`

Don't know what to do. Seem simple, enter comand, copy appkey, paste and enter, but it's not working.. I tried creating a new masterkey, i tried to create a new appkey.. Nothing work.

For python to work I created a system variable "PYTHON_HOME", with "C:\Python27\;C:\Python27\Scripts\" inside and then added %PYTHON_HOME% to the PATH, but anyway the problem don't seems to be coming from python.

Also tried to run cmd as an administrator, but it didn't changed anything.

Also tried to use b2 authorize_account keyid appkey but got similar results.

**Comment by ppolewicz** [comment]
I guess the problem is with copying and pasting data from the web browser to the terminal.

Please try to paste the id and key to a notepad first, make sure there are no whitespace characters or anything funny near it, then copy the id and key from notepad to the terminal.

**Comment by koppor** [comment]
One has to use the `applicationKey` - not the `keyID`

![grafik](https://user-images.githubusercontent.com/1366654/127717448-9282c8ec-8195-47e7-9781-0b3785d719df.png)

**Comment by reinux** [comment]
Same issue. Dead certain key is correct. Copied to Notepad and trimmed whitespaces.
![image](https://github.com/Backblaze/B2_Command_Line_Tool/assets/5127297/d2e0735f-87f0-4a5e-be63-6562b3d412ce)
