### ISSUE TITLE
auth token expires too soon

### ISSUE THREAD

**Issue by vkolesn** [Backblaze/B2_Command_Line_Tool#582]
Steps:

1. Generate an auth token using the b2 command line tool, using the get-download-auth option
2. Get back a valid token like this one:
`3_20190620084402_[skip]_001_20190627051402_0000_dnld`
3. build a URL like this:
`https://f001.backblazeb2.com/file/[bucket]/[file]?Authorization=3_20190620084402_<skip>_001_20190627051402_0000_dnld`
4. Observe the URL is working ok, returning the file
5. wait about a day
6. Observe the same URL returning 401:
```{
  "code": "expired_auth_token",
  "message": "",
  "status": 401
}```

**Comment by svonohr** [comment]
Did you use the `--duration` option? The default valid time is one day as specified in the documentation:
```
b2 get-download-auth [--prefix <fileNamePrefix>] [--duration <durationInSeconds>] <bucketName>
    Prints an authorization token that is valid only for downloading
    files from the given bucket.
    The token is valid for the duration specified, which defaults
    to 86400 seconds (one day).
    Only files that match that given prefix can be downloaded with
    the token.  The prefix defaults to "", which matches all files
    in the bucket.
    Requires capability: shareFiles
```

**Comment by vkolesn** [comment]
I was sure I do, but I will double check and come back. cheers

**Comment by vkolesn** [comment]
as a side thought, I was under impression that the token includes start and expiration timestamps in plain text (e.g. for the above example `20190620084402` and `20190627051402`). If this is the case, then the token in my example should still work till Jun.27, but it doesn't

**Comment by bwbeach** [comment]
Thanks for the bug report.  You're right about the timestamps in the download auth tokens.

This is a bug in the service.  One of embarrassing bugs where the fix is obvious once you know there's a problem.  And it's been there for years without anybody noticing.  We'll add some tests, and get it fixed right away.

**Comment by vkolesn** [comment]
my pleasure. cheers
