### ISSUE TITLE
`b2 ls` unauthorized with a prefix-restricted app key

### ISSUE THREAD

**Issue by jacquev6** [Backblaze/B2_Command_Line_Tool#583]
Similarly to #556, a prefix-restricted key cannot be used to `b2 ls`, even the directory it's restricted to.

    $ b2 list-file-names $B2_BUCKET test-prefix
    ERROR: unauthorized for application key with capabilities 'listBuckets,listFiles', restricted to bucket '...', restricted to files that start with 'test-prefix' (unauthorized)

See [the `repro.sh` file in this gist](https://gist.github.com/jacquev6/71e4a9d1dc15728c71aacbdd6f5b0894#file-repro-sh) for a full reproduction script.

The root cause seems to be that [list_file_names in `raw_api.py`](https://github.com/Backblaze/b2-sdk-python/blob/335f225ef69b8cfdd5ad9bc41866c113688b0307/b2sdk/raw_api.py#L309) doesn't provide the optional `prefix` parameter to the [b2_list_file_names](https://www.backblaze.com/b2/docs/b2_list_file_names.html) API.

I suggest adding a `--prefix` option to `b2 ls` and `b2 list-file-names`.

**Comment by ppolewicz** [comment]
Thank you for a detailed bug report. Truly, it was a pleasure to read it. Expect a release with a fix for this in the next few days.
