### ISSUE TITLE
Using upload_file uplaods files as (started large file) using bash, how to fix?

### ISSUE THREAD

**Issue by FrozenBeard** [Backblaze/B2_Command_Line_Tool#589]
Im using a shell script to upload my backups with this:

`backblaze-b2 upload_file Bucketname $Upload1/$Latest_1 my-backups/afolder/$Latest_1`

It uploads but in the web UI it shows 0bytes with (started large file) next to it.

can someone tell me how to upload a 6gb+ file using this B2 CLI tool in simple bash? I have 2 large files I upload every X amount of time via crontab.

**Comment by ppolewicz** [comment]
Could you please run the command with `--verbose` and show us the log output?

**Comment by FrozenBeard** [comment]
I don't think that's a parameter?
Is it relatively new? im using Debian 10.
It fails wherever I put it:
```

b2 upload-file [--sha1 <sha1sum>] [--contentType <contentType>] \
        [--info <key>=<value>]* [--minPartSize N] \
        [--noProgress] [--threads N] <bucketName> <localFilePath> <b2FileName>

    Uploads one file to the given bucket.  Uploads the contents
    of the local file, and assigns the given name to the B2 file.

    By default, upload_file will compute the sha1 checksum of the file
    to be uploaded.  But, if you already have it, you can provide it
    on the command line to save a little time.

    Content type is optional.  If not set, it will be set based on the
    file extension.

    By default, the file is broken into as many parts as possible to
    maximize upload parallelism and increase speed.  The minimum that
    B2 allows is 100MB.  Setting --minPartSize to a larger value will
    reduce the number of parts uploaded when uploading a large file.

    The maximum number of threads to use to upload parts of a large file
    is specified by '--threads'.  It has no effect on small files (under 200MB).
    Default is 10.

    If the 'tqdm' library is installed, progress bar is displayed
    on stderr.  Without it, simple text progress is printed.
    Use '--noProgress' to disable progress reporting.

    Each fileInfo is of the form "a=b".

    Requires capability: writeFiles

```

**Comment by ppolewicz** [comment]
It is an old option available for all commands, not explicitly documented everywhere. See `readme.md` in this repository.

**Comment by FrozenBeard** [comment]
I cant seem to get it to work, I installed via debian 10 using apt install backblaze-b2, it completes 100% in the console, but its only when viewing the bucket in the browser it shows an inconsistent file size and that text next to it.

**Comment by ppolewicz** [comment]
What is the exact command that you are running (except the file name and bucket name - please garble those two)
