### ISSUE TITLE
0 byte file with a 0-0 byte range request

### ISSUE THREAD

**Issue by digitalpardoe** [Backblaze/B2_Command_Line_Tool#590]
I've been working with a 3rd party piece of software (MinIO) that seems to aim to optimise a simulation of `HEAD` by requesting a file with a range of bytes using `b2_download_file_by_name` rather than `b2_get_file_info` - which to me does seem the more performant way of executing an existence check.

However, the file I've been accessing via MinIO has a file size of 0 bytes and the resulting range request of `0-0` produces a `416: range_not_satisfiable` error.

This to me seems like a bug in the B2 API as I feel a range of `0-0` should return a whole file if its size is 0 bytes?

**Comment by bwbeach** [comment]
I think that the 416 is according to spec.  The ending index of a range request is _inclusive_, so a range `0-0` is asking for one byte, the first byte in the file.  A range that starts past the end of a file is considered unsatisfiable, so that's what it returns here.

Why not just use a `HEAD` request?

**Comment by digitalpardoe** [comment]
I don't believe there's currently an option for `HEAD` or similar in the API at the moment although I see from the Java SDK (https://github.com/Backblaze/b2-sdk-java/issues/28) that the use of the "list" APIs is recommended instead - which is the approach I've taken so far.

**Comment by ppolewicz** [comment]
According to https://www.backblaze.com/b2/docs/b2_download_file_by_id.html `HEAD` is supported and recommended

**Comment by ppolewicz** [comment]
I'm closing this since this is not actually an issue with the CLI (or SDK for that matter)
