### ISSUE TITLE
MemoryError copying files

### ISSUE THREAD

**Issue by dmmartins** [Backblaze/B2_Command_Line_Tool#595]
I'm having some hard time copying large files from a bucket. The cli works fine for some files then start eating all the memory and simply dies. Some times it trow a MemoryError exception.

Here's an example:
```pytb
/tmp/20191001-5815-1gffcyh:  23%|██▎       | 17.8G/77.5G [02:57<1:07:43, 14.7MB/s]Exception in threa
d Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner   
    self.run()
  File "build/bdist.linux-x86_64/egg/b2sdk/transferer/parallel.py", line 283, in run
    for to_write in response.iter_content(chunk_size=self.chunk_size):
  File "/usr/lib/python2.7/site-packages/requests-2.22.0-py2.7.egg/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/site-packages/urllib3/response.py", line 496, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/site-packages/urllib3/response.py", line 444, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.7/httplib.py", line 607, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.7/socket.py", line 408, in read
    return buf.getvalue()
MemoryError
```

I've tried python2.7, 3.6 and 3.7 and different linux distributions with same result.

**Comment by ppolewicz** [comment]
How much memory do you have on the machine on which this issue has been
observed?

śr., 2 paź 2019, 19:33 użytkownik Diego Martins <notifications@github.com>
napisał:

**Comment by dmmartins** [comment]
8GB. Same happens with 4GB

**Comment by ppolewicz** [comment]
This is a very interesting bug, most likely in `ParallelTransferer`. It is interesting because b2sdk was downloaded over 20192 times and you are the first person to report that issue.

I've inspected the code to look for a source of this issue and found it here: https://github.com/Backblaze/b2-sdk-python/blob/22c8c6af520d410dd48a53bb840dff58d9f763f9/b2sdk/transferer/parallel.py#L156

as a temporary workaround you could `pip install b2==1.3.6` which will use a version that downloads slower.

This bug has been only exposed after 20 000 installations because it is very rare to have a network faster than the hard drive (as is the case in this issue).

**Comment by devhen** [comment]
I'm having an issue that might be related, on b2 1.4.2 doing `b2 download_file_by_id` consumes all memory & swap and gets killed by the kernel. I increased my VM's memory from 4GB to 8GB and it still happened. I have 2GB of swap. Downgrading to 1.3.6 worked, thanks for that, but it does download a whole lot slower.

**Comment by ppolewicz** [comment]
yes, I plan to fix it soon.

This only happens when your local storage is slower than your network. You should diagnose why your local storage is so slow.

**Comment by devhen** [comment]
Thanks @ppolewicz. In my case this is on a Google Cloud VM. It is using their SSD PD storage but performance is capped based on the size of the disk and the number of processors so while its possible to get much better performance, for us its not worth it on this particular VM.

Thanks for your work!
