### ISSUE TITLE
Is it possible to use multiple app keys on the same server?

### ISSUE THREAD

**Issue by viktorix** [Backblaze/B2_Command_Line_Tool#597]
Is it possible to upload files to 2 separate buckets using 2 separate app keys that are restricted to their  own buckets? Or would I need app key with access to all buckets? Thanks.

**Comment by ppolewicz** [comment]
You can `export B2_ACCOUNT_INFO=some/path` to change the "context" account info. Then you can have several account info files for different keys, so you can choose which you use. Remember that you need to authorize each key before you can use them.

FYI, default account info is at `~/.b2_account_info`
