### ISSUE TITLE
b2 ls command no output

### ISSUE THREAD

**Issue by nickbaileysmg** [Backblaze/B2_Command_Line_Tool#598]
I am trying to use the `b2 ls --recursive <bucket> <directory>` command to retrieve a list of files on BackBlaze in a specific "directory". It has been working while doing some testing but seems to have stopped. I think it has something to do with versions as if I do the command `b2 ls --version --recursive <bucket> <directory>` I get the list of files expected with all versions of the files. 

Is this intended behavior? What can I do to keep this from happening? I'm relatively new to BackBlaze and still working through understanding everything.

**Comment by ppolewicz** [comment]
It looks like all the files in that directory may have been hidden (deleted by `b2 sync`). Could you please check that directory with b2 web admin panel to confirm?

**Comment by nickbaileysmg** [comment]
> It looks like all the files in that directory may have been hidden (deleted by `b2 sync`). Could you please check that directory with b2 web admin panel to confirm?

Yeah, it appears you are correct. I think I have a misunderstanding in the way that the sync command works. If I issue a sync command with `--keepDays` with `--excludeRegex` my expectation was that only the included items would be sync'd with the excluded files being ignored. Instead every ignored file is marked as hidden.
