### ISSUE TITLE
Using B2 Command Line Tool with iTerm2 & ZSH (Prezto)

### ISSUE THREAD

**Issue by brianjking** [Backblaze/B2_Command_Line_Tool#60]

**Comment by bwbeach** [comment]
Could you describe the issue?  Is there a problem with iTerm2 & ZSH?

**Comment by ppolewicz** [comment]
Could you please provide a more detailed requirement? Why current version is not suitable?

**Comment by ppolewicz** [comment]
I just checked, compatibility with zsh is not a problem. I suspect the author wants support for `prezto` (zsh autocompletion).

**Comment by ppolewicz** [comment]
If someone wants to add support for autocompletion, we will accept a pull request, but due to low demand for this and limited development power, this issue is unlikely to be implemented by b2 command line tool core dev team any time soon.
