### ISSUE TITLE
excludeRegex for skipping all hidden files

### ISSUE THREAD

**Issue by brainbuz** [Backblaze/B2_Command_Line_Tool#607]
I'm trying to write a backup script using b2 sync that will always ignore hidden files and directories
I've been able to write a command that will ignore them but only in the top directory level.

**$ b2 sync --dryRun --delete --excludeRegex '\\.' --excludeDirRegex '\\.' --replaceNewer $SRC $BUCKET**
result:
_upload Good/.Trash/garbage.txt_                                     
_upload Good/.invisible_                              
upload Good/visible                                 
upload visible.txt    

_.Trash_ folder was successfully ignored
_.invisible.txt_ file was successfully ignored
 
Please add an example of the correct regex to the documentation for b2 sync help.
If this is not doable by regex is it possible to add a switch for hidden files and directories?

**Comment by mjurbanski-reef** [comment]
With current CLI version should be fine with `b2 sync --dryRun --delete --excludeRegex '(^|/)\.' --replaceNewer $SRC $BUCKET`.

We have plans to do a general refresh on our documentation, but we also accept individual contributions, so feel free to issue a PR if you would like to see some more examples in it.
