### ISSUE TITLE
copy-file-by-id creates extra versions

### ISSUE THREAD

**Issue by dlevear** [Backblaze/B2_Command_Line_Tool#609]
I have a file called april2019_backup/photos_2018.zip. It is 1.1GB large. When I call copy-file-by-id on it, I end up getting anywhere from 3-5 new copies of it at the target path. This is a problem because it triples my storage use. 

**Details and evidence:**
I am using b2 command line interface version 1.4.2. I am using Cygwin on Windows 10, which has python3.6 installed.

In this screenshot, I try copying the file three times. The first two times give an error that I don't understand. Then I tried re-authorizing my account just in case. Then I didn't get an error message the third time.

![InkedInkedcopyfile_test_LI](https://user-images.githubusercontent.com/52705716/78039620-59cc1380-733c-11ea-8bca-0b6608630674.jpg)

However, if you look at the results, you will see that all three attempts did create new copies of the file. The "failed" attempts created 5 new copies, and the "success" attempt created 3. 

![copyfiletest_webinterface](https://user-images.githubusercontent.com/52705716/78039025-8fbcc800-733b-11ea-89dd-f32f278a2932.PNG)

![copyfiletest_v3_result](https://user-images.githubusercontent.com/52705716/78038197-8c750c80-733a-11ea-820f-517aa6782960.PNG)

![copyfiletest_v4_result](https://user-images.githubusercontent.com/52705716/78038198-8c750c80-733a-11ea-93be-7d4985a3060b.PNG)

So the error message did not stop the command from going through. In fact, it seems there was no error in the first place, since it worked anyway. So this is clearly a bug... after output like this I would expect that 1 file was created, not 13 files.

**Possible cause**
I wonder if the time-out error handling causes a new copy command to be issued, and only if this happens 5 times in a row does the program spit out an error... but the process is still running on the server-side? This is just a guess.

I have tried the command on a variety of files. This issue only happens with files that are somewhat large (maybe >500MB?). I think this is because the time-out issue does not happen if the copy command takes no time.

By the way, my internet is not slow. I routinely watch Netflix and live sports streaming. But I don't think that is relevant, since the whole operation should be happening on the server side anyway. I believe this is the purpose of using copy-file-by-id instead of download + reupload.

**Comment by ppolewicz** [comment]
Your analysis seems correct.

Work on resolving large file copy is well underway, but I expected the current solution to be good enough for files up to 5GB or more. It seems that 1.1GB was server-side copied at a rate lower than 8.46 MB/s, which does not sound right. Perhaps the pod that was performing the operation was rebuilding a drive or it was impaired in some other way?

Anyway, the new solution (PR for which is now getting the final touches, docstring additions, grammar fixes in comments etc) will use large file upload mechanism for files larger than 200MB which will not only resolve the problem you were facing, but it'll also allow continuation of a failed operation (to prevent multiple copies from being created like in your case) and parallelization (so it will be much faster even if server is slow for some reason).

As for the small copy retrying on timeout, I'm not sure if there is a reasonable way to fix it (without journaling and "fsck", that is). Do you see a way to make it better?

**Comment by dlevear** [comment]
Hi, this is interesting. I'm not at all versed in how everything works, so I don't have any proposals for solution. It will be nice when this new solution is available. I don't think it was just the pod being busy, since I actually did this test multiple times on different days and something very similar happened each time. Thanks for letting me know some more information.

**Comment by ppolewicz** [comment]
@dlevear would you be interested in testing an early development version of b2sdk which has much better support for large file copy?

**Comment by dlevear** [comment]
Thanks for the offer, but I am a little busy with other things right now so I will pass on that.

**Comment by ppolewicz** [comment]
large file copy has been deployed a while back, closing the issue as stale
