### ISSUE TITLE
ERROR: Connection error: 

### ISSUE THREAD

**Issue by luccavallari** [Backblaze/B2_Command_Line_Tool#610]
Hi, my server show this error when run a sync option. How do solve this?

> ERROR: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v2/b2_list_file_versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f029ca3b0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by ppolewicz** [comment]
Hi,

DNS on your server is not configured properly. This is not b2-specific, you need to fix the configuration of your server.

**Comment by luccavallari** [comment]
@ppolewicz ,

There was an update on the server and the dns servers were changed to blank values. I had not been aware of this since in general things were working, except the backup. Thank you
