### ISSUE TITLE
Can't cancel download with `ctrl-c`

### ISSUE THREAD

**Issue by molomby** [Backblaze/B2_Command_Line_Tool#619]
When a download is active (eg. after running `b2 download-file-by-id`) it cannot be interrupted with a `SIGINT` (<kbd>Ctrl</kbd>+<kbd>c</kbd>) or EOF (<kbd>Ctrl</kbd>+<kbd>c</kbd>). Both cause the progress bar to be printed on a new line but have no other effect.

The `SIGQUIT` signal works (<kbd>Ctrl</kbd>+<kbd>\\</kbd>) but, on MacOS at least, triggers an analytics collection dialogue:

![Screenshot 2020-05-09 at 17 33 35](https://user-images.githubusercontent.com/2416367/81467387-a4825a80-921b-11ea-8155-4fd15f062571.png)

**Comment by ppolewicz** [comment]
what happens if you click "show details"?

**Comment by mjurbanski-reef** [comment]
Please reopen if problem still occurs with current version.
