### ISSUE TITLE
Repeatable 503 error (vault full) when using b2_upload on an incomplete large file. 

### ISSUE THREAD

**Issue by mookman288** [Backblaze/B2_Command_Line_Tool#622]
I will try to be as informative as possible in this bug report while maintaining privacy of the data being backed up. 

We encountered an error recently from our host, who had setup B2 CLI and a quick cronjob to sync our main data directories as another method of backup. 

At some point, the cronjob failed because of a firewall issue with changed Backblaze IP addresses. 

I noticed that we were unsuccessful with restarting the sync process, because of a 503 error. Here is the snippet from an upload: 

```
ServiceError: 503 service_unavailable not enough space in c001_v0001117_t0012
ERROR: 503 service_unavailable not enough space in c001_v0001117_t0012
```

After reviewing the help desk article, I attempted to run the sync repeatedly, but each time it returned the exact same error. 

According to the output, the B2 CLI did attempt to retry on its own multiple times:

```
100%|█| 460M/460M [00:02<00:00, 198MB/s]
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_finish_large_file HTTP/1.1" 503 108
INFO:b2sdk.b2http:Pausing thread for 1 seconds because that is what the default exponential backoff is
DEBUG:urllib3.connectionpool:Resetting dropped connection: api001.backblazeb2.com
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_finish_large_file HTTP/1.1" 503 108
INFO:b2sdk.b2http:Pausing thread for 1 seconds because that is what the default exponential backoff is
DEBUG:urllib3.connectionpool:Resetting dropped connection: api001.backblazeb2.com
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_finish_large_file HTTP/1.1" 503 108
INFO:b2sdk.b2http:Pausing thread for 2 seconds because that is what the default exponential backoff is
DEBUG:urllib3.connectionpool:Resetting dropped connection: api001.backblazeb2.com
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_finish_large_file HTTP/1.1" 503 108
INFO:b2sdk.b2http:Pausing thread for 3 seconds because that is what the default exponential backoff is
DEBUG:urllib3.connectionpool:Resetting dropped connection: api001.backblazeb2.com
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_finish_large_file HTTP/1.1" 503 108
```

This error, at the time, was fully repeatable. As long as you attempted to run a sync, or even a b2_upload of that specific file, it would always fully upload the file, and then report a 503 and error out. 

I did some research on the issues reported on github so far, I looked into the knowledge-base on Backblaze's site, and I checked all over the Web, but I couldn't find anyone who seemed to have this exact issue. Most of the responses were to "try again." 

After a long and arduous conversation with Backblaze support, which never solved the issue, I went ahead and started digging into the B2 GUI in search of the file that was hanging. I found that the file reported as 0 bytes, but was in fact an incomplete upload (something like, large parted? I can't recall.) 

After deleting the file in the GUI, I was able to successfully upload the file. 

Based on what I've seen, I believe there might be a bug where a file is uploaded (in part) and fails to fully upload into a vault that later becomes full. When the file attempts to be overwritten, the application fails because there's not enough space to finish the upload. 

I don't know enough about the B2 CLI codebase to be certain that this is an issue with the B2 CLI app, or the Backblaze B2 API. I also can't provide an accurate suggestion on a solution. In my case, deleting the incomplete file allowed the B2 CLI to re-upload without error. Maybe by detecting the incomplete upload and purging the broken file, it won't get stuck trying to upload to a full vault. 

If you need any other information, I will try to help as much as possible. 

I hope this helps.

**Comment by mookman288** [comment]
After speaking with Backblaze support further, they believe that this can be solved with the following command:

```
 b2 cancel_all_unfinished_large_files yourbucketname
```

The only concern is identifying when to use this command. There are some contextual clues provided by the CLI: 

* The file is uploaded fully
* The error still appears due to the vault being full

Doing a b2-list-file-names does not return the incomplete file, so unless you visit the GUI directly, I don't see an apparent way to ascertain that this specific situation has occurred and needs the above command to be run. 

I hope this information helps others who ran into this same problem.

**Comment by malaysf** [comment]
Thank you for reporting this. This was a backend issue where the vault was full and could not accept more uploads; this is truly an unusual and exceptional occurrence. The issue has been resolved and this vault (and all others) are accepting uploads.

An alternative to using the `cancel_all_unfinished_large_files` command, the command `list-unfinished-large-files` will list the pending large files to aid with running a targeted `cancel-large-file` command.
