### ISSUE TITLE
CLI Autocomplete Does Not Work

### ISSUE THREAD

**Issue by fancyHeat** [Backblaze/B2_Command_Line_Tool#637]
For example, if I type in "b2 auth" and then press tab, it should auto complete to "b2 authorize-account". However this does not seem to work on either Windows or Mac

**Comment by ppolewicz** [comment]
@fancyHeat did you follow [the installation instructions for auto-complete](https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/doc/bash_completion.md)?

**Comment by fancyHeat** [comment]
Would the instruction be the same for using zsh on macOS

**Comment by ppolewicz** [comment]
No, this is bash-specific. Feel free to contribute a zsh auto-completer!
