### ISSUE TITLE
b2 ls --prefix is invalid

### ISSUE THREAD

**Issue by kwinke** [Backblaze/B2_Command_Line_Tool#649]
On version 2.0.2, the b2 ls command using the --prefix option doesn't work or correctly run. It doesn't seem to take arguments like the previous list-file-names command did.

Using it before the bucketID gives the error b2: error: unrecognized arguments: "prefix argument" confusing the prefix argument (whether it's quoted or not) with the bucketID.

Running b2 ls without --prefix works as expected.

**Comment by ppolewicz** [comment]
@mlech-reef https://github.com/Backblaze/B2_Command_Line_Tool/blob/b7d1eaac16dd9840d241dcb84c69846650d6a2f5/b2/console_tool.py#L1054 I think the prefix argument is not passed in, could you please take a look (and maybe add a test)?

**Comment by mlech-reef** [comment]
I guess now we have:
https://github.com/Backblaze/B2_Command_Line_Tool/blob/b7d1eaac16dd9840d241dcb84c69846650d6a2f5/b2/console_tool.py#L1056
and `--prefix` is redundant and should be removed.
