### ISSUE TITLE
Perhaps naively trying on Windows, doesn't work

### ISSUE THREAD

**Issue by quinxy** [Backblaze/B2_Command_Line_Tool#65]
Trying this on Windows, with the latest Python (3.5.1) and running the script just says:

  File "b2.py", line 1351
    print self.desc
                 ^

Not sure if anyone expects this to work in Windows, whether I should use a lower version of Python, or what.

**Comment by bwbeach** [comment]
It should work on Windows, but doesn't work with Python 3.  Only Python 2 is supported for now.

I need to learn how to prevent pip3 from trying to install it.

**Comment by quinxy** [comment]
Ah, okay, that would explain it!  Thanks for letting me know I'll try that.

**Comment by quinxy** [comment]
Sorry, I seem to be having an issue which suggests Windows weirdness.  I was trying to sync a directory and am getting an error about "\\" in file names.

C:\test>py -2 b2.py sync a b2:test/a
+ usbdeview-x64\USBDeview.cfg
ERROR: Error returned from server:

URL: https://-------------18_t0013
Params: None
Headers: {'Content-Length': '1341', 'Content-Type': 'b2/x-auto', 'X-Bz-File-Name': 'a/usbdeview-x64%5CUSBDeview.cfg', 'X-Bz-Info-src_last_modified_millis': '1453739103916', 'X-Bz-Content-Sha1': 'ed---------------------1', 'Authorization': u'-------------upld', 'User-Agent': 'backblaze-b2/0.4.1'}

{
  "code": "bad_request",
  "message": "file names must not contain '\\'",
  "status": 400
}
