### ISSUE TITLE
Unexplained error windows B2 CLI

### ISSUE THREAD

**Issue by poliscialex** [Backblaze/B2_Command_Line_Tool#654]
I am syncing files (obviously) and toward the end of a large sync, I continually get this error which does not give me much information
![Screenshot_20200811_062047](https://user-images.githubusercontent.com/68288927/89896509-cf71a700-db9a-11ea-807a-73188dd2d88e.png)

Any thought on this?

**Comment by ppolewicz** [comment]
the information that you are looking for is further up. Sync terminates "soon after" it encounters a fatal failure, here it managed to upload a few files between the time it decided to terminate and the time it actually stopped.

By the way, perhaps you'd like to filter out `Thumbs.db` files with `--excludeRegex` - those are indexes autogenerated by Windows, storing it offsite may be of little value.
