### ISSUE TITLE
b2 sync fails with special chars (?)

### ISSUE THREAD

**Issue by rmens** [Backblaze/B2_Command_Line_Tool#655]
I might have bumped into an edge case here. After syncing a large directory with media files, there were some remaining errors. File names with a special char like _'_ in it, won't sync. 

This is with the latest b2 client (standalone) downloaded from the site on 23th august.

```
WARNING: /mnt/storage/web/video/html/uitzendingen/2019/03/15-03-2019-Kick-off 'Supersum'.mp4 could not be accessed (no permissions to read?)
WARNING: /mnt/storage/web/video/html/uitzendingen/2019/04/27-04-2019-Opening nieuw 'tochtportaal' Gertrudiskerk.mp4 could not be accessed (no permissions to read?)
WARNING: /mnt/storage/web/video/html/uitzendingen/2019/07/22-07-2019-tegelfoto\'s SEP.mp4 could not be accessed (no permissions to read?)
WARNING: /mnt/storage/web/video/html/uitzendingen/2020/02/01-02-2020 - Vastenavendbeurs \'t Veldteke.mp4 could not be accessed (no permissions to read?)
```

**Comment by ppolewicz** [comment]
I bet those chars are not actually simple single quotes but they are some weird encoding things that looks almost the same way. Could you please check if that's the case?

**Comment by sdebacker** [comment]
Same problem for me using aws cli, here the problem is the char "%0A" : 

upload failed: uploads/files/Multi Words
with Special Chars/doc.pdf to s3://bucket/uploads/files/Multi Words
with Special Chars/doc.pdf Connection was closed before we received a valid response from endpoint URL: "https://s3.eu-central-003.backblazeb2.com/bucket/uploads/files/Multi%20Words%0Awith%20Special%20Chars/doc.pdf"

**Comment by ppolewicz** [comment]
According to https://www.backblaze.com/b2/docs/files.html:
> file names can be pretty much any UTF-8 string up to 1024 bytes long. There are a few picky rules:
> 
> - No character codes below 32 are allowed.
> - DEL characters (127) are not allowed.

Here `%0A` is 10, which is below 32.

As for the opening post of this issue, it looks like an environemnt issue, I doubt that you can read those files with a shell script too.

**Comment by sdebacker** [comment]
Ideally there should be no such characters in the file name, but I have some file with it…
I can read and manipulate these files via an URL, or via a tool like Transmit (macOS). Also, I can sync it perfectly on an Amazon S3 bucket (with aws cli), so I was wondering if it could be possible also on a Backblaze B2 bucket.

**Comment by ppolewicz** [comment]
As I said, B2 has this limitation and it's documented. I suggest that you just rename those files, usually you don't really want to have newlines in the filenames anyway ;)
