### ISSUE TITLE
ConnectionResetError while uploading data using backblaze b2 command line tool

### ISSUE THREAD

**Issue by druvakumarcs** [Backblaze/B2_Command_Line_Tool#656]
![BackBlae upload failure](https://user-images.githubusercontent.com/63407819/91634047-f3424300-ea0a-11ea-9ef6-2b72b01f6ce2.PNG)

Hi,

We upload our customer most essential data to backblaze. These days we are facing a lot of connection reset by peer or connection aborted errors.

We upload files using b2 command based line

Below is the error:

ERROR: FAILED to upload after 5 tries. Encountered exceptions: Connection error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Connection error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

We are already using latest version of python
python3

OS version: Ubuntu server 18.04

Kinldy suggest us in future how to prevent these issues

**Comment by ppolewicz** [comment]
Troubleshoot your network connection

**Comment by druvakumarcs** [comment]
Hi,

We are using a cloud service provider machine. We had verified the network setting of service provider there seems to be no issue.

Moreover we don't see this frequently it occurs once in a fort night.

**Comment by ppolewicz** [comment]
Hey,

it really looks like a network issue. You should monitor the quality of your connection to the B2 server, maybe set up a smokeping or something to see what is going on. Another issue that might cause this is if your source is extremely overloaded (either in terms of CPU (steal?)) or drive speed slowing down to zero. If you stop sending data to B2 for a few minutes, it kind of looks like a DoS attack and the server might not like it. Make sure your machine and connection is fine and sync will operate properly.
