### ISSUE TITLE
download-file-by-id fails downloading file uploaded through the S3 API

### ISSUE THREAD

**Issue by gsauthof** [Backblaze/B2_Command_Line_Tool#657]
When I try to download a file I previously uploaded through the S3 API `b2` always fails like this:

```
$ b2 download-file-by-id $some_id x.opus
x.opus: 100%|███████████████████████████████| 4.65M/4.65M [00:03<00:00, 1.45MB/s]
ERROR: sha1 checksum mismatch -- bad data
```
FWIW, files were uploaded via `FPutObject()` using the minio S3 Go SDK.

This is caused by this check:

https://github.com/Backblaze/b2-sdk-python/blob/1984e90256ff7c4233d25e2485493057f9364dd6/b2sdk/transfer/inbound/download_manager.py#L131-L136

When I look at the actual values for this example I get:

```
content_sha1 => "unverified:807ab3748e11c20c7a034365b71dcc7066ef9136"
 actual_sha1 => "807ab3748e11c20c7a034365b71dcc7066ef9136"
```

Meaning that the checksums actually do match but `download-file-by-id` is only able to validate checksums when the file was uploaded with a client-supplied Sha1 checksum. That means the download would also fail for files uploaded with the B2 API when `X-Bz-Content-Sha1: do_not_verify` was set.

Please correct me if I'm wrong, but when using the S3 API there is no way to supply the file's SHA1 checksum. At least not in endpoint agnostic way, I presume.

Expected behavior of the download check: either check the unverified server computed checksum or just skip the checksum check.

AFAICS, currently, the `b2 download-file-by-id` command doesn't support disabling the checksum check via an option. Adding such an option would be a useful feature, I think.

Btw, while looking at your [API docs](https://www.backblaze.com/b2/docs/uploading.html) in Firefox I've noticed that the layout requires a quite large minimal browser window width - otherwise the content in the main content is cut off - although on the left there is a bunch of space. This gets works if one increases the font size. Quite bad for accessibility it seems.

**Comment by gsauthof** [comment]
PS: It looks like the `_validate_download()` function (https://github.com/Backblaze/b2-sdk-python/blob/1984e90256ff7c4233d25e2485493057f9364dd6/b2sdk/transfer/inbound/download_manager.py#L131-L136) also contains an error reporting issue:

```
                raise ChecksumMismatch(
                    checksum_type='sha1',
                    expected=metadata.content_length,
                    actual=actual_sha1,
                )
```

(-> the `content_length` is reported instead of the checksum)

It should probably read like this:

```
                 raise ChecksumMismatch(
                     checksum_type='sha1',
-                    expected=metadata.content_length,
+                    expected=metadata.content_sha1,
                     actual=actual_sha1,
                 )

```

**Comment by ppolewicz** [comment]
Thank you for a detailed report. There are at least three ways to fix this issue and I need to talk to the server devs to understand which way is best. Stay tuned.

**Comment by ppolewicz** [comment]
Ok, so `unverified:` prefix is pretty old now but we have not supported it. We'll have to add support for it to b2sdk (and also we'll fix `_validate_download()` on the way).

You can always download such file via http using `wget` or `curl` or something, it's not like lack of this switch in b2sdk/b2cli makes it impossible to download a corrupted file, so we'll add verification of the checksum because that's what should generally happen. If someone one day will want to add a switch to disable the verification and enable downloading of files that are most likely corrupted, then we can discuss it in a separate thread. So far we've been pushing it into the other direction whereas whenever a checksum error happened, everything stopped and we are discussing various places where we can add more verification.

**Comment by ppolewicz** [comment]
@gsauthof as for the API docs issue, please email b2 support - they have contact with the team responsible for the website and they can troubleshoot it with you, there is no point in me proxying it over there.

Backblaze/b2-sdk-python#153 will fix the issue you faced with the download verification crash, but as discussed above, we are not adding support for unverified checksum on upload at this point, or for disabling verification on download. If you'd like us to add it, please open a new issue and lets discuss it there.
