### ISSUE TITLE
auto-authorize if B2_APPLICATION_KEY_ID and B2_APPLICATION_KEY are provided

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#665]
Born out of #664.

We could maybe not ask the user to explicitly call `b2 authorize-account` if they just want to sync something from an ephemeral environment (like docker container), but we could just do that in the background. It seems that the changes required for this would not be very large, relevant code is [here](https://github.com/Backblaze/B2_Command_Line_Tool/blob/08002cb13dbd5aacc5b098458428260c48edaad6/b2/console_tool.py#L1508), we'd just check for the env variables and if they are present, authorize and `return self.run_command(argv)`

**Comment by mlech-reef** [comment]
Implemented in #688
Released in [b2 v2.2.0](https://github.com/Backblaze/B2_Command_Line_Tool/releases/tag/v2.2.0)

**Comment by lohman** [comment]
Thanks for adding this; appreciated.
