### ISSUE TITLE
Can B2_ACCOUNT_INFO accept a path?

### ISSUE THREAD

**Issue by cimm** [Backblaze/B2_Command_Line_Tool#672]
I understand we currently need to authorize the keys before using the CLI. It would be nice to pass the keys in the environment for a scripting context as requested in #665. For the time being though I'll have to use the B2_ACCOUNT_INFO environment variable.

From the README

> The environment variable B2_ACCOUNT_INFO specifies the sqlite file to use for caching authentication information. The default file to use is: ~/.b2_account_info

This means the B2_ACCOUNT_INFO variable needs to contain the JSON contents of the ~/.b2_account_info file and not the _path_ to the file, correct? I think I can confirm this since running `B2_ACCOUNT_INFO=/tmp b2 get-account-info` gives me a `IsADirectoryError` and `B2_ACCOUNT_INFO={} b2 get-account-info` a `Missing account data` error. Still, this [reply](https://github.com/Backblaze/B2_Command_Line_Tool/issues/597#issuecomment-547361691) on another issue hints at specifying a path to the file?

Is there a way to tell `b2 authorize-account` the _path_ to the authorization file to use? I am trying to run the B2 CLI in a [snap](https://snapcraft.io/) and I would like to store the authorization file in a specific location.

Thank you!

**Comment by ppolewicz** [comment]
`B2_ACCOUNT_INFO` env var should point to a file. I think you managed to convince b2cli to try to use the sqlite database stored in `./{}` and then it said there are no relevant entries in that "database".

#665 looks fairly easy to implement, it's just a few lines of code. Perhaps you'd like to take a stab at it? It would be a glorious first contribution!

**Comment by cimm** [comment]
Setting the `B2_ACCOUNT_INFO` to the path does indeed work. I since learned it is way simpler to use the Python SDK instead of trying to shoehorn the B2 CLI into a script.

I converted my shell scripts to Python ones. If anyone would be interested, this was my ugly shell attempt:

```sh
BUCKET="mybucket"
ACCOUNT_AUTH_TOKEN="$(B2_ACCOUNT_INFO=myauthfile b2 get-account-info | awk -F'"' '/accountAuthToken/{print $4}')"
API_URL="$(B2_ACCOUNT_INFO=myauthfile b2 get-account-info | awk -F'"' '/apiUrl/{print $4}')"
API_URL="$API_URL/b2api/v2/b2_get_upload_url"
BUCKET_ID="$(b2 get-bucket $BUCKET | awk -F'"' '/bucketId/{print $4}')"
UPLOAD_URL_JSON="$(curl -H 'Authorization: $ACCOUNT_AUTH_TOKEN' -d '{\"bucketId\":\"$BUCKET_ID\"}' $API_URL)"
AUTHORIZATION_TOKEN="$(echo $UPLOAD_URL_JSON | awk -F'"' '/authorizationToken/{print $4}')"
UPLOAD_URL="$(echo $UPLOAD_URL_JSON | awk -F'"' '/uploadUrl/{print $4}')"
B2_ACCOUNT_INFO=myauthfile b2 upload-file $BUCKET localFile remoteFfile
```
Now replaced with the much nicer Python version:
```python
from b2sdk.v1 import InMemoryAccountInfo
from b2sdk.v1 import B2Api
b2 = B2Api(InMemoryAccountInfo())
b2.authorize_account('production', APPLICATION_KEY_ID, APPLICATION_KEY)
bucket = b2.get_bucket_by_name(BUCKET_NAME)
bucket.upload_local_file(localFile, remoteFile)
```

Thanks for the help @ppolewicz!
