### ISSUE TITLE
Change exit code from 1 to 0 when no files were changed but process completed successfully

### ISSUE THREAD

**Issue by luboslives** [Backblaze/B2_Command_Line_Tool#673]
Hi, I have a systemd timer + service to run daily backups. When a directory has not changed since the last run, `b2` is exiting with an exit code of 1 (failure) when it should be 0 (success). An example trace:

```
mybackup.service: Failed with result 'exit-code'    systemd
mybackup.service: Main process exited, code=exited, status=1/FAILURE   systemd
Backup completed successfully!    mybackupscript.sh
Data downloaded: 54.04 MB   mybackupscript.sh
Data uploaded: 0 bytes    mybackupscript.sh
Files changed: 0   mybackupscript.sh
Files deleted: 0   mybackupscript.sh
Files added: 0   mybackupscript.sh
```

**Comment by ppolewicz** [comment]
I don't think that's what happened. In https://github.com/Backblaze/B2_Command_Line_Tool/blob/1ddcc6e3d062dd15dd99479f0597b4f630553107/b2/console_tool.py#L1324 we can see that exit code is zero (unless sync throws an exception, but there is no exception thrown if everything is the same). Perhaps it is `mybackupscript.sh` which is returning the improper error code, not `b2 sync`?

**Comment by luboslives** [comment]
Thanks @ppolewicz, I just realized the script runs through _Duplicati_ and backs up to B2. My mistake!
