### ISSUE TITLE
b2 Not Installing

### ISSUE THREAD

**Issue by shmecklen** [Backblaze/B2_Command_Line_Tool#676]
I'm trying to install the b2 command line tool in macOS 11.1, but no method seems to work. I'm one of those users who copypastes commands from instructions into Terminal.

The "self-contained download" at https://www.backblaze.com/b2/docs/quick_command_line.html downloads as a 7.4 mb file with no extension. It only opens in text edit as unintelligible machine code, so I tried the Python method.

I updated to Python version 3.9.1 and called 
`pip install --upgrade b2`
this returned:
`-bash: /usr/local/bin/pip: /usr/local/opt/python3/bin/python3.6: bad interpreter: No such file or directory`

I went to that directory, and it contains python3.7, not python 3.6.

Then I tried 
`sudo pip install --upgrade --ignore-installed b2`
It prompted my password, then returned:
`sudo: unable to execute /usr/local/bin/pip: No such file or directory`

I went to /usr/local/bin/ and it does contain a pip Unix Executable file.

Tried reinstalling pip, but got the same errors above. I'm at a total loss, any help would be appreciated.

**Comment by ppolewicz** [comment]
The self-contained thing is an executable binary. use `chmod +x file_name` on it to mark it as executable on your filesystem, then `./file_name` to actually run it

**Comment by shmecklen** [comment]
Ok, that worked. It’s strange that the instructions assume someone would know those steps at
https://www.backblaze.com/b2/docs/quick_command_line.html <https://www.backblaze.com/b2/docs/quick_command_line.html>

Thanks

**Comment by shmecklen** [comment]
Can you tell  me how to copy everything on a drive into an empty bucket using the sync command?

Best
§

**Comment by shmecklen** [comment]
I tried: 
sync /Volumes/DriveName b2://BucketName

but nothing happened…

I’m trying to sync the whole drive, not one directory at a time.

Thanks,
§

**Comment by Lasvad** [comment]
Agreed! This needs to be added to the docs. Making it an executable is an important step!
