### ISSUE TITLE
Issues B2 command tool on Linux

### ISSUE THREAD

**Issue by lgcanovas** [Backblaze/B2_Command_Line_Tool#677]
I installed it and i got this:

lara.garcia@ubuntudesktop16:~$ b2 -version
Traceback (most recent call last):
File "/usr/local/bin/b2", line 7, in
from b2.console_tool import main

Can you tell me how to solve this?
Ubuntu 18.4. Technicians from BackBlaze say there are issues with Python/Linux

By the way, I run pip install b2 to install, how can I remove it?

Regards
Lara

**Comment by ppolewicz** [comment]
duplicate of https://github.com/Backblaze/B2_Command_Line_Tool/issues/675#issuecomment-753835436
