### ISSUE TITLE
Script snippet or method for sending email alerts on success/failure/error conditions?

### ISSUE THREAD

**Issue by cvocvo** [Backblaze/B2_Command_Line_Tool#679]
I'd like to run a b2 command via a bash script or directly via cron on a schedule to offsite some photos from my NAS.
Does anyone have a working method for sending email alerts when B2 has success / failure / errors?  Perhaps a shell script or python script that parses output and can send an email alert via postfix or something else (I'm not picky)?

Thank you!
Chris

**Comment by mjurbanski-reef** [comment]
The magic of command line tool, especially on UNIX-like systems, is that it can be combined with other tools.
My advice would be to gather the whole output of the command, but only send it if `b2` exit code is not 0.

A potential script would go be something like this (disclaimer: NO GUARANTEES that it works at all):
```
#!/bin/bash

DIR_TO_BACKUP="/path/to/local/photos"
BUCKET_NAME="b2://your-bucket-name"
EMAIL="your-email@example.com"

# Sync photos to B2 and capture the output
OUTPUT=$(b2 sync $DIR_TO_BACKUP $BUCKET_NAME 2>&1)

# Check the status of the sync
if [ $? -eq 0 ]; then
    echo -e "Backup to B2 was successful.\n\n$OUTPUT" | mail -s "B2 Backup Success" $EMAIL
else
    echo -e "Backup to B2 failed.\n\n$OUTPUT" | mail -s "B2 Backup Failure" $EMAIL
fi
```
