### ISSUE TITLE
b2 2.1.0 Windows version executable is missing dateutil-zoneinfo package

### ISSUE THREAD

**Issue by dgcom** [Backblaze/B2_Command_Line_Tool#689]
Using latest b2-windows executable on Window 10.0.18363.1379:

    >b2-windows.exe version
    b2 command line tool, version 2.1.0
    >b2-windows.exe authorize-account <account> <master_key>
    Using https://api.backblazeb2.com
    dateutil\zoneinfo\__init__.py:26: UserWarning: I/O error(2): No such file or directory

Checking with Process Monitor shows that embedded python is looking for this file:

    dateutil\zoneinfo\dateutil-zoneinfo.tar.gz

Tool seems to still work, so the issue is probably cosmetic.

**Comment by nathanpc** [comment]
This issue is still present in version 2.4.0 of the binary.

**Comment by mlech-reef** [comment]
In the next release, the warning should not appear anymore.
