### ISSUE TITLE
Include b2sync here?

### ISSUE THREAD

**Issue by booi** [Backblaze/B2_Command_Line_Tool#69]
It would be great if b2sync were included in this repo or perhaps a separate repository since it's a C++ program?

**Comment by ppolewicz** [comment]
This repository is for B2 command line tool. Putting the binary here would complicates things in the release process, require cross-committing etc.

Would it be enough to provide a link from our README to b2sync tool? This way users would have a way to find out about one tool when looking at the other without storing two different products in one repository.

**Comment by bwbeach** [comment]
We do plan on putting b2sync in github at some point.  It will be its own repository.  I'll pass on the request to the owner of that code.
