### ISSUE TITLE
Add a pricing calculator or estimate parameter/option to CLI functions

### ISSUE THREAD

**Issue by geekpete** [Backblaze/B2_Command_Line_Tool#690]
The ability to "dry run" an operation and output some pricing report/estimate associated with the particular action.

**Comment by ppolewicz** [comment]
Could you provide an example on how you would use it? The cost of `list_bucket` depends on the amount of objects in the bucket and provided parameters. We could maybe output the usage information after the operation is finished, but there is no way for the CLI to be able to reliably predict all costs before making the call (though B2 is generally cheaper than anything else, so I usually just accept that it can't be much better than B2 anyway).

**Comment by geekpete** [comment]
I see this isn't too practical. I didn't have a specific use case in mind, but I guess the general idea was to be able to do some kind of dry run ahead of actually spending some full amount to see if there was any unexpected cost associated with some large/complex/deeply nested transfer you were about to do. I also get your point that even if there was, it's not so likely you'd find much cheaper than B2 anyway.

Cost stats after the transfer might be nice to see, but this might be easier with some kind of usage tagging where you add some tags to your command and then you can filter cost breakdown by specific tags from Backblaze web UI or dump a csv/json usage+cost breakdown file from UI or API (or have it turn up in a specific bucket) to analyze yourself with whatever tools.

So I think we're good to close this one off.

**Comment by ppolewicz** [comment]
We could build a better cost account infrastructure into the CLI but nobody seems to be very interested in this information, so the motivation to build it is just not there. Not worth to build it if nobody is going to use it.

As you say, a server-side version of cost accounting could be even better.
