### ISSUE TITLE
Support server-side encryption

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#691]
As https://www.backblaze.com/b2/docs/server_side_encryption.html has just been released, we need to look into supporting it in b2cli/b2sdk. I've taken a look at the docs and found that there are a few things that need to be done:

SSE-B2:
- [x] make sure `b2sdk.B2Api.list_buckets`, `update_bucket`, and `create_bucket` return the information about the current encryption setting
- [x] test if the above work for keys with `readBucketEncryption`, both for encrypted and non-encrypted bucket
- [x] make sure `isClientAuthorizedToRead` is returned where appropriate
- [x] add `defaultServerSideEncryption` / `--default-server-side-encryption=AES256|none"` parameter to `create_bucket` and `update_bucket`
- [x] handle a new parameter in object creation operations (`b2_upload_file`/`b2_start_large_file`/`b2_copy_file` + sync) to enable SSE-B2 for the particular request

SSE-C:
- [x] add encryption key parameter to `b2_upload_file`, `b2_start_large_file`, `b2_download_file_by_id`, `b2_download_file_by_name` 
- [x] add six encryption key parameters to `b2_copy_file` and `b2_copy_part` and `sync`

CLI parameters:
- `--encryption-mode-source=SSE-B2|SSE-C|CSE` (CSE for client side encryption will come in the future)
- `--encryption-algorithm-source=AES256` - this is going to be default if encryption mode is selected
- `B2_ENCRYPTION_KEY_SOURCE` - env variable with the key for reading (or for the first bucket, if it's `copy` or `sync`)
- `--encryption-mode-destination=SSE-B2|SSE-C|CSE` (CSE for client side encryption will come in the future)
- `--encryption-algorithm-destination=AES256` - this is going to be default if encryption mode is selected
- `B2_ENCRYPTION_KEY_DESTINATION` - env variable with the key for writing (or for the second bucket, if it's `copy` or `sync`)

**Comment by ppolewicz** [comment]
if someone calls `b2 upload-file --sse-c-encryption-key "$cipher" ... ...` and another user on the same machine (with a default linux kernel) runs `ps awux` they will see the key, therefore I suggest that the CLI gets the encryption key through an environment variable only.

**Comment by ppolewicz** [comment]
For `b2 sync` there seems to be no sensible way for the CLI to manage the keys. b2sdk can have callbacks for it, but b2cli will have a very simple implementation for it

**Comment by mlech-reef** [comment]
> if someone calls b2 upload-file --sse-c-encryption-key "$cipher" ... ... and another user on the same machine (with a default linux kernel) runs 
It's always nice to have both

**Comment by mlech-reef** [comment]
We use camel-case parameters all over the B2 CLI interface.

**Comment by rmahmad** [comment]
Quick question - does this mean that SSE-C is not supported via the b2 CLI right now?

**Comment by ppolewicz** [comment]
Both SSE-B2 and SSE-C are supported (for a long while now).

**Comment by rmahmad** [comment]
Cool, thanks. How can I set the encryption key when uploading a file? I’m probably missing something here sorry

**Comment by ppolewicz** [comment]
```
B2_DESTINATION_SSE_C_KEY_B64='key here' B2_DESTINATION_SSE_C_KEY_ID='key id here' b2 upload-file bucket_name my/file/path.txt destination/path.txt
```
While it is possible to skip `B2_DESTINATION_SSE_C_KEY_ID`, I recommend always setting it, even if you do `B2_DESTINATION_SSE_C_KEY_ID="$HOSTNAME/$USER"` it may save you a lot of trouble later on.

Also please see the docs for it [here](https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html)
