### ISSUE TITLE
b2 download-file-by-name giving ConnectionResetError(54, 'Connection reset by peer')

### ISSUE THREAD

**Issue by bimbashrestha** [Backblaze/B2_Command_Line_Tool#698]
Perhaps this is temporary Backblaze datacenter issue but I get 
```
ConnectionResetError(54, 'Connection reset by peer')
```
when trying to download a file using 
```
b2 download-file-by-name
```

I'm using my master key to authorize and I can confirm that I can `ls` the file I want to download just fine. Just can't actually download it.

**Comment by ppolewicz** [comment]
It seems to be a problem with your network or with the Backblaze server. Is this happening for the new uploaded files as well?

**Comment by bimbashrestha** [comment]
Hi @ppolewicz thanks for the response. Yes, for new files too. I run into the same issue when trying to download a file using rclone or the b2 python sdk directly so this might not be a cli issue. Talking to b2 support now

**Comment by bimbashrestha** [comment]
Looks like this isn't a B2 issue or a cli issue. Still don't have the fix but I've narrowed it down to my computer. The same command using the same credentials from another computer work just fine. I'm going to close this
