### ISSUE TITLE
Authorization token has expired

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#7]
I started using b2 tool on a daily basis for testing and each session I need to authorize again. I've checked the code and it would seem that b2 command line tool does not save the Application Key. Additionally there is no automated handling for an expired token, so the command line tool user needs to observe error messages and reauthorize by himself.

Can I add an option to save the Application Key persistently and request a new token when necessary if HTTP 401 code is received?

Could that option be enabled by default?

**Comment by ppolewicz** [comment]
@bwbeach ?

**Comment by bwbeach** [comment]
Sorry for the delay -- it's been a busy week...

I think we're ok with that.  You can go ahead and store it in the dot file.

- BrianB

**Comment by ppolewicz** [comment]
I've been trying to do this before #4, but auth token is being passed everywhere. It will be much easier to do this after #4 is finished.

**Comment by lukavia** [comment]
Is there any progress on this? 
Currently I get:
`AttributeError: 'StoredAccountInfo' object has no attribute 'authorize_automatically'`

I would like to eventually make b2 backup run by cron

**Comment by ppolewicz** [comment]
This is done in some places, but not everywhere yet. A refactoring to use `requests` is underway and it should take care of finishing this in the coming weeks.

**Comment by svonohr** [comment]
I'm also having problems with expiring authentication tokens. After some studying of the code (I'm definitely not a Python expert) I found that the `B2Session` class is supposed to re-authenticate in those cases. However, inside the `Bucket` class I find many instances where direct calls to the `raw_api` are made. Shouldn't those calls go through the session wrapper?

**Comment by ppolewicz** [comment]
you are right

**Comment by ppolewicz** [comment]
hm. Maybe you would like to fix it? We provide tests and code review.

**Comment by svonohr** [comment]
Yes I can try. Should I just send a pull request or what's the preferred method?

**Comment by ppolewicz** [comment]
Pull request is a preferred method.

Please run `pre-commit.sh` before pushing.
