### ISSUE TITLE
I/O error message is printed with every command on Windows

### ISSUE THREAD

**Issue by malaysf** [Backblaze/B2_Command_Line_Tool#706]
We've had several reports of the Windows version of the B2 Command-Line Tool printing an I/O error messages with every command.  Despite this message, the commands execute properly.

Here's a sample from the QA team:
```
C:\Users\Administrator\Downloads>b2-windows version
b2 command line tool, version 2.3.0

C:\Users\Administrator\Downloads>b2-windows authorize-account --staging <keyID> <applicationKey>
Using https://api.backblaze.net
dateutil\zoneinfo\__init__.py:26: UserWarning: I/O error(2): No such file or directory

C:\Users\Administrator\Downloads>b2-windows list-buckets
dateutil\zoneinfo\__init__.py:26: UserWarning: I/O error(2): No such file or directory
ecf32b11d58fd818728b0217  allPrivate  1-Terabyte

C:\Users\Administrator\Downloads>b2-windows list-keys
dateutil\zoneinfo\__init__.py:26: UserWarning: I/O error(2): No such file or directory

```

**Comment by ppolewicz** [comment]
Looks like https://github.com/arrow-py/arrow/issues/353#issuecomment-783582071 which is only triggered when using the binary one-file version of the cli.

@malaysf did any of the python users (who install cli via `pip install -U b2`) report this issue, or is it specific to the binary version?

**Comment by mlech-reef** [comment]
Duplicates #689
