### ISSUE TITLE
Do not use Ubuntu 16.04 runner in CD as it is deprecated

### ISSUE THREAD

**Issue by mlech-reef** [Backblaze/B2_Command_Line_Tool#724]
Ubuntu 16.04 is now deprecated in GitHub Actions.
We use it now to create a binary with `pyinstaller` in order to use older `glibc` version so our bundle works even on older OSes (see [this](https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible) for details).

We can either:
* use Ubuntu 18.04 and drop support for OSes with older `glibc`
* use Docker runner with Ubuntu 16.04
* use `staticx` and create a fully-static binary

**Comment by chenrui333** [comment]
Ubuntu 16.04 is EOL this April, so it would be good to use at least Ubuntu 18.04. 

Any reason why the CI/CD workflows are not using the latest OS versions (for linux, macOS, and windows)？

**Comment by mlech-reef** [comment]
@chenrui333 please refer to the linked `pyinstaller` documentation from the issue description why we use the oldest possible OS version for bundling the binary.

For Linux, we are going to make the binary fully static, so then we can switch to `ubuntu-latest`. We did similar thing in our other [project](https://github.com/Backblaze/terraform-provider-b2) already
