### ISSUE TITLE
b2 conflicts with my C++ Boost related b2 command

### ISSUE THREAD

**Issue by hanyoonLDA** [Backblaze/B2_Command_Line_Tool#732]
Any way I can change the CLI command b2 to something else?

**Comment by ppolewicz** [comment]
I know [ubuntu](https://packages.ubuntu.com/impish/backblaze-b2) and some other distros renames it to `backblaze-b2`. We've made it easier to rename it like two years ago, but I don't remember exactly how, you may want to look at the diff they are applying on our source when packaging it into .deb

**Comment by hanyoonLDA** [comment]
Ah, gotcha. Thanks again :)
