### ISSUE TITLE
Use b2sdk's TempDir in tests

### ISSUE THREAD

**Issue by mpnowacki-reef** [Backblaze/B2_Command_Line_Tool#733]

**Comment by mpnowacki-reef** [comment]
Also make it use pathlib

**Comment by mjurbanski-reef** [comment]
b2sdk TempDir has been deprecated.

Instead, https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html should be used in tests, and https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory in production code .
