### ISSUE TITLE
Debugging info with --verbose lost?

### ISSUE THREAD

**Issue by philh7456** [Backblaze/B2_Command_Line_Tool#740]
With version 3.0 there has been a change in the output to stdout when using --verbose. Prior to version 3, when using --verbose there would be extensive output after the "INFO:__main__:starting" entry, with seemingly every transaction logged. Now the extra logging ends immediately after "INFO:__main__:starting".

I see from the changelog that there have been some changes to the logging output, but I'm not clear from these whether the changes described above are intended? If intended, is there anyway to get the missing info output to stdout (rather than to b2_cli.log)?

**Comment by mpnowacki-reef** [comment]
Thanks for catching that, it's fixed now.
