### ISSUE TITLE
Installation Instructions should say to use the standalone binaries

### ISSUE THREAD

**Issue by philh7456** [Backblaze/B2_Command_Line_Tool#741]
Would it not be better for the Installation instructions to say to use the standalone binaries rather than pip, or at least show them as an option?

**Comment by ppolewicz** [comment]
This is very true. It's a small change and the highest value was to figure out that it should be done. Would you like to suggest an appropriate wording? I think it's only due that the credit for this change goes to you :)

**Comment by philh7456** [comment]
Thank you. How about:

Stand-alone binaries are available for Linux, MacOS and Windows, and most people will want to install these. The latest versions are available for download from the Releases page.

Alternatively, you can install with:

pip install b2

Note: I'm assuming the Darwin version is for MacOS, if not please correct.

**Comment by lhsazevedo** [comment]
Fixed in #743
