### ISSUE TITLE
"ERROR: No such bucket" when uploading 

### ISSUE THREAD

**Issue by pgonin** [Backblaze/B2_Command_Line_Tool#76]
__after updating to b2 command line version 0.4.4 from 0.3.0 using pip install and removing manually copied intial b2 script__

Given that I authorize to my account with
```bash
$ b2 authorize_account someAccountId
```
and provide application key interactively

and that I check authorization by listing bucket content with
```bash
$ b2 ls someBucketName
objectName1
objectName2
...
```

I fail to upload new objects with 
```bash
$ b2 upload_file --contentType b2/x-auto someBucketName filenameLocal filenameRemote
ERROR: No such bucket:  someBucketName
```
I checked with someBucketId with same result

I also check to clear account and authorize again with same result.
I double checked man pages to make sure I got it right, I noticed the command line options changes (for contentType) and I think command line syntax is ok

**Comment by ppolewicz** [comment]
@pgonin does the same happen if you don't specify the `--contentType` option?

**Comment by pgonin** [comment]
same issue if --contentType option is not specified
```bash
$ b2 upload_file someBucketName filenameLocal filenameRemote
ERROR: No such bucket: someBucketName
```

**Comment by pgonin** [comment]
I don't have the issue on a newly created bucket
```bash
$ b2 create_bucket myNewBucket allPrivate
xxxxxxxxxxxxxxxxxxxxxxxxx
```
```bash
$ b2 upload_file myNewBucket filenameLocal filenameRemote
```
=> upload in progress

**Comment by pgonin** [comment]
I like the new progress bar based on tqdm btw... very nice improvement of UI

**Comment by ppolewicz** [comment]
We have automated tests which we run before release and those perform uploads many times.

We have no logic which would distinguish old buckets from newly created ones.

I suspect that you are not the owner, or are not properly authorized to the right account, to `someBucketName` bucket. Can you somehow confirm that the name of the bucket is spelled properly?

If you will confirm that this is all ok, then please contact b2 support by email and share your account data and exact bucket name. It seems like the cloud-side issue.

**Comment by pgonin** [comment]
I confirm this is my bucket (I can list content) and I previously uploaded objects without issues (using 0.3 version of b2 cli)
I will contact b2 support to report my issue.

**Comment by bwbeach** [comment]
Contacting support is the best plan.  That can look at your bucket and see if there are any problems.

The other thing that can cause uploads to fail is when you hit your storage cap.  You might want to check the Caps & Alerts in your account at backblaze.com.

**Comment by ppolewicz** [comment]
If the limit was really hit, user should get a more appropriate error message than "No such bucket". Testing corner cases is not something we focused closely though...

**Comment by ppolewicz** [comment]
@pgonin can you confirm whether it was the storage cap issue or not?

**Comment by pgonin** [comment]
@ppolewicz sorry I did not follow up, I missed your question. I confirm it is not a storage cap issue.

**Comment by svonohr** [comment]
So the problem still exists with the newest B2 CLI version? I think I had a similar issue when I deleted a bucket through the web interface. The client still had the bucket name cached and somehow the sync command saw an empty bucket and started uploading all the local files, which of course failed. So one thing you could try is to delete the `.b2_account_info` file in your home directory. This will clear all cached information, so you have to reauthorize your account after that.

**Comment by ppolewicz** [comment]
In this case the bucket contents were successfully listed just before the error was encountered

**Comment by ppolewicz** [comment]
I am closing this as irreproducible. If anyone manages to reproduce it, please provide logs so that we can investigate. A procedure on how to enable logs can be found [here](https://github.com/Backblaze/B2_Command_Line_Tool#detailed-logs). (as of writing this, version that supports `--debugLogs` flag is not yet installable via pip - we'll probably release it next week)

**Comment by theonewolf** [comment]
This kind of hit me today.

I re-authorized, and put my bucket name in double-quotes, and it magically started uploading.
