### ISSUE TITLE
Wal-e integration

### ISSUE THREAD

**Issue by mathiasrw** [Backblaze/B2_Command_Line_Tool#77]
I would love to back up my postgres db on B2. 

If you ever feel like giving more reasons to why B2 is awesome you could look into expanding  https://github.com/wal-e/wal-e/ with a B2 backend.

**Comment by bwbeach** [comment]
Thanks for the suggestion.  Extending WAL-E to support B2 is a great idea.  

At Backblaze, we have a lot of requests to build integrations, but limited resources.  I'll make sure this one is on the list.  With luck, somebody will go ahead and contribute an extension to WAL-E for B2.

**Comment by mathiasrw** [comment]
:+1:

**Comment by qeternity** [comment]
https://github.com/qeternity/wal-e

I have started a fork with B2 functionality. Right now basic uploading functionality works.

**Comment by ibayer** [comment]
@qeternity 
Thanks for sharing the B2 upload functionality. 
Did you test if https://github.com/gaul/s3proxy (B2 has limited support) could allow us to use wal-e S3 support with B2?

**Comment by qeternity** [comment]
@ibayer that's not really an ideal solution. It requires packaging and running a separate process. Building native support in wal-e is far more preferable.

**Comment by tiingo** [comment]
+1 for this integration.  Is there some bandwidth to commission somebody to build this similar to Python-SDK. @qeternity has done a great job, but would be great to have official support
