### ISSUE TITLE
Possible to upload sparse file?

### ISSUE THREAD

**Issue by SysEngDan** [Backblaze/B2_Command_Line_Tool#773]
I have a 500GB sparse file that only have 5GB of space used. `b2` attempts to upload full size file (500GB) when there's only actually 5GB of data. You can see this when you run `ls -lhs`.

Any thoughts as to how I can configure `b2` to upload only 5GB?

**Comment by SysEngDan** [comment]
I just discovered a potential workaround: Create a single tar archive first and then upload only the tar archive. `tar cSf backup.tar *`. This results in a single tar archive where the actual and allocated file size are the same, 5GB.

**Comment by ppolewicz** [comment]
B2cli doesn't support sparse files. You might have more luck with software which supports variable-size block deduplication (check out duplicity, maybe?) if you really need to backup those.

Uploading a tar file is a possible workaround, but just using `b2 sync` on those files might be a better idea - this way the files which have not changed will not be transferred again, so incremental backup will be much less taxing on the source node (and you'll save storage, though depending on numerous conditions single tar file restore performance may be different from sync - if you have a ton of tiny files, tar will generally be faster).
