### ISSUE TITLE
Remove the use of `set_thread_pool_size` when adopting b2sdk v3 (or earlier)

### ISSUE THREAD

**Issue by awierzbicki-reef** [Backblaze/B2_Command_Line_Tool#774]
This method is not a part of public API and will probably be removed b2-sdk-python apiver v3. The preferred way to set number of threads for copy/download/upload is by using `max_copy_workers`/`max_download_workers`/`max_upload_workers` parameters for `B2Api.__init__`.

**Comment by mjurbanski-reef** [comment]
We opted to keep this function and make it official. There are caveats to it tho, so anyone daring enough to use it should carefully read the documentation of it first.
