### ISSUE TITLE
ARM binary for Linux

### ISSUE THREAD

**Issue by jaapmarcus** [Backblaze/B2_Command_Line_Tool#776]
With the popularity of ARM64 with Raspberry PI and many cloud providers it is slowly getting more popular...

-bash: /usr/local/bin/b2: cannot execute binary file: Exec format error

Are there any plans for adding an arm64 version for Linux?

**Comment by ppolewicz** [comment]
Hi,

you can `pip install b2` almost anywhere.

If you'd like to implement a change in the binary build script so that it works correctly on ARM as well as on i386, your contribution would be welcome.

**Comment by nodesocket** [comment]
See also my issue about Apple Silicon _(arm64)_ support https://github.com/Backblaze/B2_Command_Line_Tool/issues/761

**Comment by mjurbanski-reef** [comment]
Please note the "standalone" binary is mostly for install convince and does not offer any performance benefits. While we are open to contributions implementing this, we have no plans to do so ourselves.
