### ISSUE TITLE
Sync fails on broken symlink (even with --excludeAllSymlinks)

### ISSUE THREAD

**Issue by dcowan-london** [Backblaze/B2_Command_Line_Tool#780]
Hi,

I have some broken symlinks. When I run a sync, I get `WARNING: {path} could not be accessed (broken symlink?)`.

After the WARNINGS, `b2-linux` just exits. With `--debug` on, I get `INFO:__main__:\\ ========================================  exit=0  ======================================== //`.

This seems to be the same as #517 .

**Comment by flyingwolf79** [comment]
Any chance you can include the full command you are running along with a quick rundown of the locations?
The excludeAllSymlinks will ignore symlinks when syncing from the local source only.

**Comment by dcowan-london** [comment]
`/root/b2-linux sync --keepDays $KEEPDAYS --replaceNewer --excludeAllSymlinks  /etc/ b2://{bucket}/{dir} --verbose`

**Comment by dcowan-london** [comment]
`$KEEPDAYS` is 30

**Comment by ppolewicz** [comment]
It would appear that you've already synced everything (except for the broken symlinks). Isn't that the case? To test this you could create a file such as `ZZZZ` and then run the sync again with debug to see if it will be uploaded.
