### ISSUE TITLE
sync question

### ISSUE THREAD

**Issue by st4302** [Backblaze/B2_Command_Line_Tool#781]
Hello,

I normally use sync to upload data to the buckets I have. I was wondering if I sync a directory to a bucket and then delete a file in the source directory would that file be deleted from the destination bucket next time I run sync?

Thank you

**Comment by ppolewicz** [comment]
It depends on whether you use a `--delete` switch or not. Please see various sync option to control that behavior. Also you might want to see the documentation of lifecycle rules of B2, those can be quite handy.
