### ISSUE TITLE
Failed to execv() after install

### ISSUE THREAD

**Issue by mstojanovv** [Backblaze/B2_Command_Line_Tool#788]
Hello,

I'm encountering a strange issue after installing B2.

OS: Ubuntu 20.04
arch: amd64
user: root

The installation steps:

```
wget https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v3.2.1/b2-linux
mv b2-linux /usr/local/bin/b2
chmod +x /usr/local/bin/b2
```

Perform test:

`b2 --help`

Getting the following error:

`Failed to execv() /tmp/staticx-FHgLIB/b2: Permission denied`

Note that the error is not thrown only when running the `b2 --help` command, it does happen on all commands e.q.

```
root@server:~# b2 --help
Failed to execv() /tmp/staticx-FHgLIB/b2: Permission denied
root@server:~# b2 authorize-account
Failed to execv() /tmp/staticx-jcKhbb/b2: Permission denied
root@server:~#
```

Any ideas?

Thanks

**Comment by clunkclunk** [comment]
Hey, I know this is an old post, but I came across the same issue on a Synology today.

The issue is that b2 needs /tmp to allow executable files. To resolve it, I just remounted it with the exec flag while live:

`mount -o remount,exec /tmp
`

**Comment by ppolewicz** [comment]
mystery finally solved by @clunkclunk - nice job!
