### ISSUE TITLE
SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by cioionut** [Backblaze/B2_Command_Line_Tool#793]
Hello,

I received a `SignatureDoesNotMatch` error when I try to make an HTTP request using S3 Compatible pre-signed URL generated with aws-sdk v3.

Here is the code that I'm using to generate pre-signed URLs:

```js
import 'dotenv/config';
import {S3Client, GetObjectCommand} from "@aws-sdk/client-s3";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";

const s3Client = new S3Client({
    endpoint: "https://s3.us-west-004.backblazeb2.com",
    region: "us-west-004",
});

const s3Params = {
    Bucket: 'my-bucket',
    Key: 'my_image.jpg',
    Expires: 600, // Expires in 10 minutes
};

const command = new GetObjectCommand(s3Params);
getSignedUrl(s3Client, command).then(result => console.log(result));
```
Of course, I set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` with Backblaze `keyID` respectively `applicationKey` in `.env` located next to the file with the above script.

I suspect that this error seems to arise due to the nature of the `applicationKey` content. From what I see the application key contains special characters like `/`. When I try with other keys that do not contain `/` the pre-signed URLs work just fine, even with special characters like `+` in the `applicationKey`, so I think the `/` causes some issues in the signature generation.

I don't know where is the right place to signal this issue.
I appreciate your work and I like your service! More competition for the big players! Thank you!

**Comment by ppolewicz** [comment]
Hey,

this is an issue section of a github repository for the b2 cli which is built on top of the b2 native api, written in python. Your thing seems to be using aws cli, S3 interface and javascript. I'd like to help you, but I have like zero experience with these. I suggest that you try backblaze support or aws sdk repo issue section.
