### ISSUE TITLE
No "sse_c_key_id" in "fileInfo" when uploading large files with SSE-C

### ISSUE THREAD

**Issue by Jakub-KK** [Backblaze/B2_Command_Line_Tool#795]
**Environment / versions:**
b2 version
b2 command line tool, version 3.4.0 _(self-contained download for Windows)_

python --version
Python 3.10.0

Windows: 10 Pro 21H2

**Steps:**
1. Use server-side encryption with customer-managed keys (SSE-C), set environment variables according to [doc](https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html), _key_id_ is name of the key for further identification (useful if key changes in the future)
`set B2_DESTINATION_SSE_C_KEY_B64=<base64_encoded_key_data>`
`set B2_DESTINATION_SSE_C_KEY_ID=key_id`
2. Create test large file (200MB), upload large file using SSE-C
`openssl rand -out large_file_name 200000000`
`b2 upload-file --destinationServerSideEncryption SSE-C bucket_name large_file_name large_file_name`

Check output of the command (particularly "fileInfo" dict)

**Expected:**
"fileInfo" of uploaded file should contain "sse_c_key_id" with key_id taken from env variable B2_DESTINATION_SSE_C_KEY_ID - according to documentation of upload-file ([https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html](https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html)):
>If B2_DESTINATION_SSE_C_KEY_ID environment variable is provided, it’s value will be saved as sse_c_key_id in the uploaded file’s fileInfo.

**Actual:**
"sse_c_key_id" is not present in "fileInfo" when uploading large file with SSE-C

**Notes:**
For files smaller than 200MB the "sse_c_key_id" is in fact created automatically in "fileInfo" when uploading with SSE-C.
The 200MB threshold for small/large file is taken from documentation of upload-file.

**Comment by ppolewicz** [comment]
in large file upload `file_info = server_side_encryption.add_key_id_to_file_info(file_info)` is not being called. It's called in raw_api for small uploads and also in copy manager, but not in large files. It may be a mistake to call it in raw_api, it's caller should be aware of what headers are being put in - then the upload/copy managers would be responsible for assembling the fileInfo dict.

Proper fix for this requires consultation with a developer that is flying right now, I'll talk to him when he lands properly.

**Comment by mjurbanski-reef** [comment]
Resolved in b2sdk>=[1.24.1](https://github.com/Backblaze/b2-sdk-python/compare/v1.24.0...v1.24.1)
