### ISSUE TITLE
~/.b2_account_info is not truncated when being written, clear_account doesn't work

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/B2_Command_Line_Tool#8]
If `~/.b2_account_info` is being rewritten, the file beginning is being written properly, but the rest of the file contents doesn't go away. Loading such file works as intended, so the file is not seriously corrupted, but this way it will never shrink.

```bash
$ ./b2 clear_account
$ cat ~/.b2_account_info ; echo
{}
   "account_auth_token": "XXX", 
    "account_id": "YYY", 
    "api_url": "https://api001.backblaze.com", 
    "download_url": "https://f001.backblaze.com"
}
```
It seems to be a regression after #6 

Fix is in #9.

**Comment by ferricoxide** [comment]
Looks like the clear function isn't actually nulling the file:

~~~
jonest@deluge ~
$ !b2
b2 clear_account

jonest@deluge ~
$ !cat
cat .b2_account_info
{}
~~~
The regression in #6 would be that it's assuming the file is either already nulled or absent when it opens the file to update it.

**Comment by ferricoxide** [comment]
Had selected incorrect write mode on file-open. Updated and submitted PR #10
