### ISSUE TITLE
Break source code into multiple files

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#80]
Having all of the code in a single file is awkward.  And now that it can be installed with `pip`, there is no longer a need to have it all in a single file to make downloading easy.

**Comment by bwbeach** [comment]
For unit tests, we can make a `tests` directory, and `setup.py` will know how to run them.

I'm not sure how to test running it as a command.  Once we have unit tests, they can handle most of the testing of the internal logic, but I'd still like to have a way to test passing in command-line arguments.  We probably need just a couple test cases for it.

One thing I've seen is to have a test script that sets PYTHONPATH to the source directory, and then uses "python -m" to run the module as a command line.  I think this might work.

**Comment by ppolewicz** [comment]
Travis CI already installs the command line tool, so adding it to PYTHONPATH should not be needed in such case.

We should sync all forks before breaking down the file into pieces. I don't have much in the works currently. Do you plan to cut it any time soon? I think it is better if you do it (given the IDEs that we use).

**Comment by bwbeach** [comment]
It looks like there's not much happening now.  I'll plan on breaking up the code Monday afternoon (Hawaii time), which is very early Tuesday morning UTC.

If that will cause conflicts, let me know.
