### ISSUE TITLE
Most recent release crashes in toolbox

### ISSUE THREAD

**Issue by K4rakara** [Backblaze/B2_Command_Line_Tool#817]
# Issue

I get the following exception when trying to run the latest release of b2 from github:
```
Traceback (most recent call last):
  File "b2/console_tool.py", line 2829, in <module>
  File "b2/console_tool.py", line 2814, in main
  File "b2/console_tool.py", line 2644, in run_command
  File "argparse.py", line 1826, in parse_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "b2/arg_parser.py", line 87, in error
  File "argparse.py", line 2556, in print_help
  File "argparse.py", line 2562, in _print_message
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 1158: ordinal not in range(128)
[10393] Failed to execute script 'console_tool' due to unhandled exception!
```

# Environment

OS: Arch Linux toolbox container on Fedora Silverblue 36
Release: 3.5.0

Note that I only encounter the exception in a toolbox

**Comment by ppolewicz** [comment]
What command did you run?

**Comment by K4rakara** [comment]
This is from running just `b2`, but it occurs with all commands.

**Comment by ppolewicz** [comment]
Python thinks your terminal is extremely limited in terms of what it can display ("ascii" encoding) and the help message contains a character that looks like `*` but it actually isn't just a `*`. I can patch that but I suspect you'll have plenty of problems in this environment, not just with b2 command line tool

**Comment by ppolewicz** [comment]
This is not a new issue - that funny dot is with us since some version between 2.1.0 and 2.5.1, so a year or so.

**Comment by ppolewicz** [comment]
Ok, I did check it closely and it seems that your terminal is just misconfigured. We already support limited terminals - when I run `LC_ALL=c b2 -h`, I get ascii-compatible output. What happened in your case is that some parts of python think that your terminal is capable of displaying unicode and some don't.

**Comment by K4rakara** [comment]
That sounds likely to me. Toolbox is a wrapper around podman with some magic added, and podman tends to have issues with some programs (eg cargo) thinking the terminal is much more limited than it is. Thanks for getting to this so quickly.

**Comment by ppolewicz** [comment]
Try `LC_ALL=en_US.UTF-8 b2 -h`

**Comment by K4rakara** [comment]
Same result there. Gonna close this since its just a matter of unsupported environment.
