### ISSUE TITLE
Error when directory name contains non-ASCII characters?

### ISSUE THREAD

**Issue by Rolf-Smit** [Backblaze/B2_Command_Line_Tool#840]
I'm using the `sync` command to sync a folder to my local storage, however some of my directories within B2 have special character names such as: `ë`.

My path name basically looks like this:
`[bucket]/foo/bar/sp\xebcial/somefile.txt`

I'm using the CLI tool from within an Ubuntu 22.04 Docker container.

Full trace:

```
b2_download(backups/foo/bar/sp\xebcial/somefile.txt, 4_zc3ddcaf95cdc628f68f10b13_f108ab7db0721e3e0_d20200117_m000151_c003_v0312001_t0025, /backblaze-encrypted/foo/bar/sp\xebcial/somefile.txt, 1579219311000): UnicodeEncodeError('ascii', '/backblaze-encrypted/foo/bar/sp\xebcial/somefile.txt', 75, 76, 'ordinal not in range(128)') 'ascii' codec can't encode character '\xeb' in position 75: ordinal not in range(128)
WARNING:b2sdk.scan.report:could not output the following line with encoding ascii on stdout due to 'ascii' codec can't encode character '\xeb' in position 82: ordinal not in range(128): b2_download(backups/foo/bar/sp\xebcial/somefile.txt, 4_zc3ddcaf95cdc628f68f10b13_f116025563e884806_d20200117_m000152_c003_v0312000_t0013, /backblaze-encrypted/foo/bar/sp\xebcial/somefile.txt, 1579219312000): UnicodeEncodeError('ascii', '/backblaze-encrypted/foo/bar/sp\xebcial', 75, 76, 'ordinal not in range(128)') 'ascii' codec can't encode character '\xeb' in position 75: ordinal not in range(128)
```

**Comment by ppolewicz** [comment]
This looks like a problem with your terminal. Does your terminal allow you to list a file with that special character?

**Comment by Rolf-Smit** [comment]
With terminal are you referring to the the terminal being able to print a special character? because based on the warning shown in the trace, that does not seem to be supported, however if you look at the first line it already breaks down earlier.

I found another example and got a better trace:

```
 'ordinal not in range(128)') 'ascii' codec can't encode character '\xe9' in position 54: ordinal not in range(128)
backblaze-download_1  | ERROR:b2sdk.sync.action:an exception occurred in a sync action
backblaze-download_1  | Traceback (most recent call last):
backblaze-download_1  |   File "b2sdk/sync/action.py", line 48, in run
backblaze-download_1  |   File "b2sdk/sync/action.py", line 252, in do_action
backblaze-download_1  |   File "b2sdk/sync/action.py", line 239, in _ensure_directory_existence
backblaze-download_1  |   File "os.py", line 225, in makedirs
backblaze-download_1  | UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 54: ordinal not in range(128)
```

`_ensure_directory_existence` seems to be a big clue.

**Comment by Rolf-Smit** [comment]
Did some further research and I found that the folder (in my previous example) that was uploaded to B2 contains:

```
U+0065 | e | LATIN SMALL LETTER E
U+0301 | ́  | COMBINING ACUTE ACCENT
```

**Comment by ppolewicz** [comment]
B2 cli can handle it if your terminal can - but it's set to 'ascii' which doesn't handle much

**Comment by ppolewicz** [comment]
or maybe it's your operating system that is not capable of writing those down - can you please try to create a file by yourself on that filesystem with the unicode char in the name and list it to make sure it works?

**Comment by Rolf-Smit** [comment]
Does this CLI under the hood use the terminal input and output to list files? Python does not offer a "native" way to accomplish this?

I usually don't really think of a terminal as being the limiting factor in what a piece of software can do. I usually think of the terminal as the input and output of software, not so much it limiting the internal functions of software.

But I will check to see what the terminal supports.

**Comment by Rolf-Smit** [comment]
So I was able to solve this by forcing my docker container to use UTF-8:

**Dockerfile:**
```
FROM ubuntu:22.04
# Set the locale to an UTF-8 one (instead of the default ASCII?)
RUN apt-get update && apt-get -y install locales && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
COPY b2-linux /backblaze/b2-linux
RUN chmod +x /backblaze/b2-linux
ENTRYPOINT ["/backblaze/b2-linux"]
```

**Comment by Rolf-Smit** [comment]
Would it make sense to document this behavior somewhere in the README.md for example? Specifically stating that the terminal (or even OS locale settings) may influence which files/folders can be downloaded/uploaded?
