### ISSUE TITLE
How can i get the total size of a specific folder in a bucket?

### ISSUE THREAD

**Issue by dmirallestl** [Backblaze/B2_Command_Line_Tool#885]
We have a bucket were we are storing data related to our clients, the idea is to get the total size used by each client. I don't see any way to get that information from b2-cli, is there any other way such as API call to get this information easily?

**Comment by mjurbanski-reef** [comment]
The way to do this is something like:
```
b2v3 ls -r bucketName path --versions --long| awk '{total+=$5;} END{print total;}'
```
or
```
b2v3 ls -r bucketName path --versions --json|  jq -r '.[].size' | awk '{total+=$1} END {print total}'
```

Remove `--versions` if you want to see only how much space is used by most recent versions.
See https://www.backblaze.com/docs/cloud-storage-lifecycle-rules how to delete old versions automatically.

**Comment by S0yKaf** [comment]
@mjurbanski-reef 
I know I'm bumping an old thread for this. but I love you. You have no idea how much you've just helped me with this answer. Seriously. You've made my week.

Thank you.
