### ISSUE TITLE
B2_DEBUG_HTTP=1 does not seem to have any effect

### ISSUE THREAD

**Issue by dkocher** [Backblaze/B2_Command_Line_Tool#893]
No output is produced with the environment variable set.

> [^1] In order to see the raw request headers you may export B2_DEBUG_HTTP=1 before calling the CLI.

[^1]: https://github.com/Backblaze/B2_Command_Line_Tool/blob/f03e66f40710889e896bcf91dddfc71185b13a7d/README.md?plain=1#L144C1-L145C1

**Comment by mjurbanski-reef** [comment]
Looking at `git log -S B2_DEBUG_HTTP` (in this and b2sdk repository), I'm convinced it never worked, hence I removed it from the readme.

We are open to PRs enabling support for it in b2sdk, and therefor in B2 CLI if it would be useful to you to have it.
