### ISSUE TITLE
Feature request: use b2 cli without saving plaintext credentials in `.b2_account_info`

### ISSUE THREAD

**Issue by joneskoo** [Backblaze/B2_Command_Line_Tool#894]
Currently, when credentials are provided with `B2_APPLICATION_KEY_ID` and `B2_APPLICATION_KEY` environment variables, b2 cli imports them silently to a sqlite database `.b2_account_info`.

It's not ideal to store plaintext credentials on disk when there's more secure secret storage options available. Please support operation without plaintext credentials saved on disk. Concretely, do not store authorisation in global context (file on disk) when credentials are provided from environment.

Reasons why this is important:
 * Current behaviour is surprising and unexpected since most other applications getting secrets from environment treat it as a signal that secrets are provided in environment and do not make copies of the secrets.
 * Storing credentials on disk makes it easy to make insecure CI if build environment is re-used for tasks of different privileges - credentials of one build could be inadvertently used for another build that should have less privileged access.
 * Secrets could be stolen from disk by another application or from disk if full-disk encryption is not used. Storing secrets in secrets manager in encrypted form would help.

Relates to:
* #665 
* https://github.com/1Password/shell-plugins/pull/346

**Comment by mpnowacki-reef** [comment]
Hi! thanks for the feature request we will take this into consideration. For the time being, an official docker image has been released and that somewhat helps with the issue https://github.com/Backblaze/B2_Command_Line_Tool#docker-image, especially if you use `docker run --rm`

**Comment by ppolewicz** [comment]
There are a couple of problems here as credentials are not the only secrets we'd need to safeguard. `SqliteAccountInfo` holds:
1. Bucket-to-id mapping (there is a transaction cost to retrieve it and it's needed for almost every operation, so not caching it causes latency, but it is not really very secret)
2. Keyid and key. Can't really get more secret than that
3. Session token. It's equivalent to keyid+key pair but only valid for 24h (though if the session token is associated with a key which allows for creation of new keys, then whoever intercepts the session token can takes over the account with one http query)
4. Upload tokens. Each can be used to perform an upload. Reusable, but no two uploads can be done at the same time with the same token. These can only be used to put data in the system and they can sometimes break mid-upload, then if you need to get a new upload token before retrying, though an attacker gaining access to the upload tokens can in some scenarios make a real mess (upload malware than the user will download and execute later, thinking it's safe when they thought they hold the only key).

The suggestion posted by @mpnowacki-reef solves all of those problems to an extent - if you run a container for a long-running sync, you should be ok. If, on the other hand, you execute a bunch of commands back-to-back, preserving bucket-to-id mapping will decrease the transaction cost and latency but won't compromise security. If the commands you are running are uploads (typically you could imagine streaming uploads, where a tiny server might want to pg_dump several databases to B2 separately) then reusing upload tokens would be nice, however in such case you'd need to keep the file secure.

What I would suggest in this case, is mapping the `/root` of the container to (properly chmodded) ramdrive. If the entire device is stolen, no secrets will be leaked (assuming they are provisioned for the script from AWS Secrets manager or Hashicorp Vault or something or were encrypted in some other way) as content of the ramdrive won't be preserved across reboots. On the other hand all points 1-4 will be kept ensuring maximum performance.

We do have a use case where a shell user wants to run `b2 authorize_account` and wants to pass the key and key id in a script, however does not want the other users of the system seeing the secrets when they run `ps`. In that use case the user wants to keep 1-4 in the local sqlite file. I do not want to break this workflow by changing the default.

That being said adding support for not writing the file anywhere, but using an in-memory version of SQLite (`sqlite3.connect(":memory:"` someone tried in the related issue) seems like something that should work, so I'm considering adding support for it (I mean checking why it doesn't work already and fixing that unless a really good reason is discovered during the investigation).

@joneskoo would that resolve the issue you are facing?

**Comment by joneskoo** [comment]
Using :memory: or /dev/null is indeed what I tried so I believe it should.

**Comment by ppolewicz** [comment]
If every time you'd have to upload a small file you'd also have to (internally, but it still happens in the background and takes time):
1. authorize-account to trade keyid and key for a session token
2. list-buckets to trade a class C transaction for bucket-to-id mapping
3. get the upload tokens
4. actually upload the file (if it's big then that's actually: start a large file session, upload N parts, finish large file session)

and you are doing this for every small / small-ish file then your performance will drop rather massively without caching these things (not to mention you'll pay for transactions unnecessarily).

The impact of all of this depends a lot on which cluster you are on and how far away from it you are. Latency to c000 from Malaysia or Thailand is very high and you can't miss it in both CLI interaction or transfer speed. Maybe if you are a milisecond away from the newest cluster you wouldn't notice - but in such case put /root of the container (or account info path, or symlink it) in tmpfs and you should be ok. Just chmod it right :)


I'll ask a friend to check why ":memory:" doesn't work.

**Comment by joneskoo** [comment]
The use case is to use a password manager to protect tokens so that they don't stay on disk in plaintext. So encrypting the local cache would be better, :memory: is better than nothing.

**Comment by ppolewicz** [comment]
Lets start with `:memory:`, but is there an API of some sorts to do the cache encryption?

**Comment by rewilliams** [comment]
I landed here for the same reason: I'm trying to use a password manager to handle keys instead of stashing them in plain-text files. Ideal would be to encrypt the cache so we can keep it for performance reasons while letting the password manager handle security.

**Comment by philipmw** [comment]
Tonight I was shocked that I was able to do `b2 sync` when I forgot to set my `B2_APPLICATION...` environment variables. I thought my bucket is accidentally wide open to the world, or there's a bug in Backblaze backend, or something else.

IMO, this is unintuitive behavior and dangerous. I can't think of any other tool that saves its own copy of my ephemeral credentials (from environment variables, which are ephemeral!) into a file on my long-lived filesystem. The closest tool to `b2` is the AWS CLI, where I can also set credentials on the command line, then interact with my S3 storage. It never persists my credentials to the filesystem.

Please just put it in memory, and make this the default.

**Comment by mjurbanski-reef** [comment]
This problem has been resolved in `_b2v4` which is the preview of new `b2` CLI interface in the latest release https://github.com/Backblaze/B2_Command_Line_Tool/releases/tag/v3.18.0 .

If you plan to use it as is, make sure to pin the exact version of `b2` package, as the `_b2v4` interface may be changed even in patch releases. Additionally, when it is officially stabilized and released, the name will change to `b2v4`.
The `b2v3` even with versions >=3.18.0 will kept working as it was, as some users may still rely on this behavior.
