### ISSUE TITLE
Official Docker Image ? 

### ISSUE THREAD

**Issue by rudik99** [Backblaze/B2_Command_Line_Tool#895]
Hi, 

In the documentation there is a reference to an official Docker container: https://github.com/Backblaze/B2_Command_Line_Tool#docker-image

I couldn't find it on docker hub - is it still there?

Also the dockerfile.template doesn't look like a build for b2 cli container?

**Comment by ppolewicz** [comment]
We have the ability to build the docker image (using nox) and run tests on it for a while. It's been running quite smoothly except some license checker thing that sometimes failed and we adjusted for that (at least we think it should be fine now).

I think it's time to release it on the dockerhub and I think the process should begin (and hopefully end) this week. Stay tuned.

**Comment by meonkeys** [comment]
dup of #358

**Comment by mpnowacki-reef** [comment]
The official image has been released https://github.com/Backblaze/B2_Command_Line_Tool#docker-image
