### ISSUE TITLE
switch to stable pypy version after new pypy is released

### ISSUE THREAD

**Issue by mpnowacki-reef** [Backblaze/B2_Command_Line_Tool#936]
the issue has been described here: https://foss.heptapod.net/pypy/pypy/-/issues/4021. Once the problem is out of the way, the fix for it should be removed.

**Comment by mjurbanski-reef** [comment]
workaround has been since removed since it didn't quite solve the issue for all kind of tests and we are using pypy nightly build for now.
As soon as that causes trouble we should switch to stable build `>7.3.13` as it should include the official fix then.
