### ISSUE TITLE
Make an interface below B2RawApi that can be stubbed for testing.

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#95]
The B2RawApi layer and the post_json() function that go with it have enough interesting code in them that they need to be unit tested.  I think the way to do this is to define a super-simple interface that wraps the urllib calls, which can then be stubbed out for testing.

The interface can take (url, headers, data) and return (status, headers, data).  It should be clear about what it returns when the URL is malformed, when there is a broken pipe, when the connection fails, and when there is a timeout.

**Comment by ppolewicz** [comment]
We are going to switch from `urllib2` to `requests` soon anyway and probably we will not change from that in the future. I think mocking `requests` should be enough in this case. That would save us one abstraction layer, but allow for fully testing the logic in question.

**Comment by bwbeach** [comment]
Closing issue.  We now have the B2Http class.
