### ISSUE TITLE
b2 should respect the spec's default fallback for `XDG_CONFIG_HOME`

### ISSUE THREAD

**Issue by salim-b** [Backblaze/B2_Command_Line_Tool#958]
# Intro

Current docs of the b2 CLI [state](https://b2-command-line-tool.readthedocs.io/en/master/#overview)[^brok]:

> This program caches authentication-related and other data in a local SQLite database. The location of this database is determined in the following way:
> 
> If `--profile` arg is provided:
> * `XDG_CONFIG_HOME/b2/db-<profile>.sqlite`, if `XDG_CONFIG_HOME` env var is set
> * `~/.b2db-{profile}.sqlite`
>
> Otherwise:
> * `B2_ACCOUNT_INFO` env var’s value, if set
> * `~/.b2_account_info`, if it exists
> * `XDG_CONFIG_HOME/b2/account_info`, if `XDG_CONFIG_HOME` env var is set
> * `~/.b2_account_info`, as default
>
> If the directory `XDG_CONFIG_HOME/b2` does not exist (and is needed), it is created.

[^brok]: Note that the doc's Markdown formatting is partially broken, see #957

Current source of that documentation states:

https://github.com/Backblaze/B2_Command_Line_Tool/blob/88a0305ac99573efe5405672dfb71fb8517752fa/b2/console_tool.py#L766-L779

# Problem

The problem with the above is the fallback to `~/.b2*`.

The XDG Base Directory specification demands (emphasis by me):

> `XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, **a default equal to `$HOME/.config` should be used**. 

I think most popular Linux distributions like Ubuntu or Arch [do not set](https://wiki.archlinux.org/title/XDG_Base_Directory) the `XDG_CACHE_HOME`, **`XDG_CONFIG_HOME`**, `XDG_DATA_HOME` and `XDG_STATE_HOME` environment variables and [expect programs to fall back to the spec's default paths](https://superuser.com/a/425712/666946).

# Solution

I'd like to propose that b2 properly adheres to the XDG Base Directory specification, meaning to fall back to `$HOME/.config/b2/` if `XDG_CONFIG_HOME` is *un*set.

Related: https://github.com/Backblaze/B2_Command_Line_Tool/issues/699

**Comment by jsuchan-reef** [comment]
Hi,
thanks for the report, we'll look into it.

**Comment by mjurbanski-reef** [comment]
resolved in b2sdk 1.28.0 and thus, `b2` CLI 3.14.0

**Comment by salim-b** [comment]
Thanks. I just tested b2 CLI v3.15.0 and can confirm this to be resolved.

**Comment by ppolewicz** [comment]
@salim-b we appreciate the test and your confirmation. Thank you.
