### ISSUE TITLE
Silently ignore large files

### ISSUE THREAD

**Issue by lukavia** [Backblaze/B2_Command_Line_Tool#98]
I'm trying to sync several directories for backup. 
After A while I get 
```
URL: https://api001.backblaze.com/b2api/v1/b2_start_large_file
Params: None
Headers: {'Authorization': uxxxxxxx', 'User-Agent'
: 'backblaze-b2/0.4.7 python/2.7.6'}

{
  "code": "bad_request",
  "message": "large files not available yet",
  "status": 400
}
```
Which is fine except the sync stops and I'm missing 100G after the large file. 
There should be an option to just show that error and continue and not stop.

**Comment by bwbeach** [comment]
This was my bad.  Get the latest version. 

I enabled large files in the command-line tool before they were enabled in the B2 service.

**Comment by lukavia** [comment]
The latest version work like a charm. 
Thank you very much.
Great work
