### ISSUE TITLE
Feature request: Support transparent compression

### ISSUE THREAD

**Issue by netantho** [Backblaze/B2_Command_Line_Tool#981]
When dealing with a lot of small files, it would be great if b2 and its CLI would support transparent encryption.
As an example, [zstd](https://github.com/facebook/zstd) is a high-performance compression library. It could be used to create packs of small files that could be sent faster over the wire like the open-source [restic](https://restic.readthedocs.io/en/latest/047_tuning_backup_parameters.html) project does. b2's backend could then efficiently decompress the files to make them available in the buckets.

The cost of opening new TCP sockets and SSL/TLS handshakes when dealing with a large number of small files may make the idea cost-efficient.

Given work needed on the proprietary b2 backend, this feature request cannot be implemented by external contributors.

**Comment by ppolewicz** [comment]
Hi,

please submit this request to b2 server team via Backblaze support - this is a repository for the CLI (which will implement the support for compression a few days (or perhaps hours!) after B2 server implements it).

We could implement single-file compression on the CLI side, but the requests issued by the web browser would not automatically decompress the content (unless we force special headers, which the browsers might or might not support).

I see you are also asking for encryption. B2 already supports [server-side encryption](https://www.backblaze.com/docs/cloud-storage-server-side-encryption), though I'm not sure how you wanted to tie those two together.
